/**
 * Deterministic feature usefulness audit for YANG EDGE OS surfaces.
 * No UI mutation — report data only.
 */
import type { FeatureUsefulnessRow } from "./types";

export function buildFeatureUsefulnessAudit(): FeatureUsefulnessRow[] {
  const rows: FeatureUsefulnessRow[] = [
    {
      id: "dashboard",
      name: "Dashboard",
      location: "/internal/dashboard",
      classification: "DAILY_USE",
      dataConnected: true,
      buttonWorks: true,
      suggestion: "KEEP",
      reason: "대표 매일 진입 화면",
    },
    {
      id: "mission",
      name: "Mission Control",
      location: "/internal/mission",
      classification: "DAILY_USE",
      dataConnected: true,
      buttonWorks: true,
      suggestion: "KEEP",
      reason: "오늘 행동 중심",
    },
    {
      id: "cto",
      name: "CTO Room",
      location: "/internal/cto",
      classification: "WEEKLY_USE",
      dataConnected: true,
      buttonWorks: true,
      suggestion: "KEEP",
      reason: "주간 보고 + Decision Center 섹션",
    },
    {
      id: "data-center",
      name: "Data Center",
      location: "/internal/data",
      classification: "WEEKLY_USE",
      dataConnected: true,
      buttonWorks: true,
      suggestion: "KEEP",
      reason: "종목 누적 현황 요약",
    },
    {
      id: "research-lab",
      name: "Research Lab",
      location: "/internal/research",
      classification: "DAILY_USE",
      dataConnected: true,
      buttonWorks: true,
      suggestion: "KEEP",
      reason: "연구 전용 표면",
    },
    {
      id: "engine-center",
      name: "Engine Center",
      location: "/internal/engine",
      classification: "WEEKLY_USE",
      dataConnected: true,
      buttonWorks: true,
      suggestion: "KEEP",
      reason: "읽기 전용 엔진 변수 상태 · weight 수정 없음",
    },
    {
      id: "developer-console",
      name: "Developer Console",
      location: "/internal/developer",
      classification: "DEVELOPER_ONLY",
      dataConnected: true,
      buttonWorks: true,
      suggestion: "KEEP",
      reason: "Hash/Artifact/Runtime — 대표 기본 비노출",
    },
    {
      id: "settings",
      name: "Settings",
      location: "/internal/settings",
      classification: "WEEKLY_USE",
      dataConnected: true,
      buttonWorks: true,
      suggestion: "KEEP",
      reason: "대표 모드 토글",
    },
    {
      id: "operator-home-legacy",
      name: "OperatorHome (legacy)",
      location: "src/components/internal/research/OperatorHome.tsx",
      classification: "DEPRECATED_CANDIDATE",
      dataConnected: true,
      buttonWorks: true,
      suggestion: "DEPRECATE",
      reason: "Dashboard로 대체 · 라우트에서 직접 미사용",
    },
    {
      id: "system-detail",
      name: "SystemDetail",
      location: "/internal/developer (embedded)",
      classification: "DEVELOPER_ONLY",
      dataConnected: true,
      buttonWorks: true,
      suggestion: "MOVE",
      reason: "이미 Developer Console로 이동 완료",
    },
    {
      id: "dev-console-label-chips",
      name: "Developer Console label chips (Hash/Logs/...)",
      location: "DeveloperConsoleView",
      classification: "PLACEHOLDER_ONLY",
      dataConnected: false,
      buttonWorks: false,
      suggestion: "HIDE",
      reason: "라벨만 있고 개별 화면/동작 없음 — SystemDetail이 실데이터",
    },
    {
      id: "epl-schedule-checklist",
      name: "EPL Schedule checklist item",
      location: "Dashboard checklist",
      classification: "PLACEHOLDER_ONLY",
      dataConnected: false,
      buttonWorks: false,
      suggestion: "HIDE",
      reason: "축구 일정 미연결 · OFF 표시만",
    },
    {
      id: "football-nba-volleyball-cards",
      name: "Football/NBA/Volleyball Data Center cards",
      location: "/internal/data",
      classification: "PLACEHOLDER_ONLY",
      dataConnected: false,
      buttonWorks: null,
      suggestion: "KEEP",
      reason: "NOT_STARTED 상태를 정직하게 OFF로 표시 — 가짜 수치 없음",
    },
    {
      id: "cto-brier-logloss-cards",
      name: "CTO Brier/LogLoss summary cards",
      location: "/internal/cto",
      classification: "DUPLICATE",
      dataConnected: false,
      buttonWorks: null,
      suggestion: "KEEP",
      reason: "Scorecard 수치를 복제하지 않고 관찰 안내 문구만 — 오해 방지 유지",
    },
    {
      id: "owner-mode-toggle",
      name: "Owner mode / Advanced disclosure",
      location: "OsShell / Settings",
      classification: "DAILY_USE",
      dataConnected: true,
      buttonWorks: true,
      suggestion: "KEEP",
      reason: "기술 용어 숨김",
    },
    {
      id: "decision-center-section",
      name: "Decision Center (CTO section)",
      location: "/internal/cto#decision-center",
      classification: "WEEKLY_USE",
      dataConnected: true,
      buttonWorks: true,
      suggestion: "KEEP",
      reason: "승인/결정 분리 · 새 메뉴 추가 없음",
    },
  ];

  // Deterministic order
  return rows.slice().sort((a, b) => a.id.localeCompare(b.id));
}
