/** Outcome-blind Official Forward identity/receipt policy. No engine, provider or grade reader. */
import assert from 'node:assert/strict';import {existsSync,readFileSync,readdirSync,mkdirSync,rmdirSync} from 'node:fs';import {join,resolve,dirname,relative} from 'node:path';import {createHash} from 'node:crypto';
export const OFFICIAL_MODEL='football-poisson-research-v1';
export const OFFICIAL_HASH='6efa82f916346599b5e9c6ee4ad768501f7a0d2254dc9d2376acd5df755aadbf';
const stable=(v:unknown):string=>JSON.stringify(v,(_k,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.keys(x).sort().map(k=>[k,x[k]])):x);
export const digest=(v:string|Buffer)=>createHash('sha256').update(v).digest('hex');
const clock=(v:unknown)=>{assert.equal(typeof v,'string');const t=Date.parse(v as string);assert(Number.isFinite(t),'INVALID_TIME');return t;};
const positive=(v:unknown)=>Number.isSafeInteger(v)&&Number(v)>0;
const keys=(v:object,expected:string[])=>assert.deepEqual(Object.keys(v).sort(),expected.sort(),'FORBIDDEN_FIELDS');
function sealed(file:string){const e=JSON.parse(readFileSync(file,'utf8'));assert.equal(e.sha256,digest(stable(e.payload)),'HASH_MISMATCH');return e;}
export type SealCandidate={root:string;fixtureId:number;predictionId:string|null;createdAt:string|null;sealedAt:string|null;scheduledStart:string|null;eligible:boolean;reason:string;identity?:{leagueId:number;season:number;homeTeamId:number;awayTeamId:number};inputHash?:string;snapshot?:any;input?:any;receipt?:any;classification?:'CANONICAL'|'DUPLICATE_NONCANONICAL'|'INVALID_FOR_CANONICAL_COUNT'};
export function inspectOfficialSeal(root:string,fixtureId:number):SealCandidate{
 const row:SealCandidate={root,fixtureId,predictionId:null,createdAt:null,sealedAt:null,scheduledStart:null,eligible:false,reason:'INVALID_FOR_CANONICAL_COUNT'};
 try{assert(positive(fixtureId));const dir=join(root,'MODEL_FORWARD/fixtures',String(fixtureId));const s=sealed(join(dir,'snapshot.json')),p=s.payload;row.predictionId=s.sha256;row.createdAt=p.predictionCreatedAt;row.scheduledStart=p.kickoffUtc;
 const i=sealed(join(dir,'input.json')),r=sealed(join(dir,'seal-receipt.json'));row.inputHash=i.sha256;row.sealedAt=r.payload.sealedAt;
 for(const name of ['miss.json','invalid.json','first-seen-after-kickoff.json'])assert(!existsSync(join(dir,name)),'INVALID_PREGAME_MARKER');
 assert.equal(p.layer,'MODEL_FORWARD');assert.equal(p.status,'PREDICTED');assert.equal(p.modelVersion,OFFICIAL_MODEL);assert.equal(p.modelSourceHash,OFFICIAL_HASH);assert.equal(p.fixtureId,fixtureId);
 assert.equal(p.inputSnapshotHash,i.sha256);assert.equal(r.payload.snapshotHash,s.sha256);assert.equal(r.payload.fixtureId,fixtureId);assert.equal(r.payload.validPregame,true);
 const cutoff=clock(p.cutoffAt),created=clock(p.predictionCreatedAt),sealTime=clock(r.payload.sealedAt),start=clock(p.kickoffUtc);assert(cutoff<=created&&created<=sealTime&&sealTime<start,'UNSAFE_WINDOW');
 const f=i.payload.targetScheduleObservation,t=i.payload.target;assert(f&&t,'SCHEDULE_PROVENANCE_REQUIRED');keys(f,['fixtureId','kickoffUtc','leagueId','season','homeTeam','awayTeam','providerStatus','scheduleFetchedAt']);keys(t,['matchId','competitionId','homeTeamId','awayTeamId','kickoffAt']);
 assert.equal(f.fixtureId,fixtureId);assert.equal(f.leagueId,p.leagueId);assert.equal(f.season,p.season);assert([39,140,135,78].includes(p.leagueId)&&positive(p.season));assert.equal(f.kickoffUtc,p.kickoffUtc);assert.equal(f.providerStatus,'NS');assert(clock(f.scheduleFetchedAt)<=cutoff,'FUTURE_SCHEDULE');
 for(const side of ['homeTeam','awayTeam']){keys(f[side],['id','name']);assert(positive(f[side].id));assert.equal(f[side].id,p[side].id);assert.equal(typeof f[side].name,'string');assert(f[side].name.trim());}assert.notEqual(f.homeTeam.id,f.awayTeam.id);
 assert.equal(t.matchId,'API_FOOTBALL:'+fixtureId);assert.equal(t.competitionId,String(p.leagueId));assert.equal(t.homeTeamId,String(p.homeTeam.id));assert.equal(t.awayTeamId,String(p.awayTeam.id));assert.equal(t.kickoffAt,p.kickoffUtc);assert.equal(i.payload.cutoffAt,p.cutoffAt);
 for(const flag of ['TARGET_RESULT_DATA_USED','ODDS_USED','MARKET_USED','PROVIDER_PREDICTION_USED','OWNER_SHADOW_USED','EXTERNAL_SHADOW_USED'])assert.equal(p[flag],false,'FORBIDDEN_INPUT');
 keys(i.payload,['target','targetScheduleObservation','cutoffAt','completedHistory']);assert(Array.isArray(i.payload.completedHistory));const ids=new Set<number>();
 for(const h of i.payload.completedHistory){keys(h,['providerFixtureId','kickoffUtc','leagueId','homeTeamId','awayTeamId','fixtureStatus','fullTimeHomeGoals','fullTimeAwayGoals','providerFetchedAt','sourceHash']);assert(positive(h.providerFixtureId)&&positive(h.homeTeamId)&&positive(h.awayTeamId));assert.notEqual(h.homeTeamId,h.awayTeamId);assert.notEqual(h.providerFixtureId,fixtureId,'TARGET_IN_HISTORY');assert(!ids.has(h.providerFixtureId),'DUPLICATE_HISTORY');ids.add(h.providerFixtureId);assert.equal(h.fixtureStatus,'FT');assert.equal(h.leagueId,p.leagueId);const kick=clock(h.kickoffUtc),fetched=clock(h.providerFetchedAt);assert(kick<cutoff&&kick>=cutoff-365*86400000&&kick<fetched&&fetched<cutoff,'UNSAFE_HISTORY_TIME');for(const n of [h.fullTimeHomeGoals,h.fullTimeAwayGoals])assert(Number.isSafeInteger(n)&&n>=0);assert.match(h.sourceHash,/^[a-f0-9]{64}$/);}
 assert(Array.isArray(p.trainingProviderFixtureIds));assert.deepEqual([...p.trainingProviderFixtureIds].sort((a,b)=>a-b),[...ids].sort((a,b)=>a-b));assert(Array.isArray(p.trainingFixtureIds)&&p.trainingFixtureIds.every((x:string)=>ids.has(Number(x.replace('API_FOOTBALL:','')))),'UNBOUND_TRAINING_ID');
 row.identity={leagueId:p.leagueId,season:p.season,homeTeamId:p.homeTeam.id,awayTeamId:p.awayTeam.id};row.eligible=true;row.reason='VALID_PREGAME_IDENTITY_INPUT_AND_RECEIPT';row.snapshot=s;row.input=i;row.receipt=r;
 }catch(e){row.reason=e instanceof Error?e.message:'INVALID_SEAL';}return row;
}
export function chooseCanonical(rows:SealCandidate[]){
 const groups=new Map<number,SealCandidate[]>();for(const r of rows){const group=groups.get(r.fixtureId)??[];group.push(r);groups.set(r.fixtureId,group);}const classified:SealCandidate[]=[];
 for(const group of groups.values()){const valid=group.filter(r=>r.eligible).sort((a,b)=>clock(a.sealedAt)-clock(b.sealedAt)||clock(a.createdAt)-clock(b.createdAt)||a.predictionId!.localeCompare(b.predictionId!)||resolve(a.root).localeCompare(resolve(b.root)));const first=valid[0];for(const row of group)classified.push({...row,classification:!row.eligible?'INVALID_FOR_CANONICAL_COUNT':row===first?'CANONICAL':'DUPLICATE_NONCANONICAL'});}
 return classified;
}
export function officialContext(root:string){
 let at=resolve(root);for(;;){if(existsSync(join(at,'package.json'))&&existsSync(join(at,'src/lib/football/poisson-research-v1/index.ts'))){const roots=[join(at,'data/cache/research/football/forward-shadow-v1')],batches=join(at,'data/research/slate-batches');if(existsSync(batches))for(const name of readdirSync(batches)){const b=join(batches,name,'data/cache/research/football/forward-shadow-v1');if(existsSync(b))roots.push(b);}return{managed:true,repository:at,roots:[...new Set([...roots,resolve(root)])]};}const parent=dirname(at);if(parent===at)break;at=parent;}return{managed:false,repository:resolve(root),roots:[resolve(root)]};
}
export function fixtureCandidates(root:string,fixtureId:number){return chooseCanonical(officialContext(root).roots.filter(r=>existsSync(join(r,'MODEL_FORWARD/fixtures',String(fixtureId),'snapshot.json'))).map(r=>inspectOfficialSeal(r,fixtureId)));}
export function canonicalForFixture(root:string,fixtureId:number){return fixtureCandidates(root,fixtureId).find(r=>r.classification==='CANONICAL')??null;}
export function officialInventory(root:string){const rows:SealCandidate[]=[],passes:unknown[]=[];for(const r of officialContext(root).roots){const d=join(r,'MODEL_FORWARD/fixtures');if(!existsSync(d))continue;for(const name of readdirSync(d)){if(!/^\d+$/.test(name)||!existsSync(join(d,name,'snapshot.json')))continue;const row=inspectOfficialSeal(r,Number(name));if(!row.eligible){try{if(sealed(join(d,name,'snapshot.json')).payload.status==='PASS'){passes.push({root:r,fixtureId:Number(name)});continue;}}catch{}}rows.push(row);}}
 const classified=chooseCanonical(rows),canonicalIds=new Set(classified.filter(r=>r.classification==='CANONICAL').map(r=>r.fixtureId));return{rows:classified,counts:{sealedArtifacts:rows.length,uniqueFixtures:new Set(rows.map(r=>r.fixtureId)).size,canonicalPredictions:canonicalIds.size,duplicateNoncanonical:classified.filter(r=>r.classification==='DUPLICATE_NONCANONICAL').length,invalidForCanonicalCount:classified.filter(r=>r.classification==='INVALID_FOR_CANONICAL_COUNT').length},passes:passes.length};}
export function canonicalGradeAllowed(root:string,fixtureId:number,predictionHash:string){if(!officialContext(root).managed)return true;const selected=canonicalForFixture(root,fixtureId);return selected?.predictionId===predictionHash&&resolve(selected.root)===resolve(root);}
export function withOfficialFixtureLock<T>(root:string,fixtureId:number,run:()=>T):T{const c=officialContext(root),dir=c.managed?join(c.repository,'data/cache/research/football/official-fixture-locks-v1'):join(root,'official-fixture-locks-v1');mkdirSync(dir,{recursive:true});const lock=join(dir,String(fixtureId));mkdirSync(lock);try{return run();}finally{rmdirSync(lock);}}
