import assert from 'node:assert/strict';import {writeFileSync,existsSync,mkdirSync} from 'node:fs';import {join} from 'node:path';import {digest,type SealCandidate} from './index';
export const NARRATIVE_HEADINGS=['경기 한줄 요약','경기 전망','홈팀 관점','원정팀 관점','핵심 전술 포인트','핵심 변수','배당 해석','YANG EDGE V1 분석','라인업·부상 상태','최종 프리뷰 요약'] as const;
export function buildSealedNarrative(p:any,c:SealCandidate,createdAt:string,structuredHash:string){
 assert.equal(c.classification,'CANONICAL');assert(c.eligible&&c.snapshot&&c.input);assert.equal(p.canonicalPredictionId,c.predictionId);assert.equal(p.providerFixtureId,c.fixtureId);assert.equal(p.OFFICIAL_V1.predictionId,c.predictionId);assert(Date.parse(createdAt)<Date.parse(c.scheduledStart!),'PREGAME_REQUIRED');const s=c.snapshot.payload;
 for(const k of ['pHome','pDraw','pAway','predictedClass'])assert.equal(p.OFFICIAL_V1[k],s[k],'CANONICAL_VALUES_REQUIRED');
 const city=c.fixtureId===1557413;assert(city||c.fixtureId===1570394,'EXPLICIT_CURRENT_TARGET_ONLY');const home=city?'맨체스터 시티':'아틀레티코 마드리드',away=city?'선덜랜드':'레알 마드리드';
 const h=c.input.payload.completedHistory.filter((r:any)=>r.homeTeamId===s.homeTeam.id),a=c.input.payload.completedHistory.filter((r:any)=>r.awayTeamId===s.awayTeam.id);assert(h.length&&a.length);const avg=(rows:any[],key:string)=>(rows.reduce((n,r)=>n+r[key],0)/rows.length).toFixed(2);const pct=(x:number)=>(100*x).toFixed(2);
 const row=p.oddsEvidence.rows.find((r:any)=>r.number===(city?'3534':'3557'));assert(row&&row.status==='VISIBLE_VALUES_TRANSCRIBED'&&row.market==='');const o=row.odds;assert([o.left,o.middle,o.right].every((n:any)=>typeof n==='number'&&n>1));
 const paragraphs=[
 city?`맨체스터 시티의 홈 승리에 가장 무게가 실린 경기다. YANG EDGE V1의 봉인 확률은 홈 승리 ${pct(s.pHome)}%로, 무승부와 선덜랜드 승리보다 높다. 다만 이는 확정 결과가 아니라 과거 완료 경기 자료로 계산한 모델의 사전 평가다.`:`아틀레티코 마드리드가 모델상 가장 앞서지만, 한쪽으로 기울었다고 보기 어려운 맞대결이다. 홈 승리 ${pct(s.pHome)}%는 세 결과 중 가장 높을 뿐 과반은 아니며, 레알 마드리드 승리와 무승부를 합치면 ${pct(s.pAway+s.pDraw)}%다.`,
 city?`경기 전망의 출발점은 모델이 보여주는 홈 승리 쪽의 큰 확률 차이다. 무승부 ${pct(s.pDraw)}%, 선덜랜드 승리 ${pct(s.pAway)}%도 남아 있으므로 맨시티의 일방적인 승리를 확정할 수는 없다. 실제 점유율이나 슈팅 흐름을 관측한 전망은 아니며, 특정 스코어나 경기 전개를 예고하는 수치도 아니다.`:`V1은 홈 승리, 원정 승리, 무승부 순으로 확률을 배분했다. 레알 승리 ${pct(s.pAway)}%와 무승부 ${pct(s.pDraw)}%가 각각 상당한 비중을 차지한다. 어느 팀이 먼저 주도권을 잡을지까지 확인된 것은 아니므로, 홈팀을 최빈 결과로 선택했다는 사실과 경기 흐름의 확실성을 구분해야 한다.`,
 `${home}의 홈 경기 근거는 canonical 입력에 봉인된 ${h.length}경기다. 이 표본에서 경기당 득점은 ${avg(h,'fullTimeHomeGoals')}골, 실점은 ${avg(h,'fullTimeAwayGoals')}골이었다. ${city?'득점 평균이 실점 평균보다 크게 높았다는 점은 홈팀 우세를 이해하는 데 참고할 수 있다.':'홈에서 득점이 실점보다 많았다는 점은 홈팀을 가장 높은 확률로 평가한 방향과 어긋나지 않는다.'} 이는 봉인 입력의 기술 통계이며 최근 몇 경기의 폼이나 이번 경기 예상 득점으로 바꾸어 읽어서는 안 된다.`,
 `${away}의 원정 경기 표본은 ${a.length}경기로, 경기당 득점 ${avg(a,'fullTimeAwayGoals')}골과 실점 ${avg(a,'fullTimeHomeGoals')}골이 기록돼 있다. ${city?'이 표본에서는 득점보다 실점이 많았다. 맨시티의 홈 기록과 대비되지만, 선덜랜드가 이번에도 같은 경기력을 보인다는 뜻은 아니다.':'이 표본에서는 득점이 실점보다 많았다. 레알의 승리 확률이 0에 가까운 선택지가 아니라는 점과 함께 살펴볼 수 있지만, 이것만으로 모델의 모든 확률 차이를 설명할 수는 없다.'} 선수 구성이나 상대별 전술 차이는 이 평균에 별도로 반영해 설명할 근거가 없다.`,
 '핵심 전술 포인트는 현재 제한적으로만 다룰 수 있다. 검증된 점유율, 빌드업 경로, 압박 강도, 전환 속도, 측면 활용이나 세트피스 자료가 연결돼 있지 않다. 따라서 특정 팀이 높은 압박을 하거나 수비 블록을 낮출 것이라는 통상적인 설명을 덧붙이지 않는다. 전술 상세 수준은 LIMITED이며, 현재는 과거 득실점과 봉인 확률의 범위에서 판단한다.',
 '핵심 변수는 실제 선발과 부상·징계 상태를 어느 정도 확인할 수 있느냐이다. 현재 확보된 선수 소속 registry는 선수가 어느 팀에 소속된 것으로 관측됐는지를 보여줄 뿐, 출전이나 건강 상태를 보장하지 않는다. 또 이 모델 판단은 9월 13일에 봉인된 것으로, 이후에 확보하는 배당이나 선수 정보를 반영한 최신 재계산값이 아니다.',
 `인간 확인된 Round 111 ${row.number}번 행의 배당은 화면 좌·중·우 순으로 ${o.left.toFixed(2)} / ${o.middle.toFixed(2)} / ${o.right.toFixed(2)}다. 가장 낮은 숫자는 ${city?'왼쪽':'오른쪽'}에 있다. 다만 봉인 전사에서 이 행의 시장명이 비어 있고 선택지 연결은 미확정으로 남아 있다. 좌·중·우가 일반 승무패의 홈승·무승부·원정승이라는 전제가 확인된다면, ${city?'시장과 V1은 모두 홈팀 쪽을 더 높게 평가하는 방향으로 읽을 수 있다.':'시장은 레알 쪽, V1은 Atlético 쪽에 무게를 두는 차이로 읽을 수 있다.'} 현재는 조건부 해석이며 방향 일치를 확정하지 않는다. 낮은 배당은 해당 선택지의 상대적 시장 평가를 뜻할 수 있지만, 적중이나 수익을 보장하지 않고 가치 베팅 판정도 아니다.`,
 `YANG EDGE V1의 확률은 홈 승리 ${pct(s.pHome)}%, 무승부 ${pct(s.pDraw)}%, 원정 승리 ${pct(s.pAway)}%이며 모델 선택은 HOME이다. 봉인 모델은 같은 리그의 과거 완료 경기에서 홈팀의 홈 득실점과 원정팀의 원정 득실점을 사용하고, 리그 득점 평균으로 작은 표본을 보완한 뒤 독립 Poisson 가정으로 승·무·패를 계산한다. 이번 글은 그 입력 중 ${c.input.payload.completedHistory.length}경기의 범위와 홈·원정 표본을 설명했을 뿐 모델을 다시 실행하지 않았다. 선발, 부상, 시장 배당이나 전술 우위를 원인으로 붙이지 않으며 이 수치가 보정된 실제 적중률이라고 단정하지 않는다.`,
 '현재 이 프리뷰에 연결된 유효한 선발 XI 및 부상·징계 관측은 없다. 따라서 선발은 NOT_CONFIRMED, 부상과 징계는 UNKNOWN으로 남긴다. 이를 “아직 발표되지 않았다”거나 “결장자가 없다”는 사실로 바꾸어 말하지 않는다. 실제 XI가 정확한 팀과 11명의 고유 선수, registry 소속 검증을 통과하면 새 본문 버전을 작성하되 기존 V1 확률은 그대로 유지한다.',
 city?'이번 프리뷰의 중심은 맨시티 쪽에 높은 비중을 둔 canonical V1 판단이다. 다만 모델이 보지 않은 현재 선수 상태와 전술 세부는 여전히 빈칸이며, 배당 방향 비교에도 시장 선택지 확인이 필요하다. 홈팀 우세라는 모델 해석을 유지하면서도 미확인 정보를 승리 확신으로 메우지 않는 것이 현재의 결론이다.':'현재 결론은 Atlético를 가장 높은 확률의 결과로 보되, 레알 승리와 무승부의 합산 가능성을 함께 놓고 읽어야 한다는 것이다. 확실한 홈 우세나 일방적인 경기로 표현할 근거는 부족하다. 선발·가용 선수에 관한 실제 사전 증거가 확보되기 전까지 전술과 선수별 영향 평가는 보류한다.',
 ];
 const body=paragraphs.map((text,i)=>`## ${NARRATIVE_HEADINGS[i]}\n\n${text}`).join('\n\n');const version=1,targetId=p.TARGET_ID,canonicalPredictionId=c.predictionId!;
 return{previewId:digest(JSON.stringify([targetId,canonicalPredictionId,'PREVIEW_PRE_LINEUP',version])),targetId,canonicalPredictionId,version,createdAt,status:'PREVIEW_PRE_LINEUP',narrativeStatus:'PRE_LINEUP_NARRATIVE',headline:`${home} vs ${away} — ${city?'홈 우세를 가리키는 모델, 선발 확인은 별도':'홈팀 최빈 판단과 남아 있는 세 갈래 가능성'}`,matchInfo:`${p.competition} · ${p.kickoffKst.slice(0,10)} ${p.kickoffKst.slice(11,16)} KST · ${home} 홈 / ${away} 원정`,summary:paragraphs[0],body,engineAnalysis:paragraphs[7],oddsAnalysis:paragraphs[6],lineupAnalysis:paragraphs[8],dataQualityNote:'Canonical 봉인·과거 FT 기술 통계·인간 확인 배당만 사용. 전술 LIMITED, XI 미확인, 부상·징계 UNKNOWN, 시장 선택지 의미 미확정.',evidenceIds:[canonicalPredictionId,s.inputSnapshotHash,'canonicalization-v1/mandatory-previews-v5.json',...p.registrySourceHashes],evidenceHashes:[canonicalPredictionId,s.inputSnapshotHash,structuredHash,p.oddsEvidence.sourceSha256,...p.oddsEvidence.rows.map((r:any)=>r.source.sha256),...p.registrySourceHashes],TACTICAL_DETAIL_LEVEL:'LIMITED',LINEUP_STATUS:'NOT_CONFIRMED',MARKET_SELECTION_MAPPING:'UNRESOLVED',MODEL_RECOMPUTED:false,TARGET_RESULTS_ACCESSED:false,wordCount:body.trim().split(/\s+/u).length,wordCountMethod:'WHITESPACE_TOKENS_KOREAN_EOJEOL_INCLUDING_HEADINGS'};
}
export function narrativeMarkdown(n:ReturnType<typeof buildSealedNarrative>){return `# ${n.headline}\n\n${n.matchInfo}\n\n작성: ${n.createdAt} · PRE_LINEUP NARRATIVE v${n.version}\n\n${n.body}\n\n---\n\n근거: canonical Prediction \`${n.canonicalPredictionId}\`.\n\n${n.dataQualityNote}\n`;}
export function sealNarrativePair(directory:string,stem:string,n:ReturnType<typeof buildSealedNarrative>){assert(/^[A-Za-z0-9_-]+$/.test(stem));mkdirSync(directory,{recursive:true});const json=join(directory,stem+'.json'),md=join(directory,stem+'.md');assert(!existsSync(json)&&!existsSync(md),'NARRATIVE_VERSION_EXISTS');writeFileSync(json,JSON.stringify(n,null,2)+'\n',{flag:'wx'});writeFileSync(md,narrativeMarkdown(n),{flag:'wx'});return{json,md};}
