import assert from 'node:assert/strict';import {writeFileSync} from 'node:fs';import type {SealCandidate} from './index';
/** New version only. Never retain a stale batch probability object alongside the canonical one. */
export function canonicalPreview(previous:any,selected:SealCandidate,createdAt:string,previousVersion:string,previousVersionSha256:string){
 assert.equal(selected.classification,'CANONICAL');assert(selected.eligible&&selected.snapshot&&selected.input);assert.equal(previous.providerFixtureId,selected.fixtureId);assert(Date.parse(createdAt)<Date.parse(selected.scheduledStart!),'PREVIEW_AFTER_KICKOFF');const p=selected.snapshot.payload;
 assert.equal(p.homeTeam.id,previous.providerHomeTeamId);assert.equal(p.awayTeam.id,previous.providerAwayTeamId);assert.equal(Date.parse(p.kickoffUtc),Date.parse(previous.kickoffKst));
 const official={modelVersion:p.modelVersion,modelSourceHash:p.modelSourceHash,predictionCreatedAt:p.predictionCreatedAt,pHome:p.pHome,pDraw:p.pDraw,pAway:p.pAway,predictedClass:p.predictedClass,predictionId:selected.predictionId,inputSnapshotHash:p.inputSnapshotHash};
 return {schemaVersion:'PRIORITY_CANONICAL_PREVIEW_V1',TARGET_ID:previous.TARGET_ID,providerFixtureId:selected.fixtureId,providerHomeTeamId:p.homeTeam.id,providerAwayTeamId:p.awayTeam.id,TEAM_PRIORITY:previous.TEAM_PRIORITY,MATCH_PRIORITY:previous.MATCH_PRIORITY,PREVIEW_REQUIRED:true,PREVIEW_STATUS:'PREVIEW_PRE_LINEUP',createdAt,previousVersion,previousVersionSha256,canonicalPredictionId:selected.predictionId,canonicalSelectionReason:'EARLIEST_VALID_PREGAME_SEAL',OFFICIAL_ENGINE:'V1',OFFICIAL_V1:official,home:previous.home,away:previous.away,competition:previous.competition,kickoffKst:previous.kickoffKst,venue:'UNKNOWN',oddsEvidence:previous.oddsEvidence,registryReady:previous.registryReady,registrySourceHashes:previous.registrySourceHashes,operatorScopeProof:previous.inputProof,operatorScopeProofRole:'BATCH_IDENTITY_ONLY_NOT_CANONICAL_MODEL_INPUT',historicalTeamContext:[p.homeTeam.id,p.awayTeam.id].map(teamId=>({teamId,completedInputMatches:selected.input.payload.completedHistory.filter((h:any)=>h.homeTeamId===teamId||h.awayTeamId===teamId).length,sourceInputHash:p.inputSnapshotHash,role:'CANONICAL_SEALED_PAST_COMPLETED_INPUT_ONLY'})),evidenceIds:[selected.predictionId,p.inputSnapshotHash],evidenceSha256:[selected.predictionId,p.inputSnapshotHash,...previous.registrySourceHashes],lineupStatus:'NOT_CONFIRMED',injuryStatus:'UNKNOWN',suspensionStatus:'UNKNOWN',dataQuality:'CANONICAL_PREGAME_MODEL_AND_EXACT_MEMBERSHIP; XI_INJURY_VENUE_UNAVAILABLE',pollPlanKst:previous.pollPlanKst,realV4EvidenceCount:0,featureAdmissionAllowed:false,noncanonicalBatchPredictionPreserved:true,nextUpdate:'Append PREVIEW_XI_AVAILABLE only after exact VALID XI evidence at a frozen window.'};
}
export function writePreviewVersion(file:string,value:unknown){writeFileSync(file,JSON.stringify(value,null,2)+'\n',{flag:'wx'});}
