/**
 * Assemble the player-condition feature audit document.
 */
import {
  PLAYER_CONDITION_AUDIT_V1_BUILDER,
  PLAYER_CONDITION_AUDIT_V1_SCHEMA,
  type PlayerConditionFeatureAuditV1,
} from "./types";
import {
  PLAYER_CONDITION_FEATURE_CATALOG,
  countStages,
} from "./catalog";

export const MLB_CACHE_EVIDENCE = {
  note: "Local gitignored Stats API research cache inspected 2026-08-20. Not a Provider contract. Hitting gameLog was never fetched.",
  pitchingGameLogObservedKeys: [
    "airOuts",
    "atBats",
    "avg",
    "balks",
    "baseOnBalls",
    "battersFaced",
    "blownSaves",
    "catchersInterference",
    "caughtStealing",
    "caughtStealingPercentage",
    "completeGames",
    "doubles",
    "earnedRuns",
    "era",
    "flyOuts",
    "gamesFinished",
    "gamesPitched",
    "gamesPlayed",
    "gamesStarted",
    "groundIntoDoublePlay",
    "groundOuts",
    "groundOutsToAirouts",
    "hitBatsmen",
    "hitByPitch",
    "hits",
    "hitsPer9Inn",
    "holds",
    "homeRuns",
    "homeRunsPer9",
    "inheritedRunners",
    "inheritedRunnersScored",
    "inningsPitched",
    "intentionalWalks",
    "losses",
    "numberOfPitches",
    "obp",
    "ops",
    "outs",
    "pickoffs",
    "pitchesPerInning",
    "runs",
    "runsScoredPer9",
    "sacBunts",
    "sacFlies",
    "saveOpportunities",
    "saves",
    "shutouts",
    "slg",
    "stolenBasePercentage",
    "stolenBases",
    "strikeOuts",
    "strikePercentage",
    "strikeoutWalkRatio",
    "strikeoutsPer9Inn",
    "strikes",
    "summary",
    "totalBases",
    "triples",
    "walksPer9Inn",
    "whip",
    "wildPitches",
    "winPercentage",
    "wins",
  ],
  personObservedKeys: [
    "active",
    "batSide",
    "pitchHand",
    "fullName",
    "id",
    "primaryPosition",
  ],
  scheduleObservedKeys: [
    "dayNight",
    "doubleHeader",
    "gameDate",
    "gamePk",
    "lineups",
    "officialDate",
    "status",
    "teams",
    "venue",
  ],
  boxGameBattingObservedKeys: [
    "atBats",
    "baseOnBalls",
    "doubles",
    "hits",
    "homeRuns",
    "plateAppearances",
    "rbi",
    "stolenBases",
    "strikeOuts",
    "totalBases",
    "triples",
  ],
  venueFieldInfoObservedKeys: [
    "capacity",
    "center",
    "left",
    "right",
    "roofType",
    "turfType",
  ],
  venueLocationObservedKeys: [
    "azimuthAngle",
    "defaultCoordinates",
    "elevation",
  ],
  hittingGameLogFetched: false as const,
  seasonHittingObservedInPregameBoxscoreSample: false as const,
  scheduleWeatherHydratedInSample: false as const,
};

export function buildPlayerConditionAuditDocument(input: {
  generatedAt: string;
  gitBefore: PlayerConditionFeatureAuditV1["gitBefore"];
  previousMethodologyAuditCommit: string;
}): PlayerConditionFeatureAuditV1 {
  const rows = PLAYER_CONDITION_FEATURE_CATALOG;
  return {
    schemaVersion: PLAYER_CONDITION_AUDIT_V1_SCHEMA,
    builderVersion: PLAYER_CONDITION_AUDIT_V1_BUILDER,
    generatedAt: input.generatedAt,
    researchOnly: true,
    mutation: {
      predictionSnapshotsModified: 0,
      engineWeightsModified: 0,
      predictionLogicModified: 0,
      providerCalls: 0,
    },
    gitBefore: input.gitBefore,
    previousMethodologyAuditCommit: input.previousMethodologyAuditCommit,
    marketInPlayerStrength: false,
    independentModelSample: 0,
    weights: "UNDEFINED",
    todayAdjustedPlayerStrength: {
      formula:
        "BaseStrength + RecentConditionAdjustment + MatchupAdjustment + AvailabilityAdjustment + WorkloadAdjustment + EnvironmentAdjustment",
      weights: "UNDEFINED",
      marketInputsAllowed: false,
      notes: [
        "Conceptual identity only. No numeric adjustments in this mission.",
        "Availability on roster ≠ able to produce baseline performance.",
        "Environment is an interaction candidate, never a standalone weather weight.",
        "Small-sample splits must carry SplitReliabilityMeta before Engine admission.",
      ],
    },
    availabilityStatuses: [
      "CONFIRMED_STARTER",
      "EXPECTED_STARTER",
      "BENCH",
      "INJURED",
      "SUSPENDED",
      "QUESTIONABLE",
      "LIMITED",
      "RETURN_FROM_INJURY",
      "MINUTES_OR_PITCH_RESTRICTION",
      "REST_POSSIBILITY",
      "UNKNOWN",
    ],
    shrinkagePolicy: {
      observedSplitThenReliabilityThenShrink: true,
      coefficientsFrozen: false,
      smallSampleSpecialistForbidden: true,
    },
    mlbCacheEvidence: MLB_CACHE_EVIDENCE,
    rows,
    stageCounts: countStages(rows),
  };
}
