import type { AnalysisData } from "@/types/analysis";

export const ANALYSIS_BY_GAME_ID: Record<string, AnalysisData> = {
  "npb-softbank-orix": {
    gameId: "npb-softbank-orix",
    league: "NPB",
    homeTeam: "소프트뱅크",
    awayTeam: "오릭스",
    startTime: "18:00",
    pickTeam: "소프트뱅크",
    starRating: 5,
    winProbability: 71,
    confidence: 92,
    edgeScore: 18,
    grade: "A+",
    summary: "선발과 불펜 우위가 커 소프트뱅크가 유리합니다.",
    reasons: [
      {
        id: "sb-1",
        title: "선발 매치업 우위",
        detail: "소프트뱅크 선발 ERA 1.98 vs 오릭스 선발 ERA 3.41. 이닝당 출루 허용에서도 뚜렷한 차이.",
        icon: "pitcher",
      },
      {
        id: "sb-2",
        title: "홈 구장 이점",
        detail: "페이페이 돔 홈 승률 68%. 최근 홈 10경기 중 8승.",
        icon: "home",
      },
      {
        id: "sb-3",
        title: "타선 OPS 상승세",
        detail: "최근 7경기 팀 OPS .812. 중심 타선 장타율이 시즌 평균 대비 +45pt.",
        icon: "offense",
      },
      {
        id: "sb-4",
        title: "불펜 ERA 우위",
        detail: "불펜 ERA 2.21 vs 상대 3.55. 7회 이후 실점률이 리그 최저권.",
        icon: "bullpen",
      },
      {
        id: "sb-5",
        title: "시즌 상대전적 우세",
        detail: "시즌 상대전적 5승 2패. 홈에서만 3승 0패.",
        icon: "h2h",
      },
      {
        id: "sb-6",
        title: "최근 5경기 폼",
        detail: "소프트뱅크 4승 1패, 오릭스 2승 3패. 득실차 +9 vs -4.",
        icon: "form",
      },
      {
        id: "sb-7",
        title: "수비 효율 우위",
        detail: "팀 DER .715로 리그 상위. 내야 실책이 최근 5경기 1개에 불과.",
        icon: "defense",
      },
      {
        id: "sb-8",
        title: "휴식일 이점",
        detail: "소프트뱅크 1일 휴식 후 등판. 오릭스는 연전 3일차.",
        icon: "rest",
      },
    ],
    risks: ["주전 타자 출전 여부 확인", "최근 불펜 사용량 증가"],
    expectedHomeScore: 5,
    expectedAwayScore: 3,
  },
  "npb-hanshin-yomiuri": {
    gameId: "npb-hanshin-yomiuri",
    league: "NPB",
    homeTeam: "한신",
    awayTeam: "요미우리",
    startTime: "18:00",
    pickTeam: "한신",
    starRating: 4,
    winProbability: 64,
    confidence: 84,
    edgeScore: 12,
    grade: "A",
    summary: "홈 이점과 선발 안정성으로 한신이 소폭 유리합니다.",
    reasons: [
      {
        id: "hs-1",
        title: "고시엔 홈 강세",
        detail: "홈 승률 64%. 야간전 홈 평균 득점 4.8점으로 시즌 평균 상회.",
        icon: "home",
      },
      {
        id: "hs-2",
        title: "선발 QS 비율",
        detail: "한신 선발 최근 5경기 QS 4회. 요미우리 선발은 2회.",
        icon: "pitcher",
      },
      {
        id: "hs-3",
        title: "수비 안정성",
        detail: "최근 10경기 실책 3개. 외야 보살도 리그 상위권.",
        icon: "defense",
      },
      {
        id: "hs-4",
        title: "하위 타선 생산력",
        detail: "7~9번 타순 최근 OPS .740. 추가점 창출 능력이 높음.",
        icon: "offense",
      },
      {
        id: "hs-5",
        title: "불펜 셋업 안정",
        detail: "8회 셋업맨 WHIP 1.05. 리드 상황 방어율이 우수.",
        icon: "bullpen",
      },
      {
        id: "hs-6",
        title: "상대전적 균형 속 홈 우위",
        detail: "시즌 상대 3승 3패이나 홈에서는 2승 1패.",
        icon: "h2h",
      },
      {
        id: "hs-7",
        title: "최근 폼 우위",
        detail: "한신 최근 6경기 4승 2패. 요미우리는 3승 3패.",
        icon: "form",
      },
    ],
    risks: ["타선 기복", "불펜 소모"],
    expectedHomeScore: 4,
    expectedAwayScore: 3,
  },
  "npb-orix-hiroshima": {
    gameId: "npb-orix-hiroshima",
    league: "NPB",
    homeTeam: "오릭스",
    awayTeam: "히로시마",
    startTime: "18:00",
    pickTeam: "오릭스",
    starRating: 3,
    winProbability: 58,
    confidence: 76,
    edgeScore: 8,
    grade: "B+",
    summary: "선발 매치업은 팽팽하나 홈 이점이 오릭스에 있습니다.",
    reasons: [
      {
        id: "or-1",
        title: "홈 구장 이점",
        detail: "쿄세라 돔 홈 승률 59%. 야간전에서 평균 실점이 낮음.",
        icon: "home",
      },
      {
        id: "or-2",
        title: "시즌 상대전적",
        detail: "히로시마 상대 4승 2패. 홈 한정 3승 0패.",
        icon: "h2h",
      },
      {
        id: "or-3",
        title: "선발 K/9 우위",
        detail: "오릭스 선발 K/9 9.1. 탈삼진으로 위기를 끊는 패턴이 뚜렷.",
        icon: "pitcher",
      },
      {
        id: "or-4",
        title: "중견·우익 수비 범위",
        detail: "외야 Outs Above Average +6. 장타 억제에 유리.",
        icon: "defense",
      },
      {
        id: "or-5",
        title: "불펜 레버리지 상황",
        detail: "고레버리지 이닝 ERA 2.80. 접전 시 마무리가 안정적.",
        icon: "bullpen",
      },
      {
        id: "or-6",
        title: "주간 로스터 휴식",
        detail: "핵심 야수 2명이 1일 휴식 후 복귀. 선발 라인업 풀파워 예상.",
        icon: "rest",
      },
    ],
    risks: ["타선 침체", "선발 최근 성적 하락"],
    expectedHomeScore: 3,
    expectedAwayScore: 2,
  },
  "kbo-lg-doosan": {
    gameId: "kbo-lg-doosan",
    league: "KBO",
    homeTeam: "LG",
    awayTeam: "두산",
    startTime: "18:30",
    pickTeam: "LG",
    starRating: 4,
    winProbability: 67,
    confidence: 88,
    edgeScore: 14,
    grade: "A",
    summary: "선발과 불펜 모두 우위라 LG가 유리한 매치업입니다.",
    reasons: [
      {
        id: "lg-1",
        title: "선발 FIP 우위",
        detail: "LG 선발 FIP 2.85 vs 두산 3.92. 순수 투구 지표에서 격차 큼.",
        icon: "pitcher",
      },
      {
        id: "lg-2",
        title: "잠실 홈 이점",
        detail: "홈 승률 61%. 잠실 넓은 외야가 LG 투수진에 유리하게 작용.",
        icon: "home",
      },
      {
        id: "lg-3",
        title: "불펜 WAR 1위권",
        detail: "불펜 ERA 2.95, WHIP 1.18. 7회 이후 승률 보존력이 높음.",
        icon: "bullpen",
      },
      {
        id: "lg-4",
        title: "타선 출루율",
        detail: "팀 OBP .345. 볼넷 유도 후 연속 안타로 득점하는 패턴.",
        icon: "offense",
      },
      {
        id: "lg-5",
        title: "시즌 상대 우위",
        detail: "두산 상대 6승 3패. 최근 맞대결 3연승.",
        icon: "h2h",
      },
      {
        id: "lg-6",
        title: "최근 10경기 폼",
        detail: "LG 7승 3패, 평균 실점 3.1. 두산은 5승 5패.",
        icon: "form",
      },
      {
        id: "lg-7",
        title: "내야 수비 전환",
        detail: "더블플레이 성공률 리그 2위. 병살로 이닝을 끝내는 비중 높음.",
        icon: "defense",
      },
    ],
    risks: ["두산 타선 폭발 가능성"],
    expectedHomeScore: 5,
    expectedAwayScore: 3,
  },
  "kbo-kia-ssg": {
    gameId: "kbo-kia-ssg",
    league: "KBO",
    homeTeam: "KIA",
    awayTeam: "SSG",
    startTime: "18:30",
    pickTeam: "KIA",
    starRating: 4,
    winProbability: 62,
    confidence: 81,
    edgeScore: 10,
    grade: "A",
    summary: "홈 타선 화력이 강점으로 KIA가 소폭 우세합니다.",
    reasons: [
      {
        id: "kia-1",
        title: "챔필 홈런 파크팩터",
        detail: "홈 구장 장타 친화. KIA 홈 경기 평균 득점 5.6점.",
        icon: "home",
      },
      {
        id: "kia-2",
        title: "중심 타선 ISO",
        detail: "3~5번 ISO .220 이상. 한 방으로 리드를 뒤집는 빈도 높음.",
        icon: "offense",
      },
      {
        id: "kia-3",
        title: "최근 승세",
        detail: "최근 8경기 6승 2패. 연승 구간에서 타선 집중력이 좋음.",
        icon: "form",
      },
      {
        id: "kia-4",
        title: "선발 구위 지표",
        detail: "평균 구속·회전수 모두 시즌 상위. 초구 스트라이크율 64%.",
        icon: "pitcher",
      },
      {
        id: "kia-5",
        title: "클러치 상황 타율",
        detail: "득점권 타율 .298. SSG 득점권 타율 .251 대비 우위.",
        icon: "clutch",
      },
      {
        id: "kia-6",
        title: "상대전적",
        detail: "시즌 SSG 상대 5승 3패. 홈에서는 3승 1패.",
        icon: "h2h",
      },
      {
        id: "kia-7",
        title: "불펜 숏이닝 운영",
        detail: "최근 경기 불펜 1이닝 단위 운영으로 효율이 개선됨.",
        icon: "bullpen",
      },
    ],
    risks: ["선발 기복", "불펜 과부하"],
    expectedHomeScore: 6,
    expectedAwayScore: 4,
  },
  "kleague-ulsan-jeonbuk": {
    gameId: "kleague-ulsan-jeonbuk",
    league: "K리그",
    homeTeam: "울산",
    awayTeam: "전북",
    startTime: "19:00",
    pickTeam: "울산",
    starRating: 4,
    winProbability: 65,
    confidence: 85,
    edgeScore: 11,
    grade: "A",
    summary: "홈 압박과 중원 지배력이 높아 울산이 유리합니다.",
    reasons: [
      {
        id: "ul-1",
        title: "문수 홈 승률",
        detail: "홈 승률 72%. 홈 관중 압박 속에서 전반 선제골 비율 높음.",
        icon: "home",
      },
      {
        id: "ul-2",
        title: "중원 점유율",
        detail: "최근 5경기 평균 점유율 58%. 패스 성공률 86%.",
        icon: "possession",
      },
      {
        id: "ul-3",
        title: "xG 우위",
        detail: "최근 5경기 xG 1.8 vs 상대 0.9. 기회 질에서 앞섬.",
        icon: "offense",
      },
      {
        id: "ul-4",
        title: "세트피스 위협",
        detail: "코너킥·프리킥 득점이 시즌 8골. 전북 세트피스 실점 경계 필요.",
        icon: "setpiece",
      },
      {
        id: "ul-5",
        title: "최근 폼",
        detail: "울산 4승 1무, 전북 2승 2무 1패. 승점 페이스 우위.",
        icon: "form",
      },
      {
        id: "ul-6",
        title: "수비 라인 안정",
        detail: "무실점 경기 비율 40%. PPDA(압박 지표)도 리그 상위.",
        icon: "defense",
      },
      {
        id: "ul-7",
        title: "맞대결 홈 기록",
        detail: "최근 홈 전북전 3경기 2승 1무. 패배 없음.",
        icon: "h2h",
      },
    ],
    risks: ["전북 역습 위협", "세트피스 실점"],
    expectedHomeScore: 2,
    expectedAwayScore: 1,
  },
  "epl-arsenal-liverpool": {
    gameId: "epl-arsenal-liverpool",
    league: "EPL",
    homeTeam: "아스널",
    awayTeam: "리버풀",
    startTime: "23:30",
    pickTeam: "아스널",
    starRating: 3,
    winProbability: 54,
    confidence: 72,
    edgeScore: 6,
    grade: "B+",
    summary: "홈 이점이 있으나 팽팽한 빅매치로 신중한 접근이 필요합니다.",
    reasons: [
      {
        id: "ars-1",
        title: "에미레이츠 홈 이점",
        detail: "홈 승률 70%. 빅6 상대 홈에서도 승점 확보율이 높음.",
        icon: "home",
      },
      {
        id: "ars-2",
        title: "수비 xGA 억제",
        detail: "최근 6경기 xGA 0.85. 세트피스 수비 조직력이 개선됨.",
        icon: "defense",
      },
      {
        id: "ars-3",
        title: "하프스페이스 침투",
        detail: "인사이드 포워드 침투로 만든 슈팅이 경기당 4.2회.",
        icon: "offense",
      },
      {
        id: "ars-4",
        title: "중원 듀얼 승률",
        detail: "그라운드 듀얼 승률 54%. 2선 압박 전환이 빠름.",
        icon: "possession",
      },
      {
        id: "ars-5",
        title: "세트피스 xG",
        detail: "세트피스 xG 시즌 상위 3. 코너 킥 루틴이 다양함.",
        icon: "setpiece",
      },
      {
        id: "ars-6",
        title: "최근 홈 폼",
        detail: "홈 5경기 4승 1무. 무실점 3회.",
        icon: "form",
      },
    ],
    risks: ["리버풀 공격력", "빅매치 변수"],
    expectedHomeScore: 2,
    expectedAwayScore: 2,
  },
  "laliga-real-barca": {
    gameId: "laliga-real-barca",
    league: "라리가",
    homeTeam: "레알 마드리드",
    awayTeam: "바르셀로나",
    startTime: "04:00",
    pickTeam: "레알 마드리드",
    starRating: 4,
    winProbability: 60,
    confidence: 79,
    edgeScore: 9,
    grade: "A",
    summary: "홈 무대 강세와 최근 폼으로 레알이 소폭 우세합니다.",
    reasons: [
      {
        id: "rm-1",
        title: "베르나베우 홈 강세",
        detail: "홈 승률 78%. 엘클라시코 홈 최근 4경기 3승 1무.",
        icon: "home",
      },
      {
        id: "rm-2",
        title: "최근 공격 폼",
        detail: "최근 5경기 14골. 트랜지션 득점 비중이 높음.",
        icon: "form",
      },
      {
        id: "rm-3",
        title: "세트피스 효율",
        detail: "세트피스 득점률 리그 2위. 코너 킥 2선 침투 패턴이 유효.",
        icon: "setpiece",
      },
      {
        id: "rm-4",
        title: "역습 속도",
        detail: "공격 전환 평균 8.4초. 바르사 높은 라인 뒤 공간을 노림.",
        icon: "pace",
      },
      {
        id: "rm-5",
        title: "클러치 득점력",
        detail: "75분 이후 득점이 시즌 11골. 후반 집중력이 강점.",
        icon: "clutch",
      },
      {
        id: "rm-6",
        title: "맞대결 홈 우위",
        detail: "최근 홈 바르사전 승점 평균 2.25.",
        icon: "h2h",
      },
      {
        id: "rm-7",
        title: "슈팅 전환율",
        detail: "박스 안 슈팅 정확도 48%. 결정력 지표에서 앞섬.",
        icon: "offense",
      },
    ],
    risks: ["바르사 점유율", "개인기 변수"],
    expectedHomeScore: 3,
    expectedAwayScore: 2,
  },
  "kbl-seoul-anyang": {
    gameId: "kbl-seoul-anyang",
    league: "KBL",
    homeTeam: "서울 SK",
    awayTeam: "안양",
    startTime: "19:00",
    pickTeam: "서울 SK",
    starRating: 4,
    winProbability: 66,
    confidence: 86,
    edgeScore: 13,
    grade: "A",
    summary: "리바운드와 수비 효율에서 서울 SK가 앞섭니다.",
    reasons: [
      {
        id: "sk-1",
        title: "홈 코트 이점",
        detail: "홈 승률 67%. 홈 평균 득점 84.2점.",
        icon: "home",
      },
      {
        id: "sk-2",
        title: "리바운드 점유",
        detail: "리바운드율 53.8%. 공격 리바운드 후 2차 득점 비중 높음.",
        icon: "rebound",
      },
      {
        id: "sk-3",
        title: "수비 효율(DRtg)",
        detail: "DRtg 108.4로 리그 상위. 상대 eFG% 억제에 강점.",
        icon: "defense",
      },
      {
        id: "sk-4",
        title: "페이스 통제",
        detail: "경기 페이스를 낮춰 하프코트 수비 비중을 높이는 운영.",
        icon: "pace",
      },
      {
        id: "sk-5",
        title: "페인트존 득점",
        detail: "골밑 득점 비중 42%. 안양 골밑 수비 약점을 공략 가능.",
        icon: "offense",
      },
      {
        id: "sk-6",
        title: "최근 맞대결",
        detail: "시즌 상대 3승 1패. 홈에서는 2승 0패.",
        icon: "h2h",
      },
      {
        id: "sk-7",
        title: "클러치 넷레이팅",
        detail: "종료 5분 이내 넷레이팅 +6.2. 접전 강세.",
        icon: "clutch",
      },
      {
        id: "sk-8",
        title: "로테이션 체력",
        detail: "벤치 득점 비중 32%. 주전 체력 관리가 원활.",
        icon: "rest",
      },
    ],
    risks: ["외곽 기복", "파울트러블"],
    expectedHomeScore: 82,
    expectedAwayScore: 76,
  },
  "nba-lakers-celtics": {
    gameId: "nba-lakers-celtics",
    league: "NBA",
    homeTeam: "레이커스",
    awayTeam: "셀틱스",
    startTime: "11:00",
    pickTeam: "레이커스",
    starRating: 3,
    winProbability: 55,
    confidence: 74,
    edgeScore: 7,
    grade: "B+",
    summary: "홈 코트 이점이 있으나 셀틱스 수비력이 변수가 됩니다.",
    reasons: [
      {
        id: "lal-1",
        title: "스테이플스 홈 이점",
        detail: "홈 넷레이팅 +4.8. 홈 관중 앞 후반 집중력이 좋음.",
        icon: "home",
      },
      {
        id: "lal-2",
        title: "공격 효율(ORtg)",
        detail: "최근 10경기 ORtg 118.2. 페인트·미드레인지 균형이 좋음.",
        icon: "offense",
      },
      {
        id: "lal-3",
        title: "리바운드 매치업",
        detail: "OREB% 28.5%. 공격 리바운드로 추가 기회를 만듦.",
        icon: "rebound",
      },
      {
        id: "lal-4",
        title: "전환 공격 속도",
        detail: "속공 득점 경기당 16.4점. 셀틱스 턴오버 후 이득 구간.",
        icon: "pace",
      },
      {
        id: "lal-5",
        title: "최근 홈 폼",
        detail: "홈 6경기 5승 1패. 평균 마진 +7.1.",
        icon: "form",
      },
      {
        id: "lal-6",
        title: "클러치 자유투",
        detail: "종료 3분 FTA가 많고 성공률 82%. 접전 시 유리.",
        icon: "clutch",
      },
      {
        id: "lal-7",
        title: "수비 스위치 대응",
        detail: "최근 경기 스위치 수비에서 실점 억제가 개선됨.",
        icon: "defense",
      },
    ],
    risks: ["셀틱스 수비", "3점 기복"],
    expectedHomeScore: 112,
    expectedAwayScore: 108,
  },
};

export function getAnalysisByGameId(gameId: string): AnalysisData | undefined {
  return ANALYSIS_BY_GAME_ID[gameId];
}
