import type { GameData, SportFilter } from "@/types/game";

export const DEFAULT_GAME_DATE = "2026-07-23";

export const SPORT_FILTERS: { id: SportFilter; label: string }[] = [
  { id: "all", label: "전체" },
  { id: "football", label: "축구" },
  { id: "baseball", label: "야구" },
  { id: "basketball", label: "농구" },
];

export const GAMES: GameData[] = [
  {
    id: "npb-softbank-orix",
    sport: "baseball",
    league: "NPB",
    homeTeam: "소프트뱅크",
    awayTeam: "오릭스",
    startTime: "18:00",
    date: DEFAULT_GAME_DATE,
    aiAnalysisAvailable: true,
  },
  {
    id: "npb-hanshin-yomiuri",
    sport: "baseball",
    league: "NPB",
    homeTeam: "한신",
    awayTeam: "요미우리",
    startTime: "18:00",
    date: DEFAULT_GAME_DATE,
    aiAnalysisAvailable: true,
  },
  {
    id: "npb-orix-hiroshima",
    sport: "baseball",
    league: "NPB",
    homeTeam: "오릭스",
    awayTeam: "히로시마",
    startTime: "18:00",
    date: DEFAULT_GAME_DATE,
    aiAnalysisAvailable: true,
  },
  {
    id: "kbo-lg-doosan",
    sport: "baseball",
    league: "KBO",
    homeTeam: "LG",
    awayTeam: "두산",
    startTime: "18:30",
    date: DEFAULT_GAME_DATE,
    aiAnalysisAvailable: true,
  },
  {
    id: "kbo-kia-ssg",
    sport: "baseball",
    league: "KBO",
    homeTeam: "KIA",
    awayTeam: "SSG",
    startTime: "18:30",
    date: DEFAULT_GAME_DATE,
    aiAnalysisAvailable: true,
  },
  {
    id: "kleague-ulsan-jeonbuk",
    sport: "football",
    league: "K리그",
    homeTeam: "울산",
    awayTeam: "전북",
    startTime: "19:00",
    date: DEFAULT_GAME_DATE,
    aiAnalysisAvailable: true,
  },
  {
    id: "epl-arsenal-liverpool",
    sport: "football",
    league: "EPL",
    homeTeam: "아스널",
    awayTeam: "리버풀",
    startTime: "23:30",
    date: DEFAULT_GAME_DATE,
    aiAnalysisAvailable: true,
  },
  {
    id: "laliga-real-barca",
    sport: "football",
    league: "라리가",
    homeTeam: "레알 마드리드",
    awayTeam: "바르셀로나",
    startTime: "04:00",
    date: DEFAULT_GAME_DATE,
    aiAnalysisAvailable: true,
  },
  {
    id: "kbl-seoul-anyang",
    sport: "basketball",
    league: "KBL",
    homeTeam: "서울 SK",
    awayTeam: "안양",
    startTime: "19:00",
    date: DEFAULT_GAME_DATE,
    aiAnalysisAvailable: true,
  },
  {
    id: "nba-lakers-celtics",
    sport: "basketball",
    league: "NBA",
    homeTeam: "레이커스",
    awayTeam: "셀틱스",
    startTime: "11:00",
    date: DEFAULT_GAME_DATE,
    aiAnalysisAvailable: true,
  },
];
