import type { BudgetOption, TotoRoundData } from "@/types/toto";

export const TOTO_BUDGET_OPTIONS: BudgetOption[] = [
  { id: "5k", label: "5천원", amount: 5000 },
  { id: "10k", label: "1만원", amount: 10000 },
  { id: "20k", label: "2만원", amount: 20000 },
];

export const TOTO_ROUND: TotoRoundData = {
  round: 41,
  deadlineLabel: "2일 13시간",
  matches: [
    {
      matchNumber: 1,
      homeTeam: "포항",
      awayTeam: "전북",
      aiPick: "패",
      confidence: 81,
      edgeValue: 12,
      betType: "단식",
    },
    {
      matchNumber: 2,
      homeTeam: "김천",
      awayTeam: "대전",
      aiPick: "무",
      confidence: 74,
      edgeValue: 8,
      betType: "복식",
      doublePicks: ["승", "무"],
    },
    {
      matchNumber: 3,
      homeTeam: "울산",
      awayTeam: "서울",
      aiPick: "승",
      confidence: 86,
      edgeValue: 15,
      betType: "단식",
    },
    {
      matchNumber: 4,
      homeTeam: "수원FC",
      awayTeam: "제주",
      aiPick: "승",
      confidence: 79,
      edgeValue: 11,
      betType: "단식",
    },
    {
      matchNumber: 5,
      homeTeam: "인천",
      awayTeam: "광주",
      aiPick: "무",
      confidence: 71,
      edgeValue: 7,
      betType: "복식",
      doublePicks: ["무", "패"],
    },
    {
      matchNumber: 6,
      homeTeam: "대구",
      awayTeam: "강원",
      aiPick: "패",
      confidence: 77,
      edgeValue: 10,
      betType: "단식",
    },
    {
      matchNumber: 7,
      homeTeam: "부산",
      awayTeam: "전남",
      aiPick: "승",
      confidence: 83,
      edgeValue: 13,
      betType: "단식",
    },
    {
      matchNumber: 8,
      homeTeam: "충북청주",
      awayTeam: "안양",
      aiPick: "패",
      confidence: 76,
      edgeValue: 9,
      betType: "복식",
      doublePicks: ["무", "패"],
    },
    {
      matchNumber: 9,
      homeTeam: "서울E",
      awayTeam: "성남",
      aiPick: "승",
      confidence: 80,
      edgeValue: 11,
      betType: "단식",
    },
    {
      matchNumber: 10,
      homeTeam: "김포",
      awayTeam: "천안",
      aiPick: "무",
      confidence: 69,
      edgeValue: 6,
      betType: "복식",
      doublePicks: ["승", "무"],
    },
    {
      matchNumber: 11,
      homeTeam: "수원삼성",
      awayTeam: "충남아산",
      aiPick: "승",
      confidence: 88,
      edgeValue: 16,
      betType: "단식",
    },
    {
      matchNumber: 12,
      homeTeam: "경남",
      awayTeam: "부천",
      aiPick: "패",
      confidence: 73,
      edgeValue: 8,
      betType: "단식",
    },
    {
      matchNumber: 13,
      homeTeam: "화성",
      awayTeam: "안산",
      aiPick: "승",
      confidence: 78,
      edgeValue: 10,
      betType: "복식",
      doublePicks: ["승", "무"],
    },
    {
      matchNumber: 14,
      homeTeam: "고양",
      awayTeam: "서울중랑",
      aiPick: "승",
      confidence: 82,
      edgeValue: 12,
      betType: "단식",
    },
  ],
};
