import type {RichPreview} from '@/lib/football/official-canonical-v1/rich-preview';
import {engineLabFor} from '@/lib/public-analysis/engine-lab';
import EngineLab from './EngineLab';

const roles:Record<string,string>={Goalkeeper:'골키퍼',Defender:'수비수',Midfielder:'미드필더',Attacker:'공격수'};
const record=(f:any)=>`${f.count}경기 · ${f.w}승 ${f.d}무 ${f.l}패 · ${f.gf}득점 ${f.ga}실점`;
export default function AtleticoRealShowcase({preview:p}:{preview:RichPreview}){
 const lab=engineLabFor(p);const split=p.seasonSplit!;const [h,a]=split.teams;
 const names=['Atlético Madrid','Real Madrid'];
 return <article data-showcase={p.targetId} className="min-w-0 space-y-6">
  <section className="rounded-2xl bg-zinc-900/80 p-5 sm:p-8">
   <div className="flex flex-wrap justify-between gap-2 text-xs text-zinc-400"><span>SHOWCASE · 2026-09-20 23:15 KST</span><span className="text-emerald-400">OFFICIAL BASELINE ENGINE = V1</span></div>
   <h1 className="mt-5 text-3xl font-semibold tracking-tight text-white sm:text-4xl">Atlético Madrid <span className="text-zinc-500">vs</span> Real Madrid</h1>
   <p className="mt-5 text-xs font-semibold tracking-[.16em] text-emerald-400">YANG EDGE VIEW</p>
   <p className="mt-2 text-base leading-7 text-zinc-300">모델의 첫 선택은 아틀레티코입니다. 다만 가장 높은 확률도 과반에 못 미쳐, 한쪽의 확실한 우세보다 세 결과의 가능성을 함께 볼 더비입니다.</p>
   <dl className="mt-6 grid grid-cols-3 gap-2 rounded-xl bg-zinc-950/80 p-4 sm:p-5">{([['Atlético',p.officialV1.pHome],['Draw',p.officialV1.pDraw],['Real Madrid',p.officialV1.pAway]]as const).map(([name,v])=><div key={name}><dt className="text-xs text-zinc-400">{name}</dt><dd className="mt-2 text-xl font-semibold tabular-nums text-white sm:text-3xl">{(v*100).toFixed(2)}%</dd><div className="mt-3 h-1 rounded bg-zinc-800"><div className="h-1 rounded bg-emerald-500/70" style={{width:`${v*100}%`}} /></div></div>)}</dl>
   <p className="mt-3 text-xs text-zinc-500">9월 13일에 봉인된 V1 판단 · 현재 기사 v{p.version} · LOCAL OWNER ONLY</p>
  </section>
  <section className="rounded-2xl bg-zinc-900/60 p-5 sm:p-7" aria-label="CURRENT SEASON"><p className="text-xs font-semibold tracking-wider text-zinc-500">CURRENT SEASON · 2026/27</p><h2 className="mt-2 text-xl font-semibold text-white">이번 시즌, 확인된 흐름</h2><p className="mt-2 text-xs text-zinc-500">경기별 폼은 9월 13일 관측 기준. 이전 시즌을 더해 경기 수를 채우지 않습니다.</p>
   <div className="mt-5 grid gap-6 sm:grid-cols-2">{split.teams.map((t:any,i:number)=><section key={t.teamId}><h3 className="font-semibold text-zinc-200">{names[i]}</h3><p className="mt-2 text-sm leading-6 text-zinc-300">{record(t.current.all.all)}</p><div className="mt-3 flex gap-1" aria-label="이번 시즌 최신 경기부터">{t.current.all.last5.rows.map((r:any)=><span key={r.fixtureId} className={`rounded px-2 py-1 text-xs ${r.result==='W'?'bg-emerald-950 text-emerald-300':r.result==='L'?'bg-rose-950 text-rose-300':'bg-zinc-800 text-zinc-300'}`}>{r.result}</span>)}</div><p className="mt-3 text-sm leading-6 text-zinc-400">{i===0?'홈':'원정'}: {record(i===0?t.current.home.all:t.current.away.all)}</p>{p.teams[i].seasonContext&&<p className="mt-3 text-xs leading-6 text-zinc-500">9월 20일 별도 순위 관측: {p.teams[i].seasonContext!.rank}위 · {p.teams[i].seasonContext!.played}경기 · {p.teams[i].seasonContext!.gf}득점 {p.teams[i].seasonContext!.ga}실점</p>}</section>)}</div>
  </section>
  <section className="rounded-2xl bg-zinc-900/60 p-5 sm:p-7"><p className="text-xs font-semibold tracking-wider text-zinc-500">MATCH FLOW</p><h2 className="mt-2 text-xl font-semibold text-white">홈에서의 버팀과 원정에서의 득점</h2><div className="mt-4 space-y-4 text-sm leading-7 text-zinc-300"><p>이번 시즌 관측 표본에서 아틀레티코는 홈 {h.current.home.all.count}경기 {h.current.home.all.w}승 {h.current.home.all.d}무로 패배가 없었습니다. 홈 {h.current.home.all.gf}득점과 {h.current.home.all.ga}실점은 홈팀 관점에서 볼 출발점입니다. 레알은 원정 {a.current.away.all.count}경기 {a.current.away.all.w}승 {a.current.away.all.l}패, {a.current.away.all.gf}득점 {a.current.away.all.ga}실점으로 서로 다른 결과를 기록했습니다.</p><p>관전 포인트는 아틀레티코가 홈에서 보여준 득실점 균형을 이어갈지, 레알이 원정에서 득점 기회를 얼마나 살릴지입니다. 이 표본만으로 점유율이나 압박 방식을 단정할 수는 없습니다. 아래 선수들의 실제 선발 포함 여부가 확인되면 출전 구성에 관한 설명을 보완합니다.</p><p>V1은 아틀레티코를 가장 높은 확률로 선택했지만 레알 승리도 {(p.officialV1.pAway*100).toFixed(2)}%, 무승부도 {(p.officialV1.pDraw*100).toFixed(2)}%로 남겨뒀습니다. 홈팀 최빈 판단과 경기의 불확실성을 함께 읽는 것이 현재의 결론입니다.</p></div></section>
  <section className="rounded-2xl bg-zinc-900/60 p-5 sm:p-7" aria-label="KEY PLAYERS"><p className="text-xs font-semibold tracking-wider text-zinc-500">KEY PLAYERS · PLAYER CONTEXT</p><h2 className="mt-2 text-xl font-semibold text-white">출전 기록으로 고른 주목할 선수</h2><div className="mt-5 grid gap-6 sm:grid-cols-2">{p.teams.map((t,i)=><section key={t.id}><h3 className="mb-4 font-semibold text-zinc-300">{names[i]}</h3><ul className="space-y-4">{t.keyPlayers.map(k=><li key={k.providerPlayerId} className="rounded-xl bg-zinc-950/60 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-semibold text-white">{k.name}</span><span className="text-xs text-zinc-500">{roles[k.position??'']??k.position??'포지션 미확인'}</span></div><p className="mt-2 text-sm leading-6 text-zinc-400">{k.reason}</p><p className="mt-2 text-sm leading-6 text-zinc-300">{k.position==='Goalkeeper'?'높은 출전시간과 선발 횟수로, 골문에서의 지속적인 기용을 확인할 수 있는 선수입니다.':(k.goals??0)+(k.assists??0)>0?'출전시간과 기록된 득점 관여를 함께 확인할 수 있어 주목할 선수로 선정했습니다.':'높은 출전시간으로 이번 시즌 꾸준한 기용을 확인할 수 있어 선정했습니다.'}</p><p className="mt-2 text-[10px] tracking-wide text-zinc-500">{p.confirmedKeyPlayerIds?.includes(k.providerPlayerId)?'CONFIRMED_STARTER':'LIKELY_RELEVANT · 선발 확정 아님'}</p></li>)}</ul></section>)}</div></section>
  <section className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-zinc-900/60 p-5"><h2 className="text-xs font-semibold tracking-wide text-zinc-400">PREVIOUS SEASON CONTEXT · 2025/26</h2>{split.teams.map((t:any,i:number)=><p key={t.teamId} className="mt-3 text-sm leading-6 text-zinc-300">{names[i]} {i===0?'홈':'원정'}: {record(i===0?t.previous.home.all:t.previous.away.all)}</p>)}<p className="mt-3 text-xs leading-6 text-zinc-500">모델 입력에 포함된 이전 시즌 부분 표본입니다. 이번 시즌 폼이나 평균에 합산하지 않습니다.</p></div><div className="rounded-2xl bg-zinc-900/60 p-5"><h2 className="text-xs font-semibold tracking-wide text-zinc-400">MODEL HISTORICAL WINDOW</h2><p className="mt-3 text-sm leading-6 text-zinc-300">V1은 봉인 당시의 과거 rolling window를 사용합니다. 아틀레티코 홈 20경기와 레알 원정 20경기는 각각 이번 시즌 2경기와 이전 시즌 18경기로 구성됩니다.</p><p className="mt-3 text-xs leading-6 text-zinc-500">시즌 표기를 정정해도 공식 모델의 입력과 확률은 바꾸지 않습니다.</p></div></section>
  <EngineLab preview={p} />
  <section className="rounded-2xl bg-zinc-900/60 p-5 sm:p-7" aria-label="DATA QUALITY / RESEARCH STATUS"><h2 className="text-xs font-semibold tracking-wide text-zinc-400">DATA QUALITY / RESEARCH STATUS</h2><div className="mt-4 space-y-2 text-sm leading-6 text-zinc-300"><p>{p.lineupStatus==='CONFIRMED'?'검증된 선발 명단 관측 확보':'공식 선발 명단 확인 전'} · LINEUP={p.lineupStatus}</p><p>확인된 부상/징계 데이터가 아직 완전하지 않음 · AVAILABILITY={p.availabilityStatus}</p><p>ODDS_MAPPING=PENDING · 배당 선택지 확인 전에는 시장과 모델의 방향 일치를 판단하지 않습니다.</p></div>{p.lineupStatus==='CONFIRMED'&&<p className="mt-4 text-sm leading-7 text-zinc-300">{p.sections.find(s=>s.title==='LINEUP / ABSENCES')?.text}</p>}<details className="mt-4"><summary className="cursor-pointer text-xs text-zinc-500">근거·연구 상태 상세</summary><div className="mt-3 space-y-2 break-all text-xs leading-6 text-zinc-500"><p>canonicalPredictionId: {p.canonicalPredictionId}</p><p>V2/H2: {lab.h2.status}</p><p>V3 / V3.1: {lab.v3.status}</p><p>연구 자료 확인: {lab.checkedAt}</p>{[...new Set(p.dataQuality)].map(s=><p key={s}>{s}</p>)}</div></details></section>
 </article>;
}
