'use client';
import {useState} from 'react';
import {queryResearch,researchHref,type ResearchLine} from '@/lib/public-analysis/research-explorer-contract';
export default function ResearchExplorer({lines,batch,date}:{lines:ResearchLine[];batch:string;date:string}){
 const [sport,setSport]=useState(''),[competition,setCompetition]=useState(''),[tier,setTier]=useState(''),[sort,setSort]=useState('kickoff');const visible=queryResearch(lines,{sport,competition,tier,sort});
 const options=(key:'sport'|'competition'|'tier')=>[...new Set(lines.map(l=>l[key]))].sort();
 const control='min-w-0 rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm text-zinc-200';
 return <section aria-label="Research Explorer" className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><h2 className="text-2xl font-semibold text-white">Research Explorer</h2><p className="mt-2 text-sm text-zinc-400">연구가 먼저입니다. PASS와 확률 미확보 경기도 표시합니다. 모델 확률순은 Pick 순위가 아닙니다.</p><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><select aria-label="SPORT" className={control} value={sport} onChange={e=>setSport(e.target.value)}><option value="">전체 종목</option>{options('sport').map(v=><option key={v}>{v}</option>)}</select><select aria-label="COMPETITION" className={control} value={competition} onChange={e=>setCompetition(e.target.value)}><option value="">전체 대회</option>{options('competition').map(v=><option key={v}>{v}</option>)}</select><select aria-label="RESEARCH_TIER" className={control} value={tier} onChange={e=>setTier(e.target.value)}><option value="">전체 연구 단계</option>{options('tier').map(v=><option key={v}>{v}</option>)}</select><select aria-label="SORT" className={control} value={sort} onChange={e=>setSort(e.target.value)}><option value="kickoff">경기시간순</option><option value="home">모델 확률순 · HOME</option><option value="draw">모델 확률순 · DRAW</option><option value="away">모델 확률순 · AWAY</option></select></div><p className="my-4 text-sm text-zinc-500" role="status">표시 {visible.length} / 전체 {lines.length}경기</p><div className="grid gap-3 lg:grid-cols-2">{visible.map(l=><article key={l.targetId} data-research-line={l.targetId} className="min-w-0 rounded-xl bg-zinc-900/70 p-5"><div className="flex flex-wrap justify-between gap-2 text-xs text-zinc-400"><span>{l.sport} · {l.competition}</span><span>{l.tier}</span></div><a className="mt-3 block text-lg font-semibold text-white hover:text-emerald-400" href={researchHref(l.targetId,batch,date)}>{l.home} <span className="text-zinc-500">vs</span> {l.away}</a><p className="mt-2 text-sm text-zinc-400">{l.kickoff.slice(0,10)} {l.kickoff.slice(11,16)} KST</p><div className="mt-3 space-y-2 text-xs leading-6 text-zinc-400">{l.currentForm?.map(s=><p key={s}>Current season · {s}</p>)}{l.recentForm?.map(s=><p key={s}>Recent form · {s}</p>)}{l.summary&&<p>{l.summary}</p>}</div><p className="mt-3 text-xs text-zinc-500">{l.probability?'V1 모델 분석 제공':'모델 확률 준비 전'}</p><p className="mt-2 text-sm tabular-nums text-emerald-300">YANG EDGE Model Probability<br/>{l.probability?`HOME ${(l.probability.home*100).toFixed(2)}% · DRAW ${(l.probability.draw*100).toFixed(2)}% · AWAY ${(l.probability.away*100).toFixed(2)}%`:'모델 확률 준비 전'}</p><p className="mt-3 text-xs text-zinc-400">LINEUP · {l.lineupStatus}</p><details className="mt-3 text-xs leading-6 text-zinc-500"><summary className="cursor-pointer">분석 상세 · {l.dataMissing.length}개 미확보 항목</summary><p>MODEL_STATUS · {l.modelStatus}</p>{l.quality.map(q=><p key={q}>{q}</p>)}</details></article>)}</div>{!visible.length&&<p className="rounded-xl bg-zinc-900 p-6 text-zinc-400">이 필터에 맞는 경기가 없습니다. 전체 {lines.length}경기는 보존되어 있습니다.</p>}</section>;
}
