import type {ResearchDetail} from '@/lib/public-analysis/load-research-explorer';
const stat=(s:any)=>s?`${s.count}경기 · ${s.w}승 ${s.d}무 ${s.l}패 · ${s.gf}득점 ${s.ga}실점`:'NOT_AVAILABLE';
const kst=(v:string|null)=>v?new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',dateStyle:'short',timeStyle:'short'}).format(new Date(v))+' KST':'NOT_AVAILABLE';
function Block({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-xl bg-zinc-900/70 p-5 sm:p-6"><h2 className="text-xs font-semibold tracking-wide text-zinc-400">{title}</h2><div className="mt-4 space-y-3 text-sm leading-7 text-zinc-300">{children}</div></section>;}
export function CommonEngineLab(){return <Block title="YANG EDGE ENGINE LAB"><p>V1 · OFFICIAL BASELINE — 과거 득실점·홈/원정 기반</p><p>V2/H2 · RESEARCH UNPROMOTED — 현재 경기 확률 NOT_AVAILABLE</p><p>V3/V3.1 · RESEARCH CLOSED UNPROMOTED — xG / Shots / SOT 연구, 승격되지 않음. 현재 경기 확률 NOT_AVAILABLE</p><p>V4 · PLAYER / LINEUP / AVAILABILITY · IN DEVELOPMENT — 근거 수집 기반 준비. 공식 Prediction NOT IMPLEMENTED</p></Block>;}
export default function UniversalResearch({detail:d}:{detail:ResearchDetail}){
 const l=d.line,p=d.preview,football=l.sport==='SOCCER',teams=p?.recency?.teams??p?.seasonSplit?.teams;
 return <article data-universal-target={l.targetId} className="mx-auto max-w-4xl space-y-5 px-4 py-8 sm:px-6"><header className="rounded-2xl bg-zinc-900 p-6"><p className="text-xs text-emerald-400">{l.sport} · {l.competition} · {l.tier} RESEARCH</p><h1 className="mt-3 text-3xl font-semibold text-white">{p?.teams[0].name??l.home} <span className="text-zinc-500">vs</span> {p?.teams[1].name??l.away}</h1><p className="mt-3 text-sm text-zinc-400">{kst(l.kickoff)}</p><p className="mt-3 text-xs text-zinc-500">MODEL_STATUS={l.modelStatus} · 연구 라인은 Prediction/Pick과 별개입니다.</p></header>
 <Block title="YANG EDGE Model Probability"><p className="text-xl tabular-nums text-emerald-300">{l.probability?`HOME ${(l.probability.home*100).toFixed(2)}% / DRAW ${(l.probability.draw*100).toFixed(2)}% / AWAY ${(l.probability.away*100).toFixed(2)}%`:'NOT_AVAILABLE'}</p><p>ENGINE_AS_OF · {kst(l.engineAsOf)}<br/>PREVIEW_AS_OF · {kst(l.previewAsOf)}</p>{p&&<p>V1 확률은 봉인된 사전 Snapshot을 유지합니다. 아래 Preview Context는 별도로 관측한 정보이며 모델 재계산을 의미하지 않습니다.</p>}</Block>
 {football?<><Block title="CURRENT SEASON">{teams?teams.map((t:any)=><p key={t.teamId}>{t.name} · {stat(t.current.all.all)}</p>):<p>NOT_AVAILABLE · 검증된 현재 시즌 자료가 아직 연결되지 않았습니다.</p>}</Block><Block title="RECENT FORM">{teams?teams.map((t:any)=><p key={t.teamId}>{t.name}<br/>최근 5: {stat(t.current.all.last5)}<br/>최근 10: {stat(t.current.all.last10)}</p>):<p>NOT_AVAILABLE</p>}<p>이번 시즌에 확보된 경기만 사용합니다. 이전 시즌을 더해 표본 수를 채우지 않습니다.</p></Block><Block title="HOME / AWAY">{teams?teams.map((t:any,i:number)=><p key={t.teamId}>{t.name} · {i===0?'홈':'원정'} {stat(i===0?t.current.home.all:t.current.away.all)}</p>):<p>NOT_AVAILABLE</p>}</Block>
 <Block title="PLAYER CONTEXT / SEASON CORE / STRUCTURAL CONTEXT">{d.players.length?d.players.map(t=><div key={t.teamId} className="border-t border-zinc-800 pt-3"><h3 className="font-semibold text-white">{t.name}</h3><p className="text-xs text-zinc-500">ROLE_DETAIL=UNKNOWN (GK는 Provider 역할 확인) · 관측 {kst(t.observedAt??null)}</p>{t.roles?([['SEASON CORE','seasonCore'],['STRUCTURAL CONTEXT','structuralKey']].map(([label,key])=><div key={key}><h4 className="mt-3 text-xs text-emerald-400">{label}</h4>{t.roles[key].length?t.roles[key].map((q:any)=><p key={q.id}>{q.name} · {q.position} · {q.minutes}분 / 선발 {q.starts}회<br/>{q.position==='Goalkeeper'?`선방 ${q.axes.SHOT_STOPPING??'미확보'}`:`득점 ${q.goals??'미확보'} · 도움 ${q.assists??'미확보'} · 슈팅 ${q.axes.SHOTS??'미확보'} · 키패스 ${q.axes.KEY_PASSES??'미확보'}`}{key==='structuralKey'&&q.position!=='Goalkeeper'?` · 태클 ${q.axes.DEFENSIVE_IMPACT??'미확보'} / 가로채기 ${q.axes.INTERCEPTIONS??'미확보'}`:''}</p>):<p>NOT ENOUGH VERIFIED EVIDENCE</p>}</div>)):<p>NOT_AVAILABLE</p>}</div>):<p>NOT_AVAILABLE</p>}<p className="text-xs text-zinc-500">골·도움을 배제하지도, 그것만으로 선정하지도 않습니다. 공격수 태클 및 총 패스 수만으로 Structural Key를 선정하지 않습니다. 상세 역할은 추정하지 않습니다.</p></Block>
 <Block title="RECENT IMPACT"><p>NOT ENOUGH VERIFIED EVIDENCE · 시즌 누계를 최근 1~3경기 활약으로 대체하지 않습니다.</p></Block><Block title="MATCH KEY PLAYER"><p>{l.lineupStatus==='CONFIRMED'?'NOT_ENOUGH_VERIFIED_MATCHUP_EVIDENCE':'WAITING_FOR_XI'}</p></Block><Block title="LINEUP / AVAILABILITY"><p>LINEUP={l.lineupStatus}<br/>AVAILABILITY={l.availabilityStatus}</p></Block><Block title="MATCH FLOW"><p>{p?.expectedFlow??'NOT_AVAILABLE · 검증된 경기 흐름 근거를 확보하기 전에는 전술·우세를 추측하지 않습니다.'}</p></Block>
 {p?.seasonSplit&&<Block title="PREVIOUS SEASON CONTEXT / MODEL HISTORICAL WINDOW">{p.seasonSplit.teams.map((t:any)=><p key={t.teamId}>{t.name} · 이전 시즌 {stat(t.previous.all.all)}<br/>봉인된 전체 관련 모델 표본 {t.modelWindow.all.all.count}경기</p>)}<p>이전 시즌 부분 표본과 모델 rolling window는 현재 시즌 폼에 합산하지 않습니다.</p></Block>}<CommonEngineLab/></>:<Block title="SPORT RESEARCH STATUS"><p>ENGINE_STATUS=NOT_AVAILABLE_FOR_THIS_TARGET</p><p>DATA_AVAILABLE={l.dataAvailable.join(', ')}</p><p>DATA_MISSING={l.dataMissing.join(', ')}</p><p>해당 종목의 검증된 선수·라인업·확률을 확보하지 못했습니다. 공식 경기 편성은 유지합니다.</p></Block>}
 <Block title="OBSERVED MARKET">{l.observedMarkets?.length?<div>{l.observedMarkets.map(m=><p key={m.number}>#{m.number} · {m.type} {m.line??''}<br/>좌 {m.left??'NOT_AVAILABLE'} / 중 {m.middle??'NOT_AVAILABLE'} / 우 {m.right??'NOT_AVAILABLE'}<br/><span className="text-xs text-zinc-500">선택지 매핑 미확정 · 화면 좌/중/우 보존 · 모델 입력 아님</span></p>)}</div>:l.market?<p>좌 {l.market.left??'NOT_AVAILABLE'} / 중 {l.market.middle??'NOT_AVAILABLE'} / 우 {l.market.right??'NOT_AVAILABLE'}<br/>선택지 매핑={l.market.mapping} · 모델 입력 아님</p>:<p>NOT_AVAILABLE · 빈 배당을 0으로 바꾸지 않습니다.</p>}</Block><Block title="DATA QUALITY"><p>확보: {l.dataAvailable.join(', ')}</p>{l.quality.map(q=><p key={q}>{q}</p>)}</Block><Block title="OFFICIAL PICK"><p>공식 선택 의견: 없음</p><p>Pick이 없어도 경기 연구는 제공됩니다. 모델 확률의 유무는 위 별도 상태를 확인하세요.</p></Block><p className="text-xs leading-6 text-zinc-500">YANG EDGE는 스포츠 데이터와 모델을 기반으로 연구·분석 정보를 제공합니다. 표시된 확률은 모델 추정치이며 실제 경기 결과를 보장하지 않습니다. 최종 판단은 이용자에게 있습니다. LOCAL OWNER ONLY</p></article>;
}
