import {readFileSync} from 'node:fs';
import {readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {join} from 'node:path';
import {isResearchTargetScopeLockDocument,operatorBetmanDailySlateRel,researchSlateSourceFreezeRel,researchTargetScopeLockRel} from '../../research/daily-scope-lock/paths';
import {isResearchSlateSourceFreezeDocument} from '../../research/slate-source-freeze';
import {Context,Envelope,SourceType,evidenceId,id,requireProof,sha,stable,temporal,time} from './contracts';
import {Registry} from './registry';
import {get,put,exactEvidence} from './store';
import {validateXI,validateInjuries,XI,Injury} from './validate';
export type Bridge=Context&{verified:true;homeTeamRaw:string;awayTeamRaw:string;sourceEvidenceSha256:string};
export function loadScope(root:string,date:string){requireProof(/^\d{4}-\d{2}-\d{2}$/.test(date),'DATE_REQUIRED');const read=(p:string)=>{const bytes=readFileSync(join(root,p));const committed=execFileSync('git',['-c','safe.directory='+root.replaceAll('\\','/'),'show','HEAD:'+p],{cwd:root});requireProof(bytes.toString().replaceAll('\r\n','\n')===committed.toString().replaceAll('\r\n','\n'),'UNCOMMITTED_SCOPE');return{bytes,doc:JSON.parse(bytes.toString())};};
 const lock=read(researchTargetScopeLockRel(date)),source=read(researchSlateSourceFreezeRel(date)),operator=read(operatorBetmanDailySlateRel(date));
 requireProof(isResearchTargetScopeLockDocument(lock.doc)&&isResearchSlateSourceFreezeDocument(source.doc),'SCOPE_SCHEMA');requireProof(lock.doc.dateKst===date&&source.doc.dateKst===date&&lock.doc.lockStatus==='LOCKED','SCOPE_DATE');requireProof(lock.doc.source.sha256===sha(source.bytes)&&source.doc.source.sha256===sha(operator.bytes),'SCOPE_HASH_CHAIN');
 requireProof(operator.doc.reviewStatus==='VERIFIED'&&operator.doc.scopeCompletenessStatus==='COMPLETE'&&id(operator.doc.reviewedAt),'HUMAN_GATE');requireProof(Array.isArray(operator.doc.games)&&operator.doc.games.every((g:any)=>g.reviewStatus==='VERIFIED'&&g.operatorHomeAwayStatus==='VERIFIED'),'GAME_HUMAN_GATE');
 requireProof(lock.doc.targetCount===lock.doc.targets.length&&new Set(lock.doc.targets.map(t=>t.targetId)).size===lock.doc.targetCount,'DENOMINATOR');
 return{scopeHash:sha(lock.bytes),targets:lock.doc.targets};
}
export type Scope=ReturnType<typeof loadScope>;
export function bind(scope:Scope,b:Bridge,now:string){const t=scope.targets.find(t=>t.targetId===b.targetId);requireProof(t&&t.sport.toUpperCase()==='SOCCER','TARGET_NOT_LOCKED');requireProof(b.verified&&b.scopeIdentity===scope.scopeHash&&/^[a-f0-9]{64}$/.test(b.sourceEvidenceSha256),'BRIDGE_PROOF');requireProof(t.homeTeamRaw===b.homeTeamRaw&&t.awayTeamRaw===b.awayTeamRaw&&time(t.scheduledStartTimeKst!)===time(b.scheduledStart),'EXACT_BRIDGE');requireProof(!t.providerFixtureId||t.providerFixtureId===b.providerFixtureId,'FIXTURE_BRIDGE');requireProof([b.providerFixtureId,b.homeTeamId,b.awayTeamId,b.competitionProviderId,b.season].every(id)&&b.homeTeamId!==b.awayTeamId,'BRIDGE_IDS');requireProof(['39','140','135','78'].includes(b.competitionProviderId),'LEAGUE_SCOPE');requireProof(time(now)<time(b.predictionCutoff)&&time(b.predictionCutoff)<=time(b.scheduledStart)-60000,'FUTURE_CUTOFF');return b;}
export const POLL_MINUTES=[60,40,30,20] as const;
export function pollPlan(c:Context){return POLL_MINUTES.map(m=>new Date(time(c.scheduledStart)-m*60000).toISOString()).filter(t=>time(t)<time(c.predictionCutoff));}
export type Receipt={raw:unknown[];observedAt:string;collectedAt:string;asOf:string;providerUpdatedAt:string|null;paging?:{current:number;total:number}|null};
export type FetchSource=(s:SourceType,c:Context,team:string,page:number)=>Promise<Receipt>;
/** Capability accepts a previously verified scope. Real runner must use loadScope.
 * Network is only invoked here after scope, rights and durable budget reservation. */
export async function collect(input:{scope:Scope;bridge:Bridge;registry:Registry;root:string;source:SourceType;teamId:string;page?:number;pollAt:string;now:()=>string;fetchSource:FetchSource;rightsEvidenceHash:string;requestBudget:number}){
 const c=bind(input.scope,input.bridge,input.now());requireProof(/^[a-f0-9]{64}$/.test(input.rightsEvidenceHash),'RIGHTS_RECEIPT_REQUIRED');requireProof(input.requestBudget>0&&input.requestBudget<=16,'BUDGET_MAX_16');requireProof([c.homeTeamId,c.awayTeamId].includes(input.teamId),'TEAM_SCOPE');requireProof(pollPlan(c).some(t=>time(t)===time(input.pollAt)),'UNPLANNED_POLL');requireProof(time(input.now())>=time(input.pollAt)&&time(input.now())<time(input.pollAt)+60000,'POLL_WINDOW_MISSED');
 const page=input.page??1;requireProof(Number.isInteger(page)&&page>=1&&page<=100&&(input.source==='PLAYER_STATS'||page===1),'INVALID_PAGE');const baseEvent=evidenceId(c,input.source,input.teamId,input.pollAt);const event=input.source==='PLAYER_STATS'?sha(baseEvent+':page:'+page):baseEvent,receiptId=sha('receipt:'+event),claims=join(input.root,'claims'),store=join(input.root,'pregame');
 const claim=await put(claims,event,Buffer.from(stable({event,context:c,registryHash:sha(stable(input.registry)),rights:input.rightsEvidenceHash})));requireProof(claim.status!=='CONFLICT','JOB_IDENTITY_CONFLICT');if(claim.status!=='CREATED'){try{const saved=JSON.parse(await readFile(join(input.root,'receipts',receiptId+'.json'),'utf8'));if(saved.status==='SEALED')await exactEvidence(store,event,saved.sha256);}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}return{status:'ALREADY_CLAIMED_NO_REFETCH',evidenceId:event};}
 // Persistent daily reservations survive crashes/restarts. Never refund uncertain requests.
 const day=input.now().slice(0,10);let reserved=false;for(let n=0;n<input.requestBudget;n++){const v=await put(join(input.root,'budget'),sha(day+':'+n),Buffer.from(stable({event})));if(v.status==='CREATED'){reserved=true;break;}}requireProof(reserved,'REQUEST_BUDGET_EXHAUSTED');
 let r:Receipt;try{r=await input.fetchSource(input.source,c,input.teamId,page);}catch{await put(join(input.root,'receipts'),receiptId,Buffer.from(stable({event,status:'FETCH_FAILED_NO_AUTOMATIC_RETRY'})));return{status:'FETCH_FAILED',evidenceId:event};}
 const clocks={observedAt:r.observedAt,collectedAt:r.collectedAt,asOf:r.asOf,predictionCutoff:c.predictionCutoff,scheduledStart:c.scheduledStart};if(!temporal(clocks)||time(r.collectedAt)>time(input.now())){await put(join(input.root,'quarantine'),event,Buffer.from(stable({event,clocks,raw:r.raw,role:'NOT_PREGAME',status:'TEMPORAL_UNVERIFIED'})));await put(join(input.root,'receipts'),receiptId,Buffer.from(stable({event,status:'TEMPORAL_REJECTED'})));return{status:'TEMPORAL_REJECTED',evidenceId:event};}
 let validation:unknown,status='UNRESOLVED';
 if(input.source==='XI'){const x:XI={fixtureId:c.providerFixtureId,teams:r.raw.map((t:any)=>({teamId:String(t.team?.id??''),side:String(t.team?.id)===c.homeTeamId?'HOME':'AWAY',starters:(t.startXI??[]).map((p:any)=>({playerId:String(p.player?.id??''),teamId:String(t.team?.id??''),position:p.player?.pos})),substitutes:(t.substitutes??[]).map((p:any)=>({playerId:String(p.player?.id??''),teamId:String(t.team?.id??'')}))}))};validation=validateXI(x,c,input.registry);status=(validation as {status:string}).status;}
 else if(input.source==='INJURY'){const rows:Injury[]=r.raw.map((x:any)=>({fixtureId:String(x.fixture?.id??''),teamId:String(x.team?.id??''),playerId:String(x.player?.id??''),type:x.player?.type??'',reason:x.player?.reason??''}));validation=validateInjuries(rows,c,input.registry);status=(validation as {status:string}).status;}
 else {validation={status:'UNRESOLVED',reason:'CUMULATIVE_STATS_DATA_THROUGH_AND_REGISTRY_REVIEW_REQUIRED'};}
 const sourceArtifactSha256=sha(stable(r.raw));const envelope:Envelope={schemaVersion:'football-v4-prospective-evidence-v1',evidenceId:event,targetId:c.targetId,scopeIdentity:c.scopeIdentity,providerName:'api-football',providerFixtureId:c.providerFixtureId,competitionProviderId:c.competitionProviderId,teamProviderId:input.teamId,sourceType:input.source,...clocks,providerUpdatedAt:r.providerUpdatedAt,sourceArtifactSha256,collectorVersion:'football-v4-prospective-evidence-v1',identityStatus:status==='VALID'?'EXACT':'UNRESOLVED',temporalStatus:'SAFE',validationStatus:status,featureAdmitted:false,payload:{raw:r.raw,validation,rightsEvidenceHash:input.rightsEvidenceHash,registryHash:sha(stable(input.registry)),season:c.season,paging:r.paging??null}};
 const saved=await put(store,event,Buffer.from(stable(envelope)));requireProof(saved.status!=='CONFLICT','EVIDENCE_CONFLICT');await get(store,event,saved.sha256);
 await put(join(input.root,'receipts'),receiptId,Buffer.from(stable({event,status:'SEALED',sha256:saved.sha256})));
 const playerCount=input.source==='XI'?r.raw.reduce((n:number,t:any)=>n+(t.startXI?.length??0),0):null;
 await put(join(input.root,'availability'),event,Buffer.from(stable({targetId:c.targetId,competition:c.competitionProviderId,scheduledStart:c.scheduledStart,pollTime:r.collectedAt,responseEmpty:r.raw.length===0,xiValid:input.source==='XI'&&status==='VALID',playerCount,evidenceId:event,sha256:saved.sha256,source:input.source})));
 return{status:'SEALED',evidenceId:event,sha256:saved.sha256};
}
export function coverage(scope:Scope,bindings:Bridge[],evidence:Envelope[],source:SourceType){return ['39','140','135','78','UNRESOLVED_LEAGUE'].map(league=>{const targets=scope.targets.filter(t=>t.sport.toUpperCase()==='SOCCER').filter(t=>(bindings.find(b=>b.targetId===t.targetId)?.competitionProviderId??'UNRESOLVED_LEAGUE')===league);const counts={targets:targets.length,validEvidence:0,notAvailableYet:0,invalid:0,unresolved:0};for(const t of targets){const rows=evidence.filter(e=>e.targetId===t.targetId&&e.scopeIdentity===scope.scopeHash&&e.sourceType===source);if(rows.some(e=>e.validationStatus==='VALID'&&e.temporalStatus==='SAFE'&&e.identityStatus==='EXACT'))counts.validEvidence++;else if(rows.some(e=>['INVALID','CONFLICT'].includes(e.validationStatus)))counts.invalid++;else if(rows.some(e=>e.validationStatus==='INCOMPLETE'))counts.notAvailableYet++;else counts.unresolved++;}return{league,source,...counts,coverage:counts.targets?counts.validEvidence/counts.targets:null};});}
/** Storage-facing API: caller supplies an explicit manifest, never a latest lookup. */
export async function coverageFromRefs(root:string,scope:Scope,bindings:Bridge[],refs:{evidenceId:string;sha256:string}[],source:SourceType){const evidence=await Promise.all(refs.map(r=>exactEvidence(root,r.evidenceId,r.sha256)));for(const e of evidence){requireProof(e.scopeIdentity===scope.scopeHash&&scope.targets.some(t=>t.targetId===e.targetId),'FOREIGN_EVIDENCE');requireProof(temporal(e),'UNSAFE_EVIDENCE');}for(const b of bindings){const t=scope.targets.find(t=>t.targetId===b.targetId);requireProof(t&&b.verified&&b.scopeIdentity===scope.scopeHash&&t.homeTeamRaw===b.homeTeamRaw&&t.awayTeamRaw===b.awayTeamRaw&&time(t.scheduledStartTimeKst!)===time(b.scheduledStart),'COVERAGE_BRIDGE');}return coverage(scope,bindings,evidence,source);}
