import {loadCommittedProductionScope} from '../../research/terminal-decision/production-authority';
import {readFileSync} from 'node:fs';
import {readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {join} from 'node:path';
import {isResearchTargetScopeLockDocument,operatorBetmanDailySlateRel,researchSlateSourceFreezeRel,researchTargetScopeLockRel} from '../../research/daily-scope-lock/paths';
import {isResearchSlateSourceFreezeDocument} from '../../research/slate-source-freeze';
import {Context,Envelope,SourceType,evidenceId,id,requireProof,sha,stable,temporal,time} from './contracts';
import {Registry} from './registry';
import {get,put,exactEvidence} from './store';
import {validateXI,validateInjuries} from './validate';
import {PREGAME_SCHEMA,projectPregame,assertSafePregame,safeTimestamp,safePaging,serializePregame} from './projection';
export type Bridge=Context&{verified:true;homeTeamRaw:string;awayTeamRaw:string;sourceEvidenceSha256:string};
export function loadScope(root:string,date:string){ const scope=loadCommittedProductionScope(root,date);return {scopeHash:scope.hash,targets:scope.doc.targets}; }
export type Scope=ReturnType<typeof loadScope>;
export function bind(scope:Scope,b:Bridge,now:string){const t=scope.targets.find(t=>t.targetId===b.targetId);requireProof(t&&t.sport.toUpperCase()==='SOCCER','TARGET_NOT_LOCKED');requireProof(b.verified&&b.scopeIdentity===scope.scopeHash&&/^[a-f0-9]{64}$/.test(b.sourceEvidenceSha256),'BRIDGE_PROOF');requireProof(t.homeTeamRaw===b.homeTeamRaw&&t.awayTeamRaw===b.awayTeamRaw&&time(t.scheduledStartTimeKst!)===time(b.scheduledStart),'EXACT_BRIDGE');requireProof(!t.providerFixtureId||t.providerFixtureId===b.providerFixtureId,'FIXTURE_BRIDGE');requireProof([b.providerFixtureId,b.homeTeamId,b.awayTeamId,b.competitionProviderId,b.season].every(id)&&b.homeTeamId!==b.awayTeamId,'BRIDGE_IDS');requireProof(['39','140','135','78'].includes(b.competitionProviderId),'LEAGUE_SCOPE');requireProof(time(now)<time(b.predictionCutoff)&&time(b.predictionCutoff)<=time(b.scheduledStart)-60000,'FUTURE_CUTOFF');return b;}
export const POLL_MINUTES=[60,40,30,20] as const;
export function pollPlan(c:Context){return POLL_MINUTES.map(m=>new Date(time(c.scheduledStart)-m*60000).toISOString()).filter(t=>time(t)<time(c.predictionCutoff));}
export type Receipt={raw:unknown[];observedAt:string;collectedAt:string;asOf:string;providerUpdatedAt:string|null;paging?:{current:number;total:number}|null};
export type FetchSource=(s:SourceType,c:Context,team:string,page:number)=>Promise<Receipt>;
/** Capability accepts a previously verified scope. Real runner must use loadScope.
 * Network is only invoked here after scope, rights and durable budget reservation. */
export async function collect(input:{scope:Scope;bridge:Bridge;registry:Registry;root:string;source:SourceType;teamId:string;page?:number;pollAt:string;now:()=>string;fetchSource:FetchSource;rightsEvidenceHash:string;requestBudget:number}){
 requireProof(['XI','INJURY','PLAYER_STATS'].includes(input.source),'SOURCE_NOT_ALLOWED');
 const c=bind(input.scope,input.bridge,input.now());requireProof(/^[a-f0-9]{64}$/.test(input.rightsEvidenceHash),'RIGHTS_RECEIPT_REQUIRED');requireProof(input.requestBudget>0&&input.requestBudget<=16,'BUDGET_MAX_16');requireProof([c.homeTeamId,c.awayTeamId].includes(input.teamId),'TEAM_SCOPE');requireProof(pollPlan(c).some(t=>time(t)===time(input.pollAt)),'UNPLANNED_POLL');requireProof(time(input.now())>=time(input.pollAt)&&time(input.now())<time(input.pollAt)+60000,'POLL_WINDOW_MISSED');
 const page=input.page??1;requireProof(Number.isInteger(page)&&page>=1&&page<=100&&(input.source==='PLAYER_STATS'||page===1),'INVALID_PAGE');const baseEvent=evidenceId(c,input.source,input.teamId,input.pollAt);const event=input.source==='PLAYER_STATS'?sha(baseEvent+':page:'+page):baseEvent,receiptId=sha('receipt:'+event),claims=join(input.root,'claims'),store=join(input.root,'pregame');
 const claim=await put(claims,event,Buffer.from(stable({event,context:c,registryHash:sha(stable(input.registry)),rights:input.rightsEvidenceHash})));requireProof(claim.status!=='CONFLICT','JOB_IDENTITY_CONFLICT');if(claim.status!=='CREATED'){try{const saved=JSON.parse(await readFile(join(input.root,'receipts',receiptId+'.json'),'utf8'));if(saved.status==='SEALED')await exactEvidence(store,event,saved.sha256);}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}return{status:'ALREADY_CLAIMED_NO_REFETCH',evidenceId:event};}
 // Persistent daily reservations survive crashes/restarts. Never refund uncertain requests.
 const day=input.now().slice(0,10);let reserved=false;for(let n=0;n<input.requestBudget;n++){const v=await put(join(input.root,'budget'),sha(day+':'+n),Buffer.from(stable({event})));if(v.status==='CREATED'){reserved=true;break;}}requireProof(reserved,'REQUEST_BUDGET_EXHAUSTED');
 let r:Receipt;try{r=await input.fetchSource(input.source,c,input.teamId,page);}catch{await put(join(input.root,'receipts'),receiptId,Buffer.from(stable({event,status:'FETCH_FAILED_NO_AUTOMATIC_RETRY'})));return{status:'FETCH_FAILED',evidenceId:event};}
 const pregame=projectPregame(input.source,r.raw,c);assertSafePregame(pregame);
 const clocks={observedAt:safeTimestamp(r.observedAt),collectedAt:safeTimestamp(r.collectedAt),asOf:safeTimestamp(r.asOf),predictionCutoff:safeTimestamp(c.predictionCutoff),scheduledStart:safeTimestamp(c.scheduledStart)};
 if(!clocks.observedAt||!clocks.collectedAt||!clocks.asOf||!clocks.predictionCutoff||!clocks.scheduledStart||!temporal(clocks as import('./contracts').Clocks)||time(clocks.collectedAt)>time(input.now())){
  await put(join(input.root,'quarantine'),event,Buffer.from(stable({event,clocks,pregame,role:'NOT_PREGAME',status:'TEMPORAL_UNVERIFIED'})));
  await put(join(input.root,'receipts'),receiptId,Buffer.from(stable({event,status:'TEMPORAL_REJECTED'})));return{status:'TEMPORAL_REJECTED',evidenceId:event};
 }
 // The validator receives the exact projected object (or its stored rows), never a broader response.
 const validation=pregame.sourceType==='XI'?validateXI(pregame,c,input.registry):pregame.sourceType==='INJURY'?validateInjuries(pregame.rows,c,input.registry):{status:'UNRESOLVED',reason:'CUMULATIVE_STATS_DATA_THROUGH_AND_REGISTRY_REVIEW_REQUIRED'};
 const status=validation.status,sourceArtifactSha256=sha(stable(pregame));
 const envelope:Envelope={schemaVersion:PREGAME_SCHEMA,evidenceId:event,targetId:c.targetId,scopeIdentity:c.scopeIdentity,providerName:'api-football',providerFixtureId:c.providerFixtureId,competitionProviderId:c.competitionProviderId,teamProviderId:input.teamId,sourceType:input.source,...clocks as import('./contracts').Clocks,providerUpdatedAt:safeTimestamp(r.providerUpdatedAt),sourceArtifactSha256,collectorVersion:'football-v4-pregame-isolation-v2',identityStatus:(status==='VALID'||status==='CONFIRMED_COMPLETE')?'EXACT':'UNRESOLVED',temporalStatus:'SAFE',validationStatus:status,featureAdmitted:false,payload:{pregame,validation,rightsEvidenceHash:input.rightsEvidenceHash,registryHash:sha(stable(input.registry)),season:c.season,paging:safePaging(r.paging)}};
 const saved=await put(store,event,serializePregame(envelope));requireProof(saved.status!=='CONFLICT','EVIDENCE_CONFLICT');await get(store,event,saved.sha256);
 await put(join(input.root,'receipts'),receiptId,Buffer.from(stable({event,status:'SEALED',sha256:saved.sha256})));
 const playerCount=pregame.sourceType==='XI'?pregame.teams.reduce((n,t)=>n+t.starters.length,0):null;
 await put(join(input.root,'availability'),event,Buffer.from(stable({targetId:c.targetId,competition:c.competitionProviderId,scheduledStart:c.scheduledStart,pollTime:clocks.collectedAt,responseEmpty:r.raw.length===0,xiValid:input.source==='XI'&&status==='CONFIRMED_COMPLETE',playerCount,evidenceId:event,sha256:saved.sha256,source:input.source})));
 return{status:'SEALED',evidenceId:event,sha256:saved.sha256};
}
export function coverage(scope:Scope,bindings:Bridge[],evidence:Envelope[],source:SourceType){return ['39','140','135','78','UNRESOLVED_LEAGUE'].map(league=>{const targets=scope.targets.filter(t=>t.sport.toUpperCase()==='SOCCER').filter(t=>(bindings.find(b=>b.targetId===t.targetId)?.competitionProviderId??'UNRESOLVED_LEAGUE')===league);const counts={targets:targets.length,validEvidence:0,notAvailableYet:0,invalid:0,unresolved:0};for(const t of targets){const rows=evidence.filter(e=>e.targetId===t.targetId&&e.scopeIdentity===scope.scopeHash&&e.sourceType===source);if(rows.some(e=>['VALID','CONFIRMED_COMPLETE'].includes(e.validationStatus)&&e.temporalStatus==='SAFE'&&e.identityStatus==='EXACT'))counts.validEvidence++;else if(rows.some(e=>['INVALID','CONFLICT'].includes(e.validationStatus)))counts.invalid++;else if(rows.some(e=>['INCOMPLETE','UNKNOWN'].includes(e.validationStatus)))counts.notAvailableYet++;else counts.unresolved++;}return{league,source,...counts,coverage:counts.targets?counts.validEvidence/counts.targets:null};});}
/** Storage-facing API: caller supplies an explicit manifest, never a latest lookup. */
export async function coverageFromRefs(root:string,scope:Scope,bindings:Bridge[],refs:{evidenceId:string;sha256:string}[],source:SourceType){const evidence=await Promise.all(refs.map(r=>exactEvidence(root,r.evidenceId,r.sha256)));for(const e of evidence){requireProof(e.scopeIdentity===scope.scopeHash&&scope.targets.some(t=>t.targetId===e.targetId),'FOREIGN_EVIDENCE');requireProof(temporal(e),'UNSAFE_EVIDENCE');}for(const b of bindings){const t=scope.targets.find(t=>t.targetId===b.targetId);requireProof(t&&b.verified&&b.scopeIdentity===scope.scopeHash&&t.homeTeamRaw===b.homeTeamRaw&&t.awayTeamRaw===b.awayTeamRaw&&time(t.scheduledStartTimeKst!)===time(b.scheduledStart),'COVERAGE_BRIDGE');}return coverage(scope,bindings,evidence,source);}
