import {createHash} from 'node:crypto';
export const sha=(x:string|Buffer)=>createHash('sha256').update(x).digest('hex');
export function stable(x:unknown):string {requireProof(x!==undefined&&typeof x!=='function'&&typeof x!=='bigint'&&!(typeof x==='number'&&!Number.isFinite(x)),'NON_JSON_VALUE');if(x===null||typeof x!=='object')return JSON.stringify(x);if(Array.isArray(x))return '['+x.map(stable).join(',')+']';return '{'+Object.keys(x).filter(k=>(x as Record<string,unknown>)[k]!==undefined).sort().map(k=>JSON.stringify(k)+':'+stable((x as Record<string,unknown>)[k])).join(',')+'}';}
export function requireProof(ok:unknown,reason:string):asserts ok {if(!ok)throw Error(reason);}
export function time(x:string){requireProof(typeof x==='string','INVALID_TIME');const m=/^(\d{4})-(\d\d)-(\d\d)T(\d\d):(\d\d):(\d\d)(?:\.\d{1,3})?(?:Z|[+-]\d\d:\d\d)$/.exec(x);requireProof(m&&Number.isFinite(Date.parse(x)),'INVALID_TIME');const d=new Date(Date.UTC(+m[1],+m[2]-1,+m[3]));requireProof(d.getUTCFullYear()===+m[1]&&d.getUTCMonth()===+m[2]-1&&d.getUTCDate()===+m[3]&&+m[4]<24&&+m[5]<60&&+m[6]<60,'INVALID_TIME');return Date.parse(x);}
export const id=(x:unknown):x is string=>typeof x==='string'&&x.trim().length>0;
export type Clocks={observedAt:string;collectedAt:string;asOf:string;predictionCutoff:string;scheduledStart:string};
export function temporal(c:Clocks){try{return time(c.observedAt)<=time(c.collectedAt)&&time(c.asOf)<=time(c.collectedAt)&&time(c.collectedAt)<time(c.predictionCutoff)&&time(c.predictionCutoff)<=time(c.scheduledStart);}catch{return false;}}
export type Context={targetId:string;scopeIdentity:string;providerFixtureId:string;competitionProviderId:string;season:string;homeTeamId:string;awayTeamId:string;scheduledStart:string;predictionCutoff:string};
export type SourceType='XI'|'INJURY'|'PLAYER_STATS';
export type Envelope={schemaVersion:'football-v4-prospective-evidence-v1'|'football-v4-prospective-evidence-v2';evidenceId:string;targetId:string;scopeIdentity:string;providerName:'api-football';providerFixtureId:string;competitionProviderId:string;teamProviderId:string;sourceType:SourceType;observedAt:string;collectedAt:string;asOf:string;predictionCutoff:string;scheduledStart:string;providerUpdatedAt:string|null;sourceArtifactSha256:string;collectorVersion:string;identityStatus:'EXACT'|'UNRESOLVED'|'CONFLICT';temporalStatus:'SAFE'|'TEMPORAL_UNVERIFIED';validationStatus:string;featureAdmitted:false;payload:unknown};
export function evidenceId(ctx:Context,source:SourceType,team:string,event:string){requireProof(id(event),'EVENT_REQUIRED');return sha(stable([ctx.scopeIdentity,ctx.targetId,source,team,new Date(time(event)).toISOString()]));}
