import assert from 'node:assert/strict';import {readFileSync,writeFileSync,existsSync} from 'node:fs';import {join,resolve} from 'node:path';
import {exactEvidence} from '../src/lib/football/v4-prospective-evidence-v1/store';import {withVerifiedXI} from '../src/lib/football/official-canonical-v1/rich-preview-xi';import {richMarkdown} from '../src/lib/football/official-canonical-v1/rich-preview';import {digest,canonicalForFixture} from '../src/lib/football/official-canonical-v1';
async function main(){const [target,evidenceId,evidenceHash]=process.argv.slice(2);assert(/^BETMAN-\d{8}-\d+$/.test(target??'')&&/^[a-f0-9]{64}$/.test(evidenceId??'')&&/^[a-f0-9]{64}$/.test(evidenceHash??''),'EXPLICIT_TARGET_EVIDENCE_ID_HASH_REQUIRED');const repo=process.cwd(),date=`${target.slice(7,11)}-${target.slice(11,13)}-${target.slice(13,15)}`,root=resolve(repo,'../YANG-EDGE-INBOX/rich-preview-v2',date,'previews');
 const manifests=(await import('node:fs')).readdirSync(root).filter(n=>/^manifest-v\d+\.json$/.test(n)).sort((a,b)=>Number(b.match(/\d+/)![0])-Number(a.match(/\d+/)![0]));const oldManifest=JSON.parse(readFileSync(join(root,manifests[0]),'utf8')),entry=oldManifest.entries.find((r:any)=>r.targetId===target);assert(entry,'TARGET_PREVIEW_REQUIRED');const bytes=readFileSync(join(root,entry.file));assert(digest(bytes)===entry.sha256,'PREVIEW_HASH');const previous=JSON.parse(bytes.toString());const canonical=canonicalForFixture(join(repo,'data/cache/research/football/forward-shadow-v1'),previous.fixtureId);assert(canonical?.predictionId===previous.canonicalPredictionId,'CANONICAL_CHANGED');
 const registry=JSON.parse(readFileSync(join(repo,'data/research/slate-batches/round-111-odds-new-v1/priority-readiness-v1/player-registry.json'),'utf8'));
 const store=resolve(repo,'../YANG-EDGE-INBOX/football-v4-prospective-evidence-v1/pregame');const e=await exactEvidence(store,evidenceId,evidenceHash);const [injuryId,injuryHash]=process.argv.slice(5);assert(Boolean(injuryId)===Boolean(injuryHash),'INJURY_ID_AND_HASH_REQUIRED');const injury=injuryId?await exactEvidence(store,injuryId,injuryHash):undefined;const next=withVerifiedXI(previous,e,registry,new Date().toISOString(),entry.sha256,injury);
 const stem=`${target}-rich-preview-v${next.version}`,json=JSON.stringify(next,null,2)+'\n',md=richMarkdown(next),manifestVersion=Number(manifests[0].match(/\d+/)![0])+1;assert(!existsSync(join(root,stem+'.json'))&&!existsSync(join(root,stem+'.md')),'VERSION_EXISTS');writeFileSync(join(root,stem+'.json'),json,{flag:'wx'});writeFileSync(join(root,stem+'.md'),md,{flag:'wx'});
 writeFileSync(join(root,`manifest-v${manifestVersion}.json`),JSON.stringify({...oldManifest,createdAt:next.createdAt,previousManifestHash:digest(readFileSync(join(root,manifests[0]))),entries:oldManifest.entries.map((r:any)=>r.targetId===target?{...r,version:next.version,file:stem+'.json',markdown:stem+'.md',sha256:digest(json),markdownSha256:digest(md)}:r)},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({target,version:next.version,status:next.status,modelRecomputed:false}));}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
