import assert from 'node:assert/strict';import {readFileSync,writeFileSync,existsSync,readdirSync} from 'node:fs';import {join,resolve} from 'node:path';
import {canonicalForFixture,digest} from '../src/lib/football/official-canonical-v1';import {sha,stable} from '../src/lib/football/v4-prospective-evidence-v1/contracts';import {richMarkdown} from '../src/lib/football/official-canonical-v1/rich-preview';import {splitPreviewSeasons} from '../src/lib/football/official-canonical-v1/preview-season-split';
const repo=process.cwd(),root=resolve(repo,'../YANG-EDGE-INBOX/rich-preview-v2/2026-09-20/previews');
const latest=readdirSync(root).filter(n=>/^manifest-v\d+\.json$/.test(n)).sort((a,b)=>Number(b.match(/\d+/)![0])-Number(a.match(/\d+/)![0]))[0],manifestVersion=Number(latest.match(/\d+/)![0])+1;
const original=readFileSync(join(root,latest)),manifest=JSON.parse(original.toString());assert(!existsSync(join(root,`manifest-v${manifestVersion}.json`)),'VERSION_EXISTS');
const reportPath=join(repo,'data/cache/research/football/forward-shadow-v1/MODEL_FORWARD/runs/2026-09-13T07-30-40-751Z-d780b9c0-ffce-4e5d-be4e-0d6bbc037a27-report.json');const reportBytes=readFileSync(reportPath),report=JSON.parse(reportBytes.toString());assert.equal(sha(stable(report.payload)),report.sha256,'REPORT_HASH');
const entries=[],audit=[];
for(const entry of manifest.entries){const oldBytes=readFileSync(join(root,entry.file));assert.equal(digest(oldBytes),entry.sha256);const previous=JSON.parse(oldBytes.toString());const c=canonicalForFixture(join(repo,'data/cache/research/football/forward-shadow-v1'),entry.fixtureId)!;
 const next=splitPreviewSeasons(previous,c,report.payload.historyAudits,digest(reportBytes),new Date().toISOString(),entry.sha256);assert.deepEqual(next.officialV1,previous.officialV1);
 const stem=`${entry.targetId}-rich-preview-v${next.version}`,json=JSON.stringify(next,null,2)+'\n',md=richMarkdown(next);writeFileSync(join(root,stem+'.json'),json,{flag:'wx'});writeFileSync(join(root,stem+'.md'),md,{flag:'wx'});
 entries.push({...entry,version:next.version,file:stem+'.json',markdown:stem+'.md',sha256:digest(json),markdownSha256:digest(md)});
 audit.push(...next.seasonSplit!.teams.map(t=>({fixtureId:entry.fixtureId,teamId:t.teamId,name:t.name,currentSeasonMatches:t.current.all.all.count,previousSeasonMatches:t.previous.all.all.count,totalModelWindow:t.modelWindow.all.all.count,otherSeasonMatches:t.otherSeasonMatches,modelRelevantVenue:t.modelRelevantVenue,currentRelevantMatches:(t.modelRelevantVenue==='HOME'?t.current.home:t.current.away).all.count,previousRelevantMatches:(t.modelRelevantVenue==='HOME'?t.previous.home:t.previous.away).all.count,totalRelevantWindow:(t.modelRelevantVenue==='HOME'?t.modelWindow.home:t.modelWindow.away).all.count,current:{all:t.current.all.all,home:t.current.home.all,away:t.current.away.all},previous:{all:t.previous.all.all,home:t.previous.home.all,away:t.previous.away.all}})));
 assert.equal(digest(readFileSync(join(root,entry.file))),entry.sha256);
}
writeFileSync(join(root,`manifest-v${manifestVersion}.json`),JSON.stringify({...manifest,createdAt:new Date().toISOString(),previousManifestHash:digest(original),entries},null,2)+'\n',{flag:'wx'});
writeFileSync(join(root,`season-boundary-audit-manifest-v${manifestVersion}.json`),JSON.stringify({createdAt:new Date().toISOString(),sourceReportHash:digest(reportBytes),seasonProvenance:'ORIGINAL_PROVIDER_QUERY_HASH_AND_FETCH_TIMESTAMP',currentSeason:2026,previousSeason:2025,previewSeasonSplit:true,officialV1InputChanged:false,rows:audit},null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify(audit.map(({current,previous,...r})=>({...r,currentStats:{w:current.all.w,d:current.all.d,l:current.all.l,gf:current.all.gf,ga:current.all.ga},previousStats:{w:previous.all.w,d:previous.all.d,l:previous.all.l,gf:previous.all.gf,ga:previous.all.ga}})),null,2));
