import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import {join} from 'node:path';
import {readEnvelope,sha} from '../src/lib/research/terminal-decision/evidence';import {countOfficialPredictions} from '../src/lib/research/terminal-decision/prediction-counter';
import {loadScope,pollPlan,type Bridge} from '../src/lib/football/v4-prospective-evidence-v1/collector';import {registryGate} from '../src/lib/football/v4-prospective-evidence-v1/readiness';
const repo=process.cwd(),root=join(repo,'data/research/slate-batches/round-111-odds-new-v1'),out=join(root,'priority-readiness-v1');
const write=(name:string,x:unknown)=>{const p=join(out,name);writeFileSync(p,JSON.stringify(x,null,2)+'\n',{flag:'wx'});return sha(readFileSync(p));};
const read=(p:string)=>JSON.parse(readFileSync(join(root,p),'utf8'));const at=new Date().toISOString();const scope=loadScope(root,'2026-09-20');const registry=read('priority-readiness-v1/player-registry.json');const receipts=read('priority-readiness-v1/membership-receipts.json');
const parent='production-bridge-v1/',prior=read(parent+'mandatory-previews-v3.json'),identities=readEnvelope(join(root,parent+'priority-identity-evidence.json')).payload.rows;const previews=[],jobs=[],gates=[];
for(const row of identities){const prev=prior.find((p:any)=>p.TARGET_ID===row.targetId);assert(prev);const identity=row.identity;
 const proof={targetId:row.targetId,scopeIdentity:scope.scopeHash,providerFixtureId:String(identity.fixtureId),competitionProviderId:String(identity.leagueId),season:String(identity.season),homeTeamId:String(identity.homeTeamId),awayTeamId:String(identity.awayTeamId),homeTeamRaw:prev.home,awayTeamRaw:prev.away,scheduledStart:prev.kickoffKst,verificationStatus:'EXACT',fuzzyMatching:false,sourceEvidenceHash:row.evidenceHash,observedAt:row.observedAt};
 const name=`identity-${identity.fixtureId}.json`,proofHash=write(name,proof);const bridge:Bridge={...proof,verified:true,predictionCutoff:new Date(Date.parse(proof.scheduledStart)-60000).toISOString(),sourceEvidenceSha256:proofHash};const gate=registryGate(scope,bridge,registry,at);gates.push({targetId:row.targetId,...gate,committedManifestDryRun:'PENDING_COMMIT'});
 const registryRef={path:'priority-readiness-v1/player-registry.json',sha256:sha(readFileSync(join(out,'player-registry.json')))},rightsRef={path:parent+'rights-manifest.json',sha256:sha(readFileSync(join(root,parent+'rights-manifest.json')))};
 const polls=pollPlan(bridge);for(let i=0;i<polls.length;i++){const specs=i===0?[{source:'XI',teamId:bridge.homeTeamId},{source:'INJURY',teamId:bridge.homeTeamId},{source:'PLAYER_STATS',teamId:bridge.homeTeamId},{source:'PLAYER_STATS',teamId:bridge.awayTeamId}]:[{source:'XI',teamId:bridge.homeTeamId}];for(const spec of specs){const filename=`poll-${identity.fixtureId}-${i}-${spec.source}-${spec.teamId}.json`;write(filename,{bridge,identityEvidence:{path:'priority-readiness-v1/'+name,sha256:proofHash},registry:registryRef,rights:rightsRef,...spec,page:1,pollAt:polls[i],requestBudget:16,collectionAuthorized:true});jobs.push({targetId:row.targetId,pollAt:polls[i],manifest:'priority-readiness-v1/'+filename,...spec});}}
 const pdir=join(root,parent,'prediction-evidence',String(identity.fixtureId));const snapshot=readEnvelope(join(pdir,'snapshot.json')),input=readEnvelope(join(pdir,'input.json'));const v=snapshot.payload;
 assert.equal(v.fixtureId,identity.fixtureId);assert.equal(v.modelVersion,'football-poisson-research-v1');assert(Date.parse(v.predictionCreatedAt)<Date.parse(prev.kickoffKst));
 const history=input.payload.completedHistory;assert(Array.isArray(history));const context=[identity.homeTeamId,identity.awayTeamId].map(teamId=>{const rows=history.filter((h:any)=>h.homeTeamId===teamId||h.awayTeamId===teamId);return {teamId,completedInputMatches:rows.length,sourceInputHash:input.sha256,role:'SEALED_PAST_COMPLETED_INPUT_ONLY_NOT_CURRENT_TEAM_NEWS'};});
 previews.push({...prev,PREVIEW_STATUS:'PREVIEW_PRE_LINEUP',createdAt:at,LAST_UPDATED_AT:at,previousVersion:'production-bridge-v1/mandatory-previews-v3.json',previousVersionSha256:sha(readFileSync(join(root,parent+'mandatory-previews-v3.json'))),dataQuality:'EXACT_IDENTITY_SEALED_V1_AND_CURRENT_MEMBERSHIP; XI_INJURY_SUSPENSION_VENUE_UNKNOWN',DATA_QUALITY:'PREGAME_EVIDENCE_WITH_EXPLICIT_GAPS',OFFICIAL_V1:{modelVersion:v.modelVersion,predictionCreatedAt:v.predictionCreatedAt,pHome:v.pHome,pDraw:v.pDraw,pAway:v.pAway,predictedClass:v.predictedClass,predictionId:snapshot.sha256,inputSnapshotHash:v.inputSnapshotHash},historicalTeamContext:context,currentTeamContext:'Current roster observed; no confirmed lineup or availability evidence',form:'SEALED_HISTORY_COUNTS_ONLY',registryReady:true,registrySourceHashes:receipts.filter((r:any)=>[proof.homeTeamId,proof.awayTeamId].includes(r.teamId)).map((r:any)=>r.sourceSha256),pollExecution:'READY_AFTER_COMMITTED_DRY_RUN; NOT_EXECUTED',nextUpdate:'Append PREVIEW_XI_AVAILABLE only on valid exact XI; never overwrite this version.',missingEvidence:['VENUE','CONFIRMED_XI','INJURY','SUSPENSION','TACTICAL_ANALYSIS'],oddsEvidence:{...prev.oddsEvidence,blankMarketLabelMeaning:'UNRESOLVED_NOT_INFERRED',blankOddsMeaning:'UNKNOWN_NOT_ZERO',marketInputAllowed:false},globalSnapshotConflict:true,globalConflictPolicy:'Batch seal shown with explicit provenance; canonical global precedence unresolved; no silent overwrite or grading selection'});
}
write('mandatory-previews-v4.json',previews);write('gate-precommit.json',{createdAt:at,gates,providerCalls:0,xiConfirmed:false});write('poll-job-index.json',{createdAt:at,jobs,totalPlannedCalls:jobs.length,dailyFrozenBudget:16,noAutomaticPagination:true,statsPage1Only:true,statsValidation:'UNRESOLVED_UNTIL_DATA_THROUGH_REVIEW',noOSServiceInstalled:true});
write('counts-final.json',countOfficialPredictions([{label:'OFFICIAL_FORWARD',modelRoot:join(repo,'data/cache/research/football/forward-shadow-v1/MODEL_FORWARD')},{label:'ROUND_111',modelRoot:join(root,'data/cache/research/football/forward-shadow-v1/MODEL_FORWARD')}]));
write('registry-recovery-audit.json',{createdAt:at,firstAttemptProviderCalls:4,firstAttemptStatus:'RAW_PRESERVED_RECEIPT_NOT_DURABLE_REGISTRY_NOT_ADMITTED',firstFailure:'DUPLICATE_PLAYER_ID_381014',retryProviderCalls:4,retryReason:'Attended recovery after fully identical duplicate row diagnosis; fresh receipt timestamps recorded, never backdated',collapsedIdenticalRawRows:1,registryPlayers:registry.length,rawLocalOnly:true,formalLicenseConfirmed:false,rightsStatus:'CONDITIONAL_INTERNAL_OWNER_AUTHORIZED_PROVIDER_CHAT_GUIDANCE',targetResultsAccessed:false});
console.log(JSON.stringify({previews:previews.length,jobs:jobs.length,gates},null,2));
