import assert from 'node:assert/strict';import {readFileSync,mkdirSync,writeFileSync,existsSync} from 'node:fs';import {join} from 'node:path';
import {selectProductionBatch} from '../src/lib/research/terminal-decision/batch-selection';import {loadCommittedProductionScope} from '../src/lib/research/terminal-decision/production-authority';import {readEnvelope,sha} from '../src/lib/research/terminal-decision/evidence';
import {countOfficialPredictions} from '../src/lib/research/terminal-decision/prediction-counter';import {collectSquadMembership} from '../src/lib/football/foundation/squad-membership-collector';import {populateMembership,type SquadReceipt} from '../src/lib/football/v4-prospective-evidence-v1/membership';
async function main(){const repo=process.cwd(),selected=selectProductionBatch(repo,'2026-09-20','round-111-odds-new-v1'),scope=loadCommittedProductionScope(selected.root,'2026-09-20'),out=join(selected.root,'priority-readiness-v1');mkdirSync(out,{recursive:true});
const write=(name:string,x:unknown)=>writeFileSync(join(out,name),JSON.stringify(x,null,2)+'\n',{flag:'wx'});
const counts=countOfficialPredictions([{label:'OFFICIAL_FORWARD',modelRoot:join(repo,'data/cache/research/football/forward-shadow-v1/MODEL_FORWARD')},{label:'ROUND_111',modelRoot:join(selected.root,'data/cache/research/football/forward-shadow-v1/MODEL_FORWARD')}]);if(!existsSync(join(out,'counts-before.json')))write('counts-before.json',counts);console.log(JSON.stringify({counts:{total:counts.total,graded:counts.graded,ungraded:counts.ungraded,invalid:counts.invalid,conflicts:counts.conflicts,passes:counts.passes}}));
const parent=JSON.parse(readFileSync(join(selected.root,'production-bridge-v1/rights-manifest.json'),'utf8'));
assert.equal(parent.internalCollectionAuthorized,true);const rights={...parent,schemaVersion:'internal-squad-membership-rights-v1',createdAt:new Date().toISOString(),membershipEndpoints:['/players/squads'],purpose:'Minimum current roster ID evidence for the four exact priority fixture teams; no scores or player performance features',authority:'Explicit owner mission ROUND 111 PRIORITY PREVIEW + V4 REGISTRY READINESS V1 section 6; same CONDITIONAL private internal-use basis, no legal upgrade.',documentation:'https://www.api-football.com/news/post/football-players-squads',membershipSemantics:'Current club roster observed now. League/season are target fixture context, not an assertion of league registration eligibility. validFrom=actual observation, not transfer date.'};if(!existsSync(join(out,'membership-rights.json')))write('membership-rights.json',rights);
const identities=readEnvelope(join(selected.root,'production-bridge-v1/priority-identity-evidence.json')).payload.rows;const receipts:SquadReceipt[]=[];const teams=[];
for(const row of identities){const t=scope.doc.targets.find(t=>t.targetId===row.targetId);assert(t&&row.scopeSha256===scope.hash);assert(Date.now()<Date.parse(t.scheduledStartTimeKst!));for(const teamId of [row.identity.homeTeamId,row.identity.awayTeamId])teams.push({teamId:String(teamId),leagueId:String(row.identity.leagueId),season:String(row.identity.season),cutoff:new Date(Date.parse(t.scheduledStartTimeKst!)-60000).toISOString()});}
const key=process.env.FOOTBALL_API_KEY??process.env.API_FOOTBALL_KEY??'';
for(const team of teams){if(receipts.length)await new Promise(r=>setTimeout(r,6500));receipts.push(await collectSquadMembership({...team,rights,localRawDir:join(repo,'data/cache/research/round-111-priority-identity/membership-v1')},key));}
const registry=populateMembership(receipts);write('membership-receipts.json',receipts);write('player-registry.json',registry);write('team-registry.json',teams);
const status={createdAt:new Date().toISOString(),registryInfrastructureImplemented:true,registryPopulatedAndVerified:true,teamRegistryReady:true,playerRegistryReady:true,membershipBindingReady:true,exact:registry.length,unresolved:0,conflict:0,byTeam:Object.fromEntries(teams.map(t=>[t.teamId,registry.filter(r=>r.teamProviderId===t.teamId).length])),providerCalls:receipts.length,registrySha256:sha(readFileSync(join(out,'player-registry.json'))),collectionPhase:'MEMBERSHIP_BOOTSTRAP_NOT_XI_POLL',xiEvidenceCreated:0,featuresAdmitted:0,engineImplemented:false};write('registry-status.json',status);console.log(JSON.stringify(status,null,2));}
main().catch(e=>{console.error(e instanceof Error?e.message:'REGISTRY_PREPARATION_BLOCKED');process.exitCode=1;});
