import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,readdirSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {digest,canonicalForFixture} from '../src/lib/football/official-canonical-v1';
import {refreshPreview} from '../src/lib/football/official-canonical-v1/preview-recency-v3';
import {richMarkdown} from '../src/lib/football/official-canonical-v1/rich-preview';
const base=resolve('../YANG-EDGE-INBOX/rich-preview-v2/2026-09-20'),root=join(base,'previews');
const latest=readdirSync(root).filter(n=>/^manifest-v\d+\.json$/.test(n)).sort((a,b)=>Number(b.match(/\d+/)![0])-Number(a.match(/\d+/)![0]))[0];
const mb=readFileSync(join(root,latest)),m=JSON.parse(mb.toString()),version=Number(latest.match(/\d+/)![0])+1;
const entry=m.entries.find((e:any)=>e.fixtureId===1570394),oldBytes=readFileSync(join(root,entry.file));assert.equal(digest(oldBytes),entry.sha256);const old=JSON.parse(oldBytes.toString());assert(!old.recency,'RECENCY_VERSION_ALREADY_EXISTS');
const context=JSON.parse(readFileSync(join(base,'context.json'),'utf8')),freshBytes=readFileSync(join(base,'recency-v3/context.json')),fresh=JSON.parse(freshBytes.toString());
for(const [ctx,dir]of [[context,base],[fresh,join(base,'recency-v3')]])for(const r of ctx.receipts)assert.equal(digest(readFileSync(join(dir,r.sha256+'.json'))),r.sha256,'RAW_HASH');
const registry=JSON.parse(readFileSync('data/research/slate-batches/round-111-odds-new-v1/priority-readiness-v1/player-registry.json','utf8'));
const c=canonicalForFixture('data/cache/research/football/forward-shadow-v1',1570394)!;assert.equal(c.predictionId,old.canonicalPredictionId);
const next=refreshPreview(old,fresh.history,context,registry,new Date().toISOString(),entry.sha256);assert.deepEqual(next.officialV1,old.officialV1);assert.deepEqual(next.seasonSplit,old.seasonSplit);
const file=`${entry.targetId}-rich-preview-v${next.version}.json`,bytes=JSON.stringify(next,null,2)+'\n';writeFileSync(join(root,file),bytes,{flag:'wx'});writeFileSync(join(root,file.replace('.json','.md')),richMarkdown(next),{flag:'wx'});
const entries=m.entries.map((e:any)=>e===entry?{...e,version:next.version,file,markdown:file.replace('.json','.md'),sha256:digest(bytes),markdownSha256:digest(richMarkdown(next))}:e);
writeFileSync(join(root,`manifest-v${version}.json`),JSON.stringify({...m,createdAt:next.createdAt,previousManifestHash:digest(mb),entries},null,2)+'\n',{flag:'wx'});
assert.equal(digest(readFileSync(join(root,entry.file))),entry.sha256);
console.log(JSON.stringify({version:next.version,hash:digest(bytes),recency:next.recency},null,2));
