import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {populateMembership,type SquadReceipt} from '../src/lib/football/v4-prospective-evidence-v1/membership';
import {resolvePlayer,appendPlayer} from '../src/lib/football/v4-prospective-evidence-v1/registry';
import {collectSquadMembership} from '../src/lib/football/foundation/squad-membership-collector';
import {countOfficialPredictions} from '../src/lib/research/terminal-decision/prediction-counter';
import {envelope} from '../src/lib/research/terminal-decision/evidence';
const receipt=(teamId='50'):SquadReceipt=>({teamId,leagueId:'39',season:'2026',observedAt:'2026-09-20T04:00:00Z',collectedAt:'2026-09-20T04:00:00Z',sourceSha256:'a'.repeat(64),endpoint:'/players/squads',players:[{id:1,name:'Same'},{id:2,name:'Same'}]});
test('same-name players remain distinct by ID and observed membership is not backdated',()=>{const r=populateMembership([receipt()]);assert.equal(r.length,2);assert.notEqual(r[0].canonicalPlayerId,r[1].canonicalPlayerId);assert.equal(resolvePlayer(r,{provider:'api-football',playerId:'1',teamId:'50',competitionId:'39',season:'2026',at:'2026-09-19T00:00:00Z',knownAt:'2026-09-20T05:00:00Z'}).status,'UNRESOLVED');});
test('duplicates, empty roster and unsafe timestamps fail closed',()=>{const r=receipt();assert.throws(()=>populateMembership([{...r,players:[r.players[0],r.players[0]]}]));assert.throws(()=>populateMembership([{...r,players:[]}]));assert.throws(()=>populateMembership([{...r,collectedAt:'2026-09-19T00:00:00Z'}]));});
test('transfer requires closing old membership; no overlapping team assignment',()=>{let r=populateMembership([receipt()]);assert.throws(()=>populateMembership([{...receipt('746'),observedAt:'2026-09-21T00:00:00Z',collectedAt:'2026-09-21T00:00:00Z'}],r));const old=r[0];r=appendPlayer(r,{...old,recordId:'closed',supersedesId:old.recordId,recordedAt:'2026-09-21T00:00:00Z',validTo:'2026-09-21T00:00:00Z'});r=populateMembership([{...receipt('746'),players:[{id:1,name:'Renamed'}],observedAt:'2026-09-21T00:00:00Z',collectedAt:'2026-09-21T00:00:00Z',sourceSha256:'b'.repeat(64)}],r);assert.equal(r.length,4);});
test('membership acquisition cannot call provider without endpoint rights',async()=>{let calls=0;await assert.rejects(()=>collectSquadMembership({teamId:'50',leagueId:'39',season:'2026',cutoff:'2099-01-01T00:00:00Z',rights:{internalCollectionAuthorized:true,membershipEndpoints:[]},localRawDir:tmpdir()},'test',async()=>{calls++;throw Error('NEVER');}),/RIGHTS/);assert.equal(calls,0);});
test('wrong provider team cannot populate registry',async()=>{await assert.rejects(()=>collectSquadMembership({teamId:'50',leagueId:'39',season:'2026',cutoff:'2099-01-01T00:00:00Z',rights:{internalCollectionAuthorized:true,membershipEndpoints:['/players/squads']},localRawDir:tmpdir()},'test',async()=>new Response(JSON.stringify({response:[{team:{id:746},players:[]}],errors:[]}))),/TEAM/);});
test('counter validates pregame hashes, ignores PASS, and never parses grade outcomes',t=>{const root=mkdtempSync(join(tmpdir(),'ye-count-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const dir=join(root,'fixtures','1');mkdirSync(dir,{recursive:true});const s=envelope({fixtureId:1,modelVersion:'football-poisson-research-v1',modelSourceHash:'6efa82f916346599b5e9c6ee4ad768501f7a0d2254dc9d2376acd5df755aadbf',layer:'MODEL_FORWARD',predictionCreatedAt:'2026-01-01T00:00:00Z',kickoffUtc:'2026-01-02T00:00:00Z',status:'PREDICTED',pHome:.5,pDraw:.2,pAway:.3});writeFileSync(join(dir,'snapshot.json'),JSON.stringify(s));writeFileSync(join(dir,'seal-receipt.json'),JSON.stringify(envelope({snapshotHash:s.sha256,validPregame:true,sealedAt:'2026-01-01T00:00:01Z'})));mkdirSync(join(root,'postgame'));writeFileSync(join(root,'postgame','1.json'),'DO NOT PARSE OUTCOMES');const c=countOfficialPredictions([{label:'one',modelRoot:root},{label:'copy',modelRoot:root}]);assert.equal(c.total,1);assert.equal(c.graded,1);assert.equal(c.duplicateCopies,1);writeFileSync(join(dir,'snapshot.json'),'{}');assert.equal(countOfficialPredictions([{label:'one',modelRoot:root}]).invalid.length,1);});
// Independent normalization scenarios own separate receipt destinations, even in the same millisecond.
test('collector persists reception receipt and only collapses identical raw ID rows',async t=>{const root=mkdtempSync(join(tmpdir(),'ye-roster-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const q={teamId:'50',leagueId:'39',season:'2026',cutoff:'2099-01-01T00:00:00Z',rights:{internalCollectionAuthorized:true,membershipEndpoints:['/players/squads']},localRawDir:join(root,'identical-rows')};const player={id:42,name:'Same',position:'Defender'};const transport=async()=>new Response(JSON.stringify({response:[{team:{id:50},players:[player,player]}],errors:[]}));const r=await collectSquadMembership(q,'test',transport);assert.equal(r.players.length,1);assert.equal(populateMembership([r]).length,1);await assert.rejects(()=>collectSquadMembership({...q,localRawDir:join(root,'conflicting-rows')},'test',async()=>new Response(JSON.stringify({response:[{team:{id:50},players:[player,{...player,position:'Midfielder'}]}],errors:[]}))),/CONFLICTING_PLAYER_ROWS/);});
import {registryGate} from '../src/lib/football/v4-prospective-evidence-v1/readiness';
import type {Scope,Bridge} from '../src/lib/football/v4-prospective-evidence-v1/collector';
test('readiness dry-run rejects empty registry, future knowledge, and wrong exact side',()=>{const b:Bridge={targetId:'t',scopeIdentity:'a'.repeat(64),providerFixtureId:'1',competitionProviderId:'39',season:'2026',homeTeamId:'50',awayTeamId:'746',scheduledStart:'2026-09-20T13:00:00Z',predictionCutoff:'2026-09-20T12:59:00Z',verified:true,homeTeamRaw:'Home',awayTeamRaw:'Away',sourceEvidenceSha256:'b'.repeat(64)};const scope:Scope={scopeHash:b.scopeIdentity,targets:[{targetId:'t',operatorSlateGameId:'t',sport:'SOCCER',competitionNameRaw:'EPL',homeTeamRaw:'Home',awayTeamRaw:'Away',scheduledStartTimeKst:b.scheduledStart,providerFixtureId:null,providerGameId:null}]};const r=populateMembership([receipt(),{...receipt('746'),players:[{id:3,name:'Same'}]}]);assert.equal(registryGate(scope,b,r,'2026-09-20T05:00:00Z').status,'READY');assert.throws(()=>registryGate(scope,b,[],'2026-09-20T05:00:00Z'),/REGISTRY/);assert.throws(()=>registryGate(scope,b,r,'2026-09-20T03:00:00Z'),/AS_OF/);assert.throws(()=>registryGate(scope,{...b,homeTeamRaw:'Away'},r,'2026-09-20T05:00:00Z'),/BRIDGE/);});
test('different seals for one fixture are exposed as conflict, never two unique predictions',t=>{const root=mkdtempSync(join(tmpdir(),'ye-conflict-'));t.after(()=>rmSync(root,{recursive:true,force:true}));const roots=['first','second'].map((label,i)=>{const modelRoot=join(root,label),dir=join(modelRoot,'fixtures','1');mkdirSync(dir,{recursive:true});const s=envelope({fixtureId:1,modelVersion:'football-poisson-research-v1',modelSourceHash:'6efa82f916346599b5e9c6ee4ad768501f7a0d2254dc9d2376acd5df755aadbf',layer:'MODEL_FORWARD',predictionCreatedAt:'2026-01-01T00:00:00Z',kickoffUtc:'2026-01-02T00:00:00Z',status:'PREDICTED',pHome:.5+i*.1,pDraw:.2,pAway:.3-i*.1});writeFileSync(join(dir,'snapshot.json'),JSON.stringify(s));writeFileSync(join(dir,'seal-receipt.json'),JSON.stringify(envelope({snapshotHash:s.sha256,validPregame:true,sealedAt:'2026-01-01T00:00:01Z'})));return{label,modelRoot};});const c=countOfficialPredictions(roots);assert.equal(c.total,1);assert.equal(c.sealedPredictionArtifacts,2);assert.equal(c.ungradedArtifacts,2);assert.equal(c.ungraded,1);assert.deepEqual(c.conflicts,[1]);assert.equal(c.conflictDetails.length,2);assert.equal(c.status,'DISCREPANCY');});
