import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,existsSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {chooseCanonical,inspectOfficialSeal,officialInventory,canonicalGradeAllowed,withOfficialFixtureLock,OFFICIAL_HASH} from '../src/lib/football/official-canonical-v1';
import {envelope,freeze,type Fixture} from './football-forward-shadow-v1';import {validateGrade} from './football-forward-validation-v1';import {collectPostgame} from './run-football-forward-postgame-v1';import {evaluateForwardCumulative} from './football-forward-cumulative-evaluation-v1';
const start='2026-12-20T12:00:00.000Z',early='2026-12-18T12:00:00.000Z',late='2026-12-19T12:00:00.000Z';
function setup(t:any){const repo=mkdtempSync(join(tmpdir(),'canonical-'));t.after(()=>rmSync(repo,{recursive:true,force:true}));mkdirSync(join(repo,'src/lib/football/poisson-research-v1'),{recursive:true});writeFileSync(join(repo,'package.json'),'{}');writeFileSync(join(repo,'src/lib/football/poisson-research-v1/index.ts'),'// synthetic repository marker');const global=join(repo,'data/cache/research/football/forward-shadow-v1'),batch=join(repo,'data/research/slate-batches/test/data/cache/research/football/forward-shadow-v1');mkdirSync(batch,{recursive:true});return{repo,global,batch};}
function fixture(at=early):Fixture{return{fixtureId:7,leagueId:39,season:2026,kickoffUtc:start,homeTeam:{id:10,name:'Home'},awayTeam:{id:20,name:'Away'},providerStatus:'NS',scheduleFetchedAt:new Date(Date.parse(at)-1000).toISOString()};}
function seal(root:string,at:string,home=.5){const f=fixture(at),history=[{providerFixtureId:8,kickoffUtc:'2026-12-10T12:00:00.000Z',leagueId:39,homeTeamId:10,awayTeamId:20,fixtureStatus:'FT',fullTimeHomeGoals:1,fullTimeAwayGoals:1,providerFetchedAt:'2026-12-11T12:00:00.000Z',sourceHash:'a'.repeat(64)}];const input=envelope({target:{matchId:'API_FOOTBALL:7',competitionId:'39',homeTeamId:'10',awayTeamId:'20',kickoffAt:start},targetScheduleObservation:f,cutoffAt:at,completedHistory:history});const snapshot=envelope({layer:'MODEL_FORWARD',fixtureId:7,leagueId:39,season:2026,homeTeam:f.homeTeam,awayTeam:f.awayTeam,kickoffUtc:start,cutoffAt:at,predictionCreatedAt:at,status:'PREDICTED',pHome:home,pDraw:.2,pAway:.8-home,predictedClass:'HOME',modelVersion:'football-poisson-research-v1',modelSourceHash:OFFICIAL_HASH,inputSnapshotHash:input.sha256,trainingFixtureIds:['API_FOOTBALL:8'],trainingProviderFixtureIds:[8],TARGET_RESULT_DATA_USED:false,ODDS_USED:false,MARKET_USED:false,PROVIDER_PREDICTION_USED:false,OWNER_SHADOW_USED:false,EXTERNAL_SHADOW_USED:false});const dir=join(root,'MODEL_FORWARD/fixtures/7');mkdirSync(dir,{recursive:true});for(const [name,value] of Object.entries({'input.json':input,'snapshot.json':snapshot,'seal-receipt.json':envelope({fixtureId:7,snapshotHash:snapshot.sha256,sealedAt:at,validPregame:true})}))writeFileSync(join(dir,name),JSON.stringify(value));return snapshot;}
test('earliest valid rule ignores probability strength and input enumeration order',t=>{const {global,batch}=setup(t),first=seal(global,early,.4),second=seal(batch,late,.7);const rows=chooseCanonical([inspectOfficialSeal(batch,7),inspectOfficialSeal(global,7)]);assert(rows.every(r=>r.eligible));assert.equal(rows.find(r=>r.classification==='CANONICAL')?.predictionId,first.sha256);assert.equal(rows.find(r=>r.classification==='DUPLICATE_NONCANONICAL')?.predictionId,second.sha256);const counts=officialInventory(global).counts;assert.deepEqual(counts,{sealedArtifacts:2,uniqueFixtures:1,canonicalPredictions:1,duplicateNoncanonical:1,invalidForCanonicalCount:0});});
test('invalid earlier receipt falls back without deleting or changing either snapshot',t=>{const {global,batch}=setup(t);seal(global,early);const valid=seal(batch,late);const path=join(global,'MODEL_FORWARD/fixtures/7/snapshot.json'),before=readFileSync(path);writeFileSync(join(global,'MODEL_FORWARD/fixtures/7/invalid.json'),'{}');const rows=officialInventory(global).rows;assert.equal(rows.find(r=>r.classification==='CANONICAL')?.predictionId,valid.sha256);assert.equal(rows.filter(r=>r.classification==='INVALID_FOR_CANONICAL_COUNT').length,1);assert(readFileSync(path).equals(before));});
test('provenance and target-field contamination fail before ranking',t=>{const {global}=setup(t);seal(global,early);const path=join(global,'MODEL_FORWARD/fixtures/7/input.json');const i=JSON.parse(readFileSync(path,'utf8'));i.payload.target.actualScore={home:0,away:0};const modified=envelope(i.payload);writeFileSync(path,JSON.stringify(modified));const sp=join(global,'MODEL_FORWARD/fixtures/7/snapshot.json'),s=JSON.parse(readFileSync(sp,'utf8'));s.payload.inputSnapshotHash=modified.sha256;const sn=envelope(s.payload);writeFileSync(sp,JSON.stringify(sn));writeFileSync(join(global,'MODEL_FORWARD/fixtures/7/seal-receipt.json'),JSON.stringify(envelope({fixtureId:7,snapshotHash:sn.sha256,sealedAt:early,validPregame:true})));assert.equal(inspectOfficialSeal(global,7).eligible,false);});
test('runner prevents a new batch seal and never invokes model/history inputs',t=>{const {global,batch}=setup(t),prior=seal(global,early);const observations=new Proxy([],{get(){throw Error('MODEL_INPUT_MUST_NOT_BE_READ');}});const r=freeze(batch,fixture(late),()=>Date.parse(late),observations);assert.equal(r.kind,'EXISTING_OFFICIAL_PREDICTION');assert.equal(r.envelope.sha256,prior.sha256);assert(!existsSync(join(batch,'MODEL_FORWARD/fixtures/7/snapshot.json')));assert.throws(()=>freeze(batch,{...fixture(late),awayTeam:{id:99,name:'Wrong'}},()=>Date.parse(late)),/IDENTITY_CONFLICT/);});
test('shared fixture lock fails closed for simultaneous namespaces',t=>{const {global,batch}=setup(t);assert.throws(()=>withOfficialFixtureLock(global,7,()=>withOfficialFixtureLock(batch,7,()=>undefined)),/EEXIST/);});
test('noncanonical grade excluded before body read, collection or evaluation denominator',async t=>{const {global,batch}=setup(t),first=seal(global,early),second=seal(batch,late);assert(canonicalGradeAllowed(global,7,first.sha256));assert(!canonicalGradeAllowed(batch,7,second.sha256));mkdirSync(join(batch,'MODEL_FORWARD/postgame'),{recursive:true});writeFileSync(join(batch,'MODEL_FORWARD/postgame/7.json'),'FORBIDDEN_GRADE_BODY_NOT_JSON');assert.throws(()=>validateGrade(batch,7,Date.parse(start)+10000),/NONCANONICAL/);let calls=0;const collected=await collectPostgame(batch,'synthetic',{clock:()=>Date.parse(start)+10000,fetcher:async()=>{calls++;throw Error('FORBIDDEN_NETWORK');}});assert.equal(calls,0);assert.equal(collected.payload.rows[0].status,'DUPLICATE_NONCANONICAL_EXCLUDED');const evaluation=evaluateForwardCumulative(batch,Date.parse(start)+10000);assert.equal(evaluation.payload.counts.totalGraded,0);assert.equal(evaluation.payload.counts.totalPredicted,0);assert.equal(evaluation.payload.integrityExclusions[0].reason,'DUPLICATE_NONCANONICAL_EXCLUDED');});
test('same timestamp tie break is stable SHA only',t=>{const {global,batch}=setup(t);seal(global,early,.4);seal(batch,early,.6);const rows=[inspectOfficialSeal(global,7),inspectOfficialSeal(batch,7)],wanted=rows.map(r=>r.predictionId!).sort()[0];assert.equal(chooseCanonical(rows.reverse()).find(r=>r.classification==='CANONICAL')?.predictionId,wanted);});
import {canonicalPreview,writePreviewVersion} from '../src/lib/football/official-canonical-v1/preview';
test('identical mirror bytes still have exactly one physical grade authority',t=>{const {global,batch}=setup(t),first=seal(global,early);seal(batch,early);const rows=officialInventory(global).rows;assert.equal(rows.filter(r=>r.classification==='CANONICAL').length,1);assert.equal([global,batch].filter(r=>canonicalGradeAllowed(r,7,first.sha256)).length,1);});
test('preview selects canonical values only, preserves old version and rejects noncanonical source',t=>{const {repo,global,batch}=setup(t);seal(global,early,.4);seal(batch,late,.7);const rows=officialInventory(global).rows,selected=rows.find(r=>r.classification==='CANONICAL')!;const previous={TARGET_ID:'operator',providerFixtureId:7,providerHomeTeamId:10,providerAwayTeamId:20,kickoffKst:start,home:'Home',away:'Away',registrySourceHashes:[],officialV1:{pHome:.7},OFFICIAL_V1:{pHome:.7},inputProof:{role:'BATCH'}};const old=JSON.stringify(previous);const preview=canonicalPreview(previous,selected,late,'previous.json','a'.repeat(64));assert.equal(preview.OFFICIAL_V1.pHome,.4);assert.equal(preview.canonicalPredictionId,selected.predictionId);assert(!('officialV1' in preview));assert.equal(JSON.stringify(previous),old);assert.throws(()=>canonicalPreview(previous,rows.find(r=>r.classification==='DUPLICATE_NONCANONICAL')!,late,'old','a'.repeat(64)));const file=join(repo,'preview-v2.json');writePreviewVersion(file,preview);const bytes=readFileSync(file);assert.throws(()=>writePreviewVersion(file,{bad:true}),/EEXIST/);assert(readFileSync(file).equals(bytes));});
