import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtempSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {planPregame} from '../src/lib/research/terminal-decision/lifecycle';
import {resolveExactPregameIdentity,assertOneToOneBindings,type ExactBinding,type PregameIdentity} from '../src/lib/betman/daily-slate/exact-pregame-identity';
import {validatePregameObservation,collectPregameObservation,loadPregameInputBundle,type Receipt} from '../src/lib/mlb/prediction-v0/pregame-provenance';
const now='2030-01-01T00:00:00Z',start='2030-01-01T01:00:00Z',scope='a'.repeat(64);
const hash=(b:Buffer)=>createHash('sha256').update(b).digest('hex');
const base={scheduledStart:start,now,existingTerminal:false,readiness:'PENDING' as const};
for(const readiness of ['PENDING','IDENTITY_BLOCKED','AS_OF_BLOCKED','INPUT_WAITING','PIPELINE_BLOCKED'] as const)test(`lifecycle ${readiness} waits without terminal action`,()=>assert.equal(planPregame({...base,readiness}).action,'WAIT'));
const prediction={kind:'FOOTBALL_FORWARD_V1' as const,fixtureId:123,snapshotHash:scope,scopeSha256:scope};
test('lifecycle ready reference may proceed to strict terminal validation',()=>assert.equal(planPregame({...base,prediction}).action,'PREDICTION'));
test('lifecycle exact deadline supersedes readiness',()=>assert.deepEqual(planPregame({...base,now:start,prediction}),{action:'PASS',reason:'PASS_PREGAME_WINDOW_MISSED'}));
for(const next of [{prediction},{hardLimitation:{reason:'PASS_ENGINE_NOT_APPROVED' as const,finalForDate:true as const,evidence:'unsupported league approval'}}])test('lifecycle existing terminal always preserved',()=>assert.equal(planPregame({...base,...next,existingTerminal:true}).action,'PRESERVE'));
test('lifecycle hard limitation requires explicit evidence',()=>assert.throws(()=>planPregame({...base,hardLimitation:{reason:'PASS_ENGINE_NOT_APPROVED',finalForDate:true,evidence:''}})));
const target={targetId:'synthetic',operatorSlateGameId:'synthetic',sport:'SOCCER' as const,competitionNameRaw:'테스트',homeTeamRaw:'홈',awayTeamRaw:'원정',scheduledStartTimeKst:start,providerGameId:null,providerFixtureId:null};
const source:PregameIdentity={provider:'API_FOOTBALL',fixtureId:123,leagueId:39,season:2029,kickoffUtc:start,homeTeamId:1,awayTeamId:2,homeTeamName:'Home',awayTeamName:'Away',status:'NS',observedAt:'2029-12-31T23:00:00Z'};
const bytes=Buffer.from(JSON.stringify(source));
const binding:ExactBinding={targetId:'synthetic',scopeSha256:scope,homeRaw:'홈',awayRaw:'원정',competitionRaw:'테스트',providerFixtureId:123,homeProviderId:1,awayProviderId:2,leagueId:39,season:2029,scheduledStart:start,reviewStatus:'VERIFIED',reviewedAt:'2029-12-31T23:30:00Z',evidenceSha256:hash(bytes)};
test('identity exact reviewed directed binding succeeds',()=>assert.equal(resolveExactPregameIdentity(target,scope,binding,bytes,now).fixtureId,123));
for(const patch of [{homeProviderId:2,awayProviderId:1},{scopeSha256:'b'.repeat(64)},{season:2030},{scheduledStart:'2030-01-01T01:01:00Z'},{reviewStatus:'DRAFT'},{homeRaw:'홈팀'}])test(`identity rejects ${JSON.stringify(patch)}`,()=>assert.throws(()=>resolveExactPregameIdentity(target,scope,{...binding,...patch} as ExactBinding,bytes,now)));
test('identity rejects result fields even with matching hash',()=>{const b=Buffer.from(JSON.stringify({...source,result:null}));assert.throws(()=>resolveExactPregameIdentity(target,scope,{...binding,evidenceSha256:hash(b)},b,now));});
test('identity duplicate provider binding rejected',()=>assert.throws(()=>assertOneToOneBindings([binding,{...binding,targetId:'second'}])));
test('identity no post-start bridge',()=>assert.throws(()=>resolveExactPregameIdentity(target,scope,binding,bytes,start)));
const mlbTarget={provider:'SYNTHETIC',targetId:'m1',homeTeamId:'h',awayTeamId:'a',scheduledStart:start};
const receipt:Receipt={schemaVersion:'mlb-pregame-observation-v1',target:mlbTarget,kind:'HomeStarter',sourceIdentity:'synthetic:starter:h',asOf:'2029-12-31T22:00:00Z',targetExcludedFromHistory:true,collectedAt:'2029-12-31T23:00:00Z',observedAt:'2029-12-31T23:01:00Z',sha256:hash(bytes)};
test('provenance exact bytes and real observation order',()=>assert.equal(validatePregameObservation(receipt,bytes,mlbTarget,now),true));
for(const patch of [{observedAt:start},{collectedAt:'invalid'},{asOf:'2030-01-01T00:30:00Z'},{targetExcludedFromHistory:false},{sha256:'0'.repeat(64)}])test(`provenance rejects ${JSON.stringify(patch)}`,()=>assert.throws(()=>validatePregameObservation({...receipt,...patch} as Receipt,bytes,mlbTarget,now)));
test('provenance wrong target rejected',()=>assert.throws(()=>validatePregameObservation(receipt,bytes,{...mlbTarget,targetId:'m2'},now)));
test('provenance deadline equality rejected',()=>assert.throws(()=>validatePregameObservation(receipt,bytes,mlbTarget,start)));
test('collector records actual time, is exclusive, and missing inputs fail closed',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'ye-provenance-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));
 const target={...mlbTarget,scheduledStart:new Date(Date.now()+3600000).toISOString()};const p=join(dir,'observation.json');
 const acquire=async()=>({kind:'HomeStarter' as const,sourceIdentity:'synthetic',asOf:new Date().toISOString(),targetExcludedFromHistory:true as const,bytes:Buffer.from('{}')});
 const before=Date.now();const r=await collectPregameObservation(target,'HomeStarter',p,acquire);assert.ok(Date.parse(r.collectedAt)>=before);
 const original=readFileSync(p);await assert.rejects(()=>collectPregameObservation(target,'HomeStarter',p,acquire));assert.deepEqual(readFileSync(p),original);
 assert.throws(()=>loadPregameInputBundle([p],target));
});
