/** No result/grade access; compare current pregame files to the outcome-blind audit. */
import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {join} from 'node:path';import {execFileSync} from 'node:child_process';
import {officialInventory,digest} from '../src/lib/football/official-canonical-v1';
const repo=process.cwd(),batch=join(repo,'data/research/slate-batches/round-111-odds-new-v1'),out=join(batch,'canonicalization-v1');const registry=JSON.parse(readFileSync(join(out,'canonical-registry.json'),'utf8')),current=officialInventory(join(repo,'data/cache/research/football/forward-shadow-v1'));
assert.deepEqual(current.counts,registry.counts);for(const old of registry.rows){const now=current.rows.find(r=>r.fixtureId===old.fixtureId&&r.predictionId===old.predictionId&&r.root.replaceAll('\\','/').endsWith(old.root));assert(now);assert.equal(now.classification,old.classification);assert.equal(now.inputHash,old.inputHash);assert.equal(now.sealedAt,old.sealedAt);}
const forensic=JSON.parse(readFileSync(join(out,'duplicate-forensics.json'),'utf8'));for(const row of forensic.rows)for(const file of row.copies)assert.equal(digest(readFileSync(join(repo,file.path))),file.sha256);
const oldPreview='data/research/slate-batches/round-111-odds-new-v1/priority-readiness-v1/mandatory-previews-v4.json';assert(readFileSync(oldPreview).equals(execFileSync('git',['show','424cbb51dd8667cbf62b01509d2e7a6472346186:'+oldPreview])));
assert.equal(digest(readFileSync('src/lib/football/poisson-research-v1/index.ts','utf8').replaceAll('\r\n','\n')),'6efa82f916346599b5e9c6ee4ad768501f7a0d2254dc9d2376acd5df755aadbf');
const now=new Date().toISOString();assert(Date.parse(now)<Date.parse('2026-09-20T12:00:00.000Z'),'OBSERVATION_WINDOW_REQUIRES_RECHECK');
const audit={createdAt:now,status:'DUPLICATE_POLICY_READY_WAITING_FOR_WINDOW',counts:current.counts,pregameSealsPreserved:47,duplicateCopiesByteVerified:forensic.rows.reduce((n:number,r:any)=>n+r.copies.length,0),oldPreviewPreserved:true,canonicalPolicySha256:registry.policySha256,modelChanged:false,weightsChanged:false,thresholdsChanged:false,featureSetChanged:false,resultDataAccessed:false,liveDataAccessed:false,postgameDataAccessed:false,gradeDataAccessed:false,providerCalls:0,newPredictions:0,newPasses:0,v4:{gateMci:'READY',gateAtmRma:'READY',windowsExecuted:0,realEvidenceArtifacts:0,xiObservations:0,injuryObservations:0,playerStatsObservations:0,playerStatsPlan:'PAGE_1_ONLY',paginationComplete:false,playerStatsAdmission:'MORE_DATA_REQUIRED',A_ADMITTED:false,B_ADMITTED:false,C_ADMITTED:false,engineImplemented:false,shadowExecuted:false,nextWindowsKst:['2026-09-20T21:00:00+09:00','2026-09-20T22:15:00+09:00']},tests:{combinedPassed:102,additionalPassed:2,uniqueFocusedPassed:104,failed:0,typecheck:'PASS_ZERO_ERRORS'}};
writeFileSync(join(out,'execution-audit.json'),JSON.stringify(audit,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(audit,null,2));
