import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {join,resolve} from 'node:path';import {execFileSync} from 'node:child_process';
import {put,get} from '../src/lib/football/v4-prospective-evidence-v1/store';import {sha} from '../src/lib/football/v4-prospective-evidence-v1/contracts';import {readDecisionCoverage} from '../src/lib/research/terminal-decision';
async function main(){const repo=process.cwd(),batch=join(repo,'data/research/slate-batches/round-111-odds-new-v1'),out=join(batch,'priority-readiness-v1');const jobs=JSON.parse(readFileSync(join(out,'poll-job-index.json'),'utf8')).jobs;const gates=[];
 for(const job of jobs){const raw=execFileSync(process.execPath,['--import','tsx','scripts/run-football-v4-prospective-evidence-v1.ts','--date','2026-09-20','--batch','round-111-odds-new-v1','--manifest',job.manifest],{cwd:repo,encoding:'utf8'});const result=JSON.parse(raw);assert.equal(result.status,'PLAN_ONLY');assert.equal(result.gate.status,'READY');assert.equal(result.providerCalls,0);gates.push({manifest:job.manifest,result});}
 // Non-evidence namespace only. This is a storage capability probe, never a V4 observation.
 const store=resolve(repo,'../YANG-EDGE-INBOX/football-v4-prospective-evidence-v1/readiness-probes'),key=sha('round-111-priority-readiness-v1'),bytes=Buffer.from('LOCAL_STORAGE_CAPABILITY_PROBE_NOT_PREGAME_EVIDENCE');const created=await put(store,key,bytes);assert(['CREATED','IDEMPOTENT_REPLAY'].includes(created.status));assert.equal((await put(store,key,Buffer.from('conflict'))).status,'CONFLICT');assert((await get(store,key,sha(bytes))).equals(bytes));
 const coverage=['2026-09-20','2026-09-21'].map(date=>({date,...readDecisionCoverage(batch,date)}));assert(coverage.every(c=>c.INVALID_DECISION_COUNT===0&&c.DUPLICATE_TARGET_COUNT===0&&c.OUT_OF_SCOPE_DECISION_COUNT===0));
 const audit={createdAt:new Date().toISOString(),committedHead:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),status:'READY',gates,immutableStoreProbe:'PASS_NON_EVIDENCE_NAMESPACE',coverage,providerCalls:0,realCollectionExecuted:false,xiConfirmed:false,featuresAdmitted:0};writeFileSync(join(out,'committed-gate-audit.json'),JSON.stringify(audit,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({status:audit.status,jobs:gates.length,immutableStoreProbe:audit.immutableStoreProbe,coverage:coverage.map(c=>({date:c.date,predicted:c.SEALED_PREDICTION_COUNT,pass:c.SEALED_PASS_COUNT,pending:c.UNRESOLVED_COUNT,invalid:c.INVALID_DECISION_COUNT}))},null,2));}
main().catch(e=>{console.error(e instanceof Error?e.message:'GATE_FAILED');process.exitCode=1;});
