/** Local integrity audit only: never opens postgame evidence. */
import assert from 'node:assert/strict';import {readFileSync,writeFileSync,existsSync} from 'node:fs';import {join,resolve} from 'node:path';import {execFileSync} from 'node:child_process';
import {sha,readEnvelope} from '../src/lib/research/terminal-decision/evidence';import {committedBytes} from '../src/lib/research/terminal-decision/batch-selection';
const root=process.cwd(),batch=join(root,'data/research/slate-batches/round-111-odds-new-v1'),out=join(batch,'priority-readiness-v1');const read=(p:string)=>JSON.parse(readFileSync(join(out,p),'utf8'));
const old='production-bridge-v1/mandatory-previews-v3.json';assert(readFileSync(join(batch,old)).equals(committedBytes(batch,old)));
const next=join(out,'mandatory-previews-v4.json'),before=readFileSync(next);assert.throws(()=>writeFileSync(next,'invalid overwrite',{flag:'wx'}));assert(readFileSync(next).equals(before));
for(const p of read('mandatory-previews-v4.json')){assert.equal(p.previousVersionSha256,sha(readFileSync(join(batch,old))));const original=readEnvelope(join(batch,'production-bridge-v1/prediction-evidence',String(p.providerFixtureId),'snapshot.json'));for(const k of ['pHome','pDraw','pAway','predictedClass','modelVersion','predictionCreatedAt'])assert.equal(p.OFFICIAL_V1[k],original.payload[k]);assert.equal(p.OFFICIAL_V1.predictionId,original.sha256);}
const registry=read('player-registry.json');for(const r of read('membership-receipts.json')){const rawBytes=readFileSync(join(root,'data/cache/research/round-111-priority-identity/membership-v1',`${r.teamId}-${r.sourceSha256}.json`),'utf8').trimEnd();assert.equal(sha(rawBytes),r.sourceSha256);const raw=JSON.parse(rawBytes);assert.equal(String(raw.response[0].team.id),r.teamId);const ids=new Set(raw.response[0].players.map((p:any)=>p.id));assert.equal(ids.size,r.players.length);for(const player of r.players){assert(ids.has(player.id));const record=registry.find((v:any)=>v.teamProviderId===r.teamId&&v.providerPlayerId===String(player.id));assert(record);assert.equal(record.validFrom,r.observedAt);assert.equal(record.recordedAt,r.collectedAt);}}
const manifest=JSON.parse(readFileSync(join(batch,'production-bridge-v1/terminal-evidence-manifest.json'),'utf8'));for(const ref of manifest.references)for(const f of ref.files)assert.equal(sha(readFileSync(join(batch,'production-bridge-v1',f.path))),f.sha256);
const modelPath='src/lib/football/poisson-research-v1/index.ts';assert.equal(sha(readFileSync(modelPath,'utf8').replaceAll('\r\n','\n')),'6efa82f916346599b5e9c6ee4ad768501f7a0d2254dc9d2376acd5df755aadbf');
const index=read('poll-job-index.json');assert.equal(index.jobs.length,14);assert(index.jobs.length<=index.dailyFrozenBudget);assert.equal(new Set(index.jobs.map((j:any)=>j.manifest)).size,14);
console.log(JSON.stringify({status:'PASS',checks:['prior_preview_bytes_unchanged','preview_append_only','sealed_values_exact','raw_membership_hashes','exact_id_and_timestamp_bindings','prior_predictions_unchanged','frozen_model_hash','poll_budget_14_of_16'],modelHash:'6efa82f916346599b5e9c6ee4ad768501f7a0d2254dc9d2376acd5df755aadbf',targetResultsAccessed:false,providerCalls:0}));
