import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
import {bindObservedCutoff,validateTarget,historyReasons,rateGate,predictSafely,order,type Target,type Match,type Prediction} from './frozen/scripts/football-v3-feature-research-v1/contracts-v1';
import {featureState,type FeatureRecord} from './frozen/scripts/football-v3-feature-research-v1/feature-state-v1';
import {fitRates,predictRates} from './frozen/scripts/football-poisson-v2-draw-research/evaluation-v1/h2-ridge-rates-v1';
import {joint} from './frozen/scripts/football-poisson-v2-draw-research/evaluation-v1/numerics-v1';
import {digest,requireRule,readSeal,validateObservation,type Observation,type Feature} from './store-v1';
export const MAP_HASH='244c2ef4f930855271744e39f0de44598ec6c929ac18edd4c6f72965eb8a4a26',BETA_HASH='dc8f9faa4a09429ddfdd46631502375540e25fdbb37f84a1f92f6ceeb21e2ab4';
export type Parameters={leagueId:number;map:number[][];beta:number[];mapHash:string;betaHash:string};
export function loadParameters(){const root=fileURLToPath(new URL('../../',import.meta.url)),s=readSeal<{finals:{leagueId:number;candidate:string;mapParameters:number[][];mapParameterHash:string;beta:{parameters:number[]};betaHash:string}[]}>(join(root,'data/audits/football-v31-development-v1.json'));requireRule(s.sha256==='e28bc95c8b4b7d99dc967bfcad8cad76d152e1d96ba8946af6621e03fccc2e80','FINAL_PARAMETER_SEAL');const rows=[39,140,135,78].map(l=>{const f=s.payload.finals.find(x=>x.leagueId===l&&x.candidate==='V31-R1')!;requireRule(digest(f.mapParameters)===f.mapParameterHash&&digest(f.beta.parameters)===f.betaHash,'PARAMETER_HASH');return {leagueId:l,map:f.mapParameters,beta:f.beta.parameters,mapHash:f.mapParameterHash,betaHash:f.betaHash};});requireRule(digest(rows.map(r=>({leagueId:r.leagueId,parameterHash:r.mapHash})))===MAP_HASH,'MAP_HASH');requireRule(digest(rows.map(r=>({leagueId:r.leagueId,parameterHash:r.betaHash})))===BETA_HASH,'BETA_HASH');return rows;}
export function targetGate(t:Target,cutoff:string,createdAt:string){validateTarget(t);requireRule(t.season===2026,'WARMUP_CANNOT_BE_TARGET');requireRule(Number.isFinite(Date.parse(cutoff))&&Number.isFinite(Date.parse(createdAt))&&Date.parse(cutoff)<=Date.parse(createdAt)&&Date.parse(createdAt)<Date.parse(t.kickoffUtc),'PREGAME_TIME');}
export function select(t:Target,cutoffAt:string,createdAt:string,observations:Observation[]){targetGate(t,cutoffAt,createdAt);const cutoff=Date.parse(cutoffAt),byId=new Map<number,Observation[]>(),excluded:{fixtureId:number;reason:string}[]=[];
 for(const o of observations){validateObservation(o);requireRule(o.fixture.fixtureId!==t.fixtureId,'TARGET_OWN_DATA');const f=o.fixture;let reason='';if(f.leagueId!==t.leagueId)reason='CROSS_LEAGUE';else if(Date.parse(f.kickoffUtc)>=cutoff||Date.parse(f.kickoffUtc)>=Date.parse(t.kickoffUtc))reason='FUTURE_OR_SAME_KICKOFF';else if(Date.parse(f.kickoffUtc)<cutoff-365*86400000)reason='OUTSIDE_365D';else if(Date.parse(o.providerFetchedAt)>cutoff||Date.parse(o.sealCreatedAt)>cutoff||Date.parse(o.completion.providerFetchedAt)>cutoff)reason='NOT_OBSERVED_AND_STORED_AT_CUTOFF';if(reason){excluded.push({fixtureId:f.fixtureId,reason});continue;}const rows=byId.get(f.fixtureId)??[];rows.push(o);byId.set(f.fixtureId,rows);}
 const selected:Observation[]=[];for(const [fixtureId,rows]of byId){requireRule(new Set(rows.map(r=>digest(r.fixture))).size===1,'FIXTURE_IDENTITY_CONFLICT');const latest=Math.max(...rows.map(r=>Date.parse(r.providerFetchedAt))),same=rows.filter(r=>Date.parse(r.providerFetchedAt)===latest);if(new Set(same.map(r=>digest({raw:r.rawResponseSha256,features:r.features,presence:r.presence,quality:r.quality,completion:r.completion}))).size>1){excluded.push({fixtureId,reason:'UNKNOWN_SAME_TIME_CONFLICT'});continue;}same.sort((a,b)=>a.sealCreatedAt.localeCompare(b.sealCreatedAt)||a.observationId.localeCompare(b.observationId));selected.push(same[0]);}
 selected.sort((a,b)=>a.fixture.kickoffUtc.localeCompare(b.fixture.kickoffUtc)||a.fixture.fixtureId-b.fixture.fixtureId);
 const counts=Object.fromEntries([['home',t.homeTeamId],['away',t.awayTeamId]].map(([side,id])=>[side,Object.fromEntries((['xG','shots','sot'] as Feature[]).map(f=>[f,selected.filter(o=>(o.fixture.homeTeamId===id||o.fixture.awayTeamId===id)&&!['API_ERROR','IDENTITY_INVALID'].includes(o.quality)&&o.features[f]!==null).length]))])) as Record<'home'|'away',Record<Feature,number>>;
 const sufficient=Object.values(counts).every(c=>Object.values(c).every(n=>n>=5));return {selected,excluded,counts,sufficient,status:sufficient?'ELIGIBLE':'PASS_INSUFFICIENT_OBSERVED_FEATURE_HISTORY'};
}
/** Numeric kernel uses unchanged ordered equations. It never reads files, providers or evaluation metrics. */
export function kernel(t:Target,cutoffAt:string,base:Match[],features:FeatureRecord[],p:Parameters):Prediction{requireRule(t.season===2026,'WARMUP_CANNOT_BE_TARGET');requireRule(p.leagueId===t.leagueId&&digest(p.map)===p.mapHash&&digest(p.beta)===p.betaHash,'PARAMETER_MUTATION');bindObservedCutoff(t,Date.parse(cutoffAt));return predictSafely(()=>{const reasons=historyReasons(t,base);requireRule(!reasons.length,reasons.join('|'),'PASS');const fit=fitRates(base);if(fit.status!=='FITTED')requireRule(false,fit.reasons.join('|'),fit.status);const offset=predictRates(fit.parameters,t,base),state=featureState('F3',t,features);const project=(z:number[])=>[((z[0]+z[2])+z[4])/3,((z[1]+z[3])+z[5])/3];const q=[project(state.home),project(state.away)],h=[[1,Math.log(offset[0]),Math.log(offset[1])],[1,Math.log(offset[1]),Math.log(offset[0])]];const x=q.map((v,s)=>p.map.map((col,j)=>{let dot=0;for(let i=0;i<3;i++)dot+=h[s][i]*col[i];return v[j]-dot;}));const contribution=x.map(v=>p.beta[0]*v[0]+p.beta[1]*v[1]),rates=contribution.map((v,s)=>Math.exp(Math.log(offset[s])+v)) as [number,number];rateGate(...rates);return {p:joint(...rates).p,rates,details:{q,h,x,offset,contribution,h2InputHash:digest(base),h2ParameterHash:digest(fit.parameters),featureInputHash:digest(features),mapHash:p.mapHash,betaHash:p.betaHash}};});}
export function predict(t:Target,cutoffAt:string,createdAt:string,observations:Observation[]){const census=select(t,cutoffAt,createdAt,observations);if(!census.sufficient)return {prediction:{status:'PASS',reasons:['PASS_INSUFFICIENT_OBSERVED_FEATURE_HISTORY'],p:null,rates:null,details:{counts:census.counts}} as Prediction,census};const base=order(census.selected.map(o=>({...o.fixture,homeGoals:o.completion.homeGoals,awayGoals:o.completion.awayGoals}))),features=census.selected.map(o=>({target:o.fixture,values:['API_ERROR','IDENTITY_INVALID'].includes(o.quality)?{xG:null,shots:null,sot:null}:o.features,sourceHash:o.rawResponseSha256,providerFetchedAt:o.providerFetchedAt}));return {prediction:kernel(t,cutoffAt,base,features,loadParameters().find(p=>p.leagueId===t.leagueId)!),census};}
