const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'../..'),hash=s=>crypto.createHash('sha256').update(s).digest('hex');
function expected(){const out={};function visit(p){if(out[p])return;const original=fs.readFileSync(path.join(root,p),'utf8').replaceAll('\r\n','\n');let text=original;
 if(p.endsWith('/evaluation-v1/contracts-evaluation-v1.ts')){text=text.replace('[2023,2024].includes(t.season)','[2023,2024,2025,2026].includes(t.season)').replaceAll('const cutoff=Date.parse(t.kickoffUtc)-1','const cutoff=observedCutoff(t)').replaceAll('Date.parse(r.kickoffUtc)+2*DAY<cutoff','Date.parse(r.kickoffUtc)<cutoff');text+='\nconst cutoffs=new WeakMap<Target,number>();\nexport function bindObservedCutoff(t:Target,cutoff:number){validateTarget(t);requireRule(Number.isFinite(cutoff)&&cutoff<Date.parse(t.kickoffUtc),"INVALID_CUTOFF");cutoffs.set(t,cutoff);}\nexport function observedCutoff(t:Target){const c=cutoffs.get(t);requireRule(c!==undefined,"OBSERVATION_SELECTOR_REQUIRED");return c;}\n';}
 if(p==='scripts/football-v3-feature-research-v1/contracts-v1.ts'){text=text.replace('{validateTarget,validateHistory,order,DAY,requireRule,','{observedCutoff,validateTarget,validateHistory,order,DAY,requireRule,').replace('const cutoff=Date.parse(target.kickoffUtc)-1','const cutoff=observedCutoff(target)').replaceAll('Date.parse(r.kickoffUtc)+2*DAY<cutoff','Date.parse(r.kickoffUtc)<cutoff');}
 out[p]={originalHash:hash(original),copyHash:hash(text),text};for(const m of original.matchAll(/(?:from\s*|import\s*)['"](\.[^'"]+)['"]/g)){let q=path.posix.normalize(path.posix.join(path.posix.dirname(p),m[1]));if(!q.endsWith('.ts'))q+='.ts';visit(q);}}
 ['scripts/football-v3-feature-research-v1/feature-state-v1.ts','scripts/football-poisson-v2-draw-research/evaluation-v1/h2-ridge-rates-v1.ts','scripts/football-poisson-v2-draw-research/evaluation-v1/numerics-v1.ts'].forEach(visit);return out;}
function verify(write=false){const out=expected();for(const [p,r]of Object.entries(out)){const dest=path.join(__dirname,'frozen',p);if(write){fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,r.text,{flag:'wx'});}else if(fs.readFileSync(dest,'utf8').replaceAll('\r\n','\n')!==r.text)throw Error('MATH_SOURCE_CHANGED:'+p);}return Object.fromEntries(Object.entries(out).map(([p,{text,...r}])=>[p,r]));}
module.exports={verify};if(require.main===module)console.log(JSON.stringify(verify(process.argv.includes('--create'))));
