/** Foundation intake/census only. No prediction, metric, fitting or grading imports. */
import {readFileSync,writeFileSync,mkdirSync,existsSync,readdirSync} from 'node:fs';
import {join,resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {append,list,parse,storeRoot,sha,digest,readSeal,writeSeal,requireRule,type Observation} from './store-v1';
import {select,loadParameters} from './adapter-v1';
import {type Target} from './frozen/scripts/football-v3-feature-research-v1/contracts-v1';
const root=fileURLToPath(new URL('../../',import.meta.url));
export const localRoot=resolve(root,'../YANG-EDGE-INBOX/football-v31-r1-prospective-shadow-v1');
type RawFixture={fixture:{id:number;date:string;status:{short:string}};league:{id:number;season:number;round:string};teams:{home:{id:number};away:{id:number}};score:{fulltime:{home:number;away:number}}};
type Receipt={providerFetchedAt:string;sourceHash:string;endpoint:string;httpStatus?:number};
type Meta={fixtures:{fixtureId:number;leagueId:number;season:number;kickoffUtc:string;homeTeamId:number;awayTeamId:number;round:string;status:string}[];featureRecords:({fixtureId:number;leagueId:number}&Receipt)[];leagues:{leagueId:number;source:Receipt}[];provenance:{localRunDirectory:string}};
type Probe={requests:Receipt[];inventories:{leagueId:number;season:number;provenance:Receipt}[]};
type Prior={fixture:Target;round:string;completion:Observation['completion']};
function raw(p:string,hash:string){const b=readFileSync(p);requireRule(sha(b)===hash,'ORIGINAL_RAW_HASH');return JSON.parse(b.toString('utf8'));}
export function identity(r:RawFixture,league:number,season:number,fetched:string,hash:string):Prior{requireRule(r.league.id===league&&r.league.season===season&&r.fixture.status.short==='FT'&&/^Regular Season - [1-9][0-9]*$/.test(r.league.round),'RAW_IDENTITY_STAGE');return {fixture:{fixtureId:r.fixture.id,leagueId:league,season,kickoffUtc:new Date(r.fixture.date).toISOString(),homeTeamId:r.teams.home.id,awayTeamId:r.teams.away.id},round:r.league.round,completion:{providerFetchedAt:fetched,rawHash:hash,homeGoals:r.score.fulltime.home,awayGoals:r.score.fulltime.away}};}
export function ingest(rootDir:string,prior:Prior,receipt:Receipt,file:string){const b=raw(file,receipt.sourceHash);let parsed:ReturnType<typeof parse>,quality:Observation['quality'];try{requireRule((receipt.httpStatus??200)===200,'API_ERROR');parsed=parse(b,prior.fixture);quality=Object.values(parsed.features).every(v=>v!==null)?'VALID':'MISSING_FEATURE';}catch(e){parsed={features:{xG:null,shots:null,sot:null},presence:{xG:['UNKNOWN','UNKNOWN'],shots:['UNKNOWN','UNKNOWN'],sot:['UNKNOWN','UNKNOWN']}};quality=String(e).includes('IDENTITY')?'IDENTITY_INVALID':'API_ERROR';}return append(rootDir,{...prior,fixtureStatus:'FT',providerFetchedAt:receipt.providerFetchedAt,...parsed,rawPath:file,rawResponseSha256:receipt.sourceHash,endpoint:receipt.endpoint,quality});}
export async function collectMissing(rootDir:string,priors:Prior[],key:string,request:typeof fetch=fetch){requireRule(key.length>0,'MISSING_API_KEY');const existing=new Set(list(rootDir).map(o=>o.payload.fixture.fixtureId)),results:{fixtureId:number;action:string;quality:string}[]=[];let calls=0;for(const p of priors){if(existing.has(p.fixture.fixtureId)){results.push({fixtureId:p.fixture.fixtureId,action:'ALREADY_OBSERVED',quality:'PRESERVED'});continue;}requireRule(p.fixture.season===2026,'COLLECTOR_SEASON');const endpoint='/fixtures/statistics?fixture='+p.fixture.fixtureId;let bytes:string,httpStatus:number;try{const response=await request('https://v3.football.api-sports.io'+endpoint,{headers:{'x-apisports-key':key},redirect:'error',signal:AbortSignal.timeout(30000)});httpStatus=response.status;bytes=await response.text();}catch{httpStatus=0;bytes=JSON.stringify({errors:{transport:'REQUEST_FAILED'},response:[]});}calls++;const providerFetchedAt=new Date().toISOString();let validJson=true;try{JSON.parse(bytes);}catch{validJson=false;}const file=join(storeRoot(rootDir),'raw',sha(bytes)+'.json');mkdirSync(dirname(file),{recursive:true});if(!existsSync(file))writeFileSync(file,bytes,{flag:'wx'});let r;if(validJson)r=ingest(rootDir,p,{endpoint,providerFetchedAt,sourceHash:sha(bytes),httpStatus},file);else r=append(rootDir,{...p,fixtureStatus:'FT',providerFetchedAt,rawPath:file,rawResponseSha256:sha(bytes),endpoint,quality:'API_ERROR',features:{xG:null,shots:null,sot:null},presence:{xG:['UNKNOWN','UNKNOWN'],shots:['UNKNOWN','UNKNOWN'],sot:['UNKNOWN','UNKNOWN']}});results.push({fixtureId:p.fixture.fixtureId,action:'NEWLY_OBSERVED',quality:r.payload.quality});if(calls%10===0)console.log(JSON.stringify({stage:'CURRENT_COLLECTION',calls}));await new Promise(r=>setTimeout(r,250));}return {calls,results};}
export async function prepare(key:string){loadParameters();const runDir=join(storeRoot(localRoot),'foundation');writeSeal(join(runDir,'STARTED.json'),{createdAt:new Date().toISOString(),shadowExecution:false});const existing=list(localRoot),known=new Set(existing.map(r=>r.payload.fixture.fixtureId+':'+r.payload.providerFetchedAt+':'+r.payload.rawResponseSha256));let imported=0;
 const metadata=readSeal<Meta>(join(root,'data/audits/football-v3-2025-independent-holdout-cohort-seal-v1.json'));requireRule(metadata.sha256==='7924420956e419af1a7f14b8b2eb520cc55d37b46534736d35b0fbdcf51c2581','WARMUP_METADATA');
 const priors=new Map<number,Prior>();for(const l of metadata.payload.leagues){const body=raw(join(metadata.payload.provenance.localRunDirectory,'fixtures-'+l.leagueId+'.raw.json'),l.source.sourceHash);for(const r of body.response as RawFixture[]){if(!/^Regular Season - [1-9][0-9]*$/.test(r.league.round))continue;const p=identity(r,l.leagueId,2025,l.source.providerFetchedAt,l.source.sourceHash),m=metadata.payload.fixtures.find(x=>x.fixtureId===p.fixture.fixtureId);requireRule(m&&m.leagueId===p.fixture.leagueId&&m.homeTeamId===p.fixture.homeTeamId&&m.awayTeamId===p.fixture.awayTeamId&&new Date(m.kickoffUtc).toISOString()===p.fixture.kickoffUtc,'WARMUP_IDENTITY');priors.set(p.fixture.fixtureId,p);}}
 for(const r of metadata.payload.featureRecords){const p=priors.get(r.fixtureId);requireRule(p&&p.fixture.leagueId===r.leagueId,'FEATURE_IDENTITY');if(!known.has(r.fixtureId+':'+r.providerFetchedAt+':'+r.sourceHash)){ingest(localRoot,p,r,join(metadata.payload.provenance.localRunDirectory,'statistics-'+r.fixtureId+'.raw.json'));imported++;}}
 const gate=readSeal<{providerProbe:{localReportPath:string;localReportSha256:string};sampleEvidence:({fixtureId:number;season:number;provenance:Receipt})[]}>(join(root,'docs/FOOTBALL_V3_FEATURE_DATA_ACCESS_GATE_V1.json'));requireRule(gate.sha256==='37aef3e80f6559fcc0c272e99ed0dfef8c187aaa809475744ec4d66b195d82e5','CURRENT_GATE');const probe=raw(gate.payload.providerProbe.localReportPath,gate.payload.providerProbe.localReportSha256) as Probe;
 const locate=(r:Receipt)=>{const i=probe.requests.findIndex(x=>x.endpoint===r.endpoint&&x.providerFetchedAt===r.providerFetchedAt&&x.sourceHash===r.sourceHash);requireRule(i>=0,'RECEIPT_NOT_FOUND');return join(dirname(gate.payload.providerProbe.localReportPath),'response-'+String(i+1).padStart(3,'0')+'.json');};
 const current:Prior[]=[];for(const l of probe.inventories.filter(l=>l.season===2026)){const body=raw(locate(l.provenance),l.provenance.sourceHash);for(const r of body.response as RawFixture[])if(r.fixture.status.short==='FT'&&/^Regular Season - [1-9][0-9]*$/.test(r.league.round))current.push(identity(r,l.leagueId,2026,l.provenance.providerFetchedAt,l.provenance.sourceHash));}
 for(const r of gate.payload.sampleEvidence.filter(x=>x.season===2026)){const p=current.find(p=>p.fixture.fixtureId===r.fixtureId)!;if(!known.has(r.fixtureId+':'+r.provenance.providerFetchedAt+':'+r.provenance.sourceHash)){ingest(localRoot,p,r.provenance,locate(r.provenance));imported++;}}
 const census=readSeal<{localReportPath:string;currentRechecks:({fixtureId:number}&Receipt)[]}>(join(root,'data/audits/football-v3-historical-feature-coverage-census-v1.json'));requireRule(census.sha256==='0f215fba91a68cdd0a4a53b5124a311f193821baddd2ff1764d8942cb8718c41','CENSUS_HASH');for(const r of census.payload.currentRechecks){if(!known.has(r.fixtureId+':'+r.providerFetchedAt+':'+r.sourceHash)){ingest(localRoot,current.find(p=>p.fixture.fixtureId===r.fixtureId)!,r,join(dirname(census.payload.localReportPath),'current-'+r.fixtureId+'.raw.json'));imported++;}}
 requireRule(current.length===122,'STORED_CURRENT_COHORT');const collection=await collectMissing(localRoot,current,key),observations=list(localRoot),cutoffAt=new Date().toISOString();const fixtureRoot=join(root,'data/cache/research/football/forward-shadow-v1/MODEL_FORWARD/fixtures');const targets=readdirSync(fixtureRoot).flatMap(id=>{const p=join(fixtureRoot,id,'snapshot.json');if(!existsSync(p))return [];const s=readSeal<{fixtureId:number;leagueId:number;season:number;kickoffUtc:string;homeTeam:{id:number};awayTeam:{id:number}}>(p).payload;return s.season===2026&&Date.parse(s.kickoffUtc)>Date.parse(cutoffAt)+60000?[{fixtureId:s.fixtureId,leagueId:s.leagueId,season:s.season,kickoffUtc:s.kickoffUtc,homeTeamId:s.homeTeam.id,awayTeamId:s.awayTeam.id}]:[];});
 const targetCensus=targets.map(t=>{const selected=select(t,cutoffAt,cutoffAt,observations.map(o=>o.payload)),warm=selected.selected.filter(o=>o.fixture.season===2025);return {target:t,cutoffAt,warmupEligibleFixtures:warm.length,requiredFeatureCompleteWarmupFixtures:warm.filter(o=>Object.values(o.features).every(v=>v!==null)&&o.quality==='VALID').length,counts:selected.counts,baseCounts:{competition:selected.selected.length,homeVenue:selected.selected.filter(o=>o.fixture.homeTeamId===t.homeTeamId).length,awayVenue:selected.selected.filter(o=>o.fixture.awayTeamId===t.awayTeamId).length},historyEligible:selected.sufficient&&selected.selected.length>=30&&selected.selected.filter(o=>o.fixture.homeTeamId===t.homeTeamId).length>=5&&selected.selected.filter(o=>o.fixture.awayTeamId===t.awayTeamId).length>=5,selectedObservationHashes:selected.selected.map(digest)};});
 const perLeague=[39,140,135,78].map(leagueId=>{const t=targets.filter(t=>t.leagueId===leagueId).sort((a,b)=>a.kickoffUtc.localeCompare(b.kickoffUtc))[0];if(!t)return {leagueId,target:null};const selected=select(t,cutoffAt,cutoffAt,observations.map(o=>o.payload)).selected.filter(o=>o.fixture.season===2025),teams=[...new Set(selected.flatMap(o=>[o.fixture.homeTeamId,o.fixture.awayTeamId]))];const counts=teams.map(teamId=>({teamId,...Object.fromEntries((['xG','shots','sot'] as const).map(f=>[f,selected.filter(o=>(o.fixture.homeTeamId===teamId||o.fixture.awayTeamId===teamId)&&o.features[f]!==null&&o.quality==='VALID').length]))})) as {teamId:number;xG:number;shots:number;sot:number}[];return {leagueId,target:t,cutoffAt,eligiblePriorFixtures:selected.length,completePriorFixtures:selected.filter(o=>o.quality==='VALID').length,teamsWith5Xg:counts.filter(c=>c.xG>=5).length,teamsWith5Shots:counts.filter(c=>c.shots>=5).length,teamsWith5Sot:counts.filter(c=>c.sot>=5).length,teamsAllRequired:counts.filter(c=>c.xG>=5&&c.shots>=5&&c.sot>=5).length};});
 const latest=current.map(p=>observations.filter(o=>o.payload.fixture.fixtureId===p.fixture.fixtureId).sort((a,b)=>a.payload.providerFetchedAt.localeCompare(b.payload.providerFetchedAt)).at(-1)!.payload);const result={createdAt:new Date().toISOString(),imported,observationRecords:observations.length,observationRegistryHash:digest(observations.map(s=>({observationId:s.payload.observationId,hash:s.sha256}))),collection,perLeague,targetCensus,current:{total:latest.length,xGComplete:latest.filter(o=>o.features.xG!==null).length,shotsComplete:latest.filter(o=>o.features.shots!==null).length,sotComplete:latest.filter(o=>o.features.sot!==null).length},shadowExecuted:false,metricsComputed:false,role:'PROSPECTIVE_INPUT_HISTORY_ONLY'};writeSeal(join(runDir,'READY_CENSUS.json'),result);console.log(JSON.stringify({current:result.current,perLeague,targets:targetCensus.length,historyEligibleTargets:targetCensus.filter(t=>t.historyEligible).length,apiCalls:collection.calls,shadowExecuted:false}));return result;
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){requireRule(process.argv[2]==='--prepare','EXPLICIT_PREPARE_ONLY');prepare(process.env.FOOTBALL_API_KEY??'').catch(e=>{console.error(String(e));process.exitCode=1;});}
