import {join} from 'node:path';
import {exactKeys,validProb,argmax,actual,type Target,type Prediction} from './frozen/scripts/football-v3-feature-research-v1/contracts-v1';
import {targetGate,MAP_HASH,BETA_HASH} from './adapter-v1';
import {storeRoot,NAMESPACE,writeSeal,readSeal,requireRule,digest,type Observation} from './store-v1';
export type Snapshot={namespace:typeof NAMESPACE;fixture:Target;predictionCreatedAt:string;cutoffAt:string;sealedAt:string;prediction:Prediction;predictedClass:string|null;inputFixtureIds:number[];observationIds:string[];observationHashes:string[];featureSampleCounts:unknown;h2Provenance:unknown;adapterHash:string;mapHash:string;betaHash:string;inputHash:string;officialForwardReference:{fixtureId:number;snapshotHash:string}|null};
export function validateSnapshot(s:Snapshot){exactKeys(s,['namespace','fixture','predictionCreatedAt','cutoffAt','sealedAt','prediction','predictedClass','inputFixtureIds','observationIds','observationHashes','featureSampleCounts','h2Provenance','adapterHash','mapHash','betaHash','inputHash','officialForwardReference']);requireRule(s.namespace===NAMESPACE,'NAMESPACE');targetGate(s.fixture,s.cutoffAt,s.predictionCreatedAt);requireRule(Date.parse(s.sealedAt)>=Date.parse(s.predictionCreatedAt)&&Date.parse(s.fixture.kickoffUtc)-Date.parse(s.sealedAt)>=60000,'SEAL_DEADLINE');requireRule(s.mapHash===MAP_HASH&&s.betaHash===BETA_HASH,'FROZEN_PARAMETERS');for(const h of [s.adapterHash,s.inputHash,...s.observationHashes])requireRule(/^[a-f0-9]{64}$/.test(h),'HASH');requireRule(s.observationIds.length===s.observationHashes.length&&s.inputFixtureIds.length===s.observationIds.length&&new Set(s.inputFixtureIds).size===s.inputFixtureIds.length&&!s.inputFixtureIds.includes(s.fixture.fixtureId),'INPUT_IDENTITY');exactKeys(s.prediction,['status','reasons','p','rates','details']);requireRule(['PREDICTED','PASS'].includes(s.prediction.status),'UNSEALABLE_STATUS');if(s.prediction.status==='PREDICTED'){requireRule(s.prediction.p,'PROBABILITY');validProb(s.prediction.p);requireRule(s.predictedClass===['HOME','DRAW','AWAY'][argmax(s.prediction.p)],'CLASS');}else requireRule(s.prediction.p===null&&s.prediction.rates===null&&s.predictedClass===null&&s.prediction.reasons.length>0,'PASS_PRESERVATION');if(s.officialForwardReference)requireRule(s.officialForwardReference.fixtureId===s.fixture.fixtureId&&/^[a-f0-9]{64}$/.test(s.officialForwardReference.snapshotHash),'OFFICIAL_REFERENCE');}
export function sealPregame(root:string,s:Snapshot,observations:Observation[]){validateSnapshot(s);requireRule(digest(observations)===s.inputHash,'INPUT_HASH');requireRule(digest(observations.map(o=>o.fixture.fixtureId))===digest(s.inputFixtureIds)&&digest(observations.map(o=>o.observationId))===digest(s.observationIds)&&digest(observations.map(digest))===digest(s.observationHashes),'INPUT_LINK');for(const o of observations)requireRule(Date.parse(o.providerFetchedAt)<=Date.parse(s.cutoffAt)&&Date.parse(o.sealCreatedAt)<=Date.parse(s.cutoffAt),'OBSERVATION_AFTER_CUTOFF');const dir=join(storeRoot(root),'fixtures',String(s.fixture.fixtureId));writeSeal(join(dir,'input.json'),observations);return writeSeal(join(dir,'snapshot.json'),s);}
export type Grade={fixtureId:number;predictionHash:string;actualScore:{home:number;away:number};actualClass:string;correct1X2:boolean|null;gradedAt:string;providerFetchedAt:string;sourceHash:string;fixtureStatus:'FT';revision:number;previousHash:string|null;revisionReason:string};
export function appendGrade(root:string,g:Grade){exactKeys(g,['fixtureId','predictionHash','actualScore','actualClass','correct1X2','gradedAt','providerFetchedAt','sourceHash','fixtureStatus','revision','previousHash','revisionReason']);const dir=join(storeRoot(root),'fixtures',String(g.fixtureId)),snapshot=readSeal<Snapshot>(join(dir,'snapshot.json'));validateSnapshot(snapshot.payload);requireRule(snapshot.sha256===g.predictionHash,'PREDICTION_HASH');requireRule(g.fixtureStatus==='FT'&&Date.parse(g.providerFetchedAt)>Date.parse(snapshot.payload.fixture.kickoffUtc)&&Date.parse(g.providerFetchedAt)>Date.parse(snapshot.payload.sealedAt)&&Date.parse(g.gradedAt)>=Date.parse(g.providerFetchedAt),'POSTGAME_ONLY');requireRule(/^[a-f0-9]{64}$/.test(g.sourceHash)&&g.revisionReason.length>0,'GRADE_PROVENANCE');exactKeys(g.actualScore,['home','away']);for(const n of Object.values(g.actualScore))requireRule(Number.isSafeInteger(n)&&n>=0,'SCORE');const label=['HOME','DRAW','AWAY'][actual(g.actualScore.home,g.actualScore.away)];requireRule(g.actualClass===label&&g.correct1X2===(snapshot.payload.prediction.status==='PASS'?null:snapshot.payload.predictedClass===label),'GRADE_RESULT');requireRule(Number.isSafeInteger(g.revision)&&g.revision>=1,'REVISION');if(g.revision===1)requireRule(g.previousHash===null,'REVISION');else requireRule(readSeal<Grade>(join(dir,'grades',String(g.revision-1)+'.json')).sha256===g.previousHash,'REVISION_CHAIN');return writeSeal(join(dir,'grades',String(g.revision)+'.json'),g);}
