import {readFileSync,mkdirSync,openSync,writeFileSync,closeSync,fsyncSync,readdirSync,existsSync,realpathSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import {digest,sha,requireRule,exactKeys,validateTarget,type Target} from './frozen/scripts/football-v3-feature-research-v1/contracts-v1';
export {digest,sha,requireRule};
export const NAMESPACE='V31_R1_PROSPECTIVE_SHADOW';
export const TYPES={xG:'expected_goals',shots:'Total Shots',sot:'Shots on Goal'} as const;
export type Feature=keyof typeof TYPES;
export type Observation={observationId:string;namespace:typeof NAMESPACE;fixture:Target;round:string;fixtureStatus:'FT';providerFetchedAt:string;sealCreatedAt:string;features:Record<Feature,[number,number]|null>;presence:Record<Feature,[string,string]>;rawResponseSha256:string;rawPath:string;endpoint:string;collectorVersion:string;completion:{providerFetchedAt:string;rawHash:string;homeGoals:number;awayGoals:number};quality:'VALID'|'MISSING_FEATURE'|'API_ERROR'|'IDENTITY_INVALID';role:'PROSPECTIVE_INPUT_HISTORY_ONLY'};
export function storeRoot(root:string){const parts=resolve(root).split(/[\\/]/);requireRule(parts.at(-1)==='football-v31-r1-prospective-shadow-v1'&&!parts.some(p=>['MODEL_FORWARD','OWNER_MANUAL_SHADOW','EXTERNAL_ANALYSIS_SHADOW'].includes(p)),'PRIVATE_NAMESPACE_REQUIRED');return join(resolve(root),NAMESPACE);}
export function readSeal<T>(file:string){const r=JSON.parse(readFileSync(file,'utf8')) as {payload:T;sha256:string};requireRule(digest(r.payload)===r.sha256,'SEAL_HASH');return r;}
export function writeSeal<T>(file:string,payload:T){mkdirSync(resolve(file,'..'),{recursive:true});const s={payload,sha256:digest(payload)},fd=openSync(file,'wx');try{writeFileSync(fd,JSON.stringify(s,null,2)+'\n');fsyncSync(fd);}finally{closeSync(fd);}return s;}
export function parse(body:unknown,t:Target){validateTarget(t);const b=body as {errors?:object;response?:{team?:{id:number};statistics?:{type:string;value:unknown}[]}[]};requireRule(b&&Object.keys(b.errors??{}).length===0&&Array.isArray(b.response),'API_ERROR');const ids=[t.homeTeamId,t.awayTeamId];requireRule(b.response.length<=2&&new Set(b.response.map(r=>r.team?.id)).size===b.response.length&&b.response.every(r=>ids.includes(r.team?.id??-1)),'IDENTITY_INVALID');
 const features={} as Observation['features'],presence={} as Observation['presence'];for(const f of Object.keys(TYPES) as Feature[]){const values=ids.map(id=>{const r=b.response!.find(r=>r.team?.id===id);if(!r)return {state:'ABSENT',value:null};requireRule(Array.isArray(r.statistics),'IDENTITY_INVALID');const rows=r.statistics!.filter(x=>x.type===TYPES[f]);requireRule(rows.length<=1,'IDENTITY_INVALID');if(!rows.length)return {state:'ABSENT',value:null};if(rows[0].value===null)return {state:'NULL',value:null};const v=rows[0].value;requireRule((typeof v==='number'||typeof v==='string'&&/^\d+(\.\d+)?$/.test(v.trim()))&&Number.isFinite(Number(v))&&Number(v)>=0&&(f==='xG'||Number.isInteger(Number(v))),'INVALID_VALUE');return {state:'VALUE',value:Number(v)};});presence[f]=values.map(v=>v.state) as [string,string];features[f]=values.every(v=>v.value!==null)?values.map(v=>v.value) as [number,number]:null;}return {features,presence};}
export function validateObservation(o:Observation){exactKeys(o,['observationId','namespace','fixture','round','fixtureStatus','providerFetchedAt','sealCreatedAt','features','presence','rawResponseSha256','rawPath','endpoint','collectorVersion','completion','quality','role']);validateTarget(o.fixture);requireRule(o.namespace===NAMESPACE&&o.role==='PROSPECTIVE_INPUT_HISTORY_ONLY','ROLE_FIREWALL');requireRule(o.fixtureStatus==='FT'&&/^Regular Season - [1-9][0-9]*$/.test(o.round),'FT_STAGE_REQUIRED');requireRule(o.endpoint==='/fixtures/statistics?fixture='+o.fixture.fixtureId,'FIXTURE_REQUEST_IDENTITY');for(const t of [o.providerFetchedAt,o.sealCreatedAt,o.completion.providerFetchedAt])requireRule(Number.isFinite(Date.parse(t)),'OBSERVATION_TIME');requireRule(Date.parse(o.providerFetchedAt)<=Date.parse(o.sealCreatedAt)&&Date.parse(o.completion.providerFetchedAt)<=Date.parse(o.sealCreatedAt)&&Date.parse(o.completion.providerFetchedAt)>Date.parse(o.fixture.kickoffUtc),'OBSERVATION_TIME');for(const h of [o.rawResponseSha256,o.completion.rawHash])requireRule(/^[a-f0-9]{64}$/.test(h),'RAW_HASH');for(const n of [o.completion.homeGoals,o.completion.awayGoals])requireRule(Number.isSafeInteger(n)&&n>=0&&n<=100,'INVALID_FT_SCORE');exactKeys(o.features,['xG','shots','sot']);exactKeys(o.presence,['xG','shots','sot']);for(const f of Object.keys(TYPES) as Feature[]){const v=o.features[f];requireRule(v===null||v.length===2&&v.every(n=>Number.isFinite(n)&&n>=0&&(f==='xG'||Number.isInteger(n))),'INVALID_VALUE');requireRule(o.presence[f].length===2,'PRESENCE');}requireRule(['VALID','MISSING_FEATURE','API_ERROR','IDENTITY_INVALID'].includes(o.quality),'QUALITY');}
export function verifyRawProjection(o:Observation){const b=readFileSync(o.rawPath);requireRule(sha(b)===o.rawResponseSha256,'RAW_REFERENCE_CHANGED');if(o.quality==='VALID'||o.quality==='MISSING_FEATURE'){const parsed=parse(JSON.parse(b.toString('utf8')),o.fixture);requireRule(digest(parsed.features)===digest(o.features)&&digest(parsed.presence)===digest(o.presence),'RAW_PROJECTION_MISMATCH');}}
export function append(root:string,input:Omit<Observation,'observationId'|'namespace'|'sealCreatedAt'|'collectorVersion'|'role'>,now=new Date().toISOString()){const o:Observation={...input,observationId:randomUUID(),namespace:NAMESPACE,sealCreatedAt:now,collectorVersion:'v31-r1-observation-v1',role:'PROSPECTIVE_INPUT_HISTORY_ONLY'};validateObservation(o);realpathSync(o.rawPath);verifyRawProjection(o);return writeSeal(join(storeRoot(root),'observations',o.observationId+'.json'),o);}
export function list(root:string){const p=join(storeRoot(root),'observations');if(!existsSync(p))return [];return readdirSync(p).filter(f=>f.endsWith('.json')).sort().map(f=>{const s=readSeal<Observation>(join(p,f));validateObservation(s.payload);verifyRawProjection(s.payload);return s;});}
