import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {DAY,validateTarget,selectTargets,causalHistory,targetOf,digest,REQUIRED,type Target,type Match,type Prediction} from './contracts-v1';
import {featureState,parseFeature,type FeatureRecord} from './feature-state-v1';
import {fitBeta,objective,choleskyDirection,initialize,KAPPA,type Example} from './ridge-offset-poisson-v1';
import {causalOffset,baseline} from './h2-causal-offset-v1';
import {prepare,predict} from './candidate-v1';
import {fitRates,predictRates} from '../football-poisson-v2-draw-research/evaluation-v1/h2-ridge-rates-v1';
import {joint} from '../football-poisson-v2-draw-research/evaluation-v1/numerics-v1';
import {compare,population} from './metrics-v1';
import {root,verifyParents,loadData} from './evidence-v1';
import {splitDevelopment} from './run-development-v1';
const t:Target={fixtureId:99999,leagueId:39,season:2023,kickoffUtc:'2023-12-20T12:00:00.000Z',homeTeamId:1,awayTeamId:2};
const rows:Match[]=Array.from({length:40},(_,i)=>({...t,fixtureId:i+1,kickoffUtc:new Date(Date.parse(t.kickoffUtc)-(80-i)*DAY).toISOString(),homeTeamId:i%2?2:1,awayTeamId:i%2?1:2,homeGoals:2,awayGoals:1}));
const features=rows.map(r=>({target:targetOf(r),values:{xG:[2,1],shots:[12,6],sot:[6,3]},sourceHash:'a'.repeat(64),providerFetchedAt:'2026-09-12T00:00:00.000Z'} as FeatureRecord));
const clone=<T>(x:T):T=>JSON.parse(JSON.stringify(x));
const offset:Prediction={status:'PREDICTED',reasons:[],p:joint(2,1).p,rates:[2,1],details:{}};
test('parent hashes and read-only holdout metadata',()=>verifyParents());
test('season 2025 target rejected',()=>assert.throws(()=>validateTarget({...t,season:2025}),/SEASON_FIREWALL/));
test('season 2025 is rejected even when not temporally eligible',()=>assert.throws(()=>selectTargets(t,[{...t,season:2025}]),/SEASON_FIREWALL/));
test('target own results and market fields rejected',()=>{for(const field of ['homeGoals','odds','ownerShadow','prediction'])assert.throws(()=>validateTarget({...t,[field]:1}),/FORBIDDEN/);});
test('48-hour equality excluded, earlier by 1ms included',()=>{const c=Date.parse(t.kickoffUtc)-1;const r={...t,fixtureId:1,kickoffUtc:new Date(c-2*DAY).toISOString()};assert.equal(selectTargets(t,[r]).length,0);r.kickoffUtc=new Date(c-2*DAY-1).toISOString();assert.equal(selectTargets(t,[r]).length,1);});
test('365-day lower boundary inclusive',()=>{const c=Date.parse(t.kickoffUtc)-1;const r={...t,fixtureId:1,kickoffUtc:new Date(c-365*DAY).toISOString()};assert.equal(selectTargets(t,[r]).length,1);r.kickoffUtc=new Date(c-365*DAY-1).toISOString();assert.equal(selectTargets(t,[r]).length,0);});
test('same kickoff and own fixture never selected',()=>assert.equal(selectTargets(t,[t,{...t,fixtureId:3}]).length,0));
test('league isolation before label lookup',()=>{let called=false;assert.equal(causalHistory(t,[{...rows[0],leagueId:140}].map(targetOf),()=>{called=true;return rows[0];}).length,0);assert.equal(called,false);});
for(const kind of ['own','future','league'] as const)test('feature history rejects '+kind,()=>{const f=clone(features);f[0].target=kind==='own'?t:kind==='future'?{...t,fixtureId:9,kickoffUtc:'2024-01-01T00:00:00.000Z'}:{...f[0].target,leagueId:140};assert.throws(()=>featureState('F1',t,f));});
test('duplicate feature ID rejected',()=>assert.throws(()=>featureState('F1',t,[...features,features[0]]),/DUPLICATE/));
test('For Against home-away reversal and arithmetic mean',()=>{const fs=features.slice(0,5).map(x=>({...x,target:{...x.target,homeTeamId:1,awayTeamId:2}}));const s=featureState('F1',t,fs);assert.deepEqual(s.home,[Math.log(2)-Math.log(1.5),Math.log(2)-Math.log(1.5)]);assert.deepEqual(s.away,[Math.log(1)-Math.log(1.5),Math.log(1)-Math.log(1.5)]);});
test('minimum exactly 5 accepted and 4 PASS',()=>{assert(featureState('F1',t,features.slice(0,5)));assert.throws(()=>featureState('F1',t,features.slice(0,4)),/PASS_INSUFFICIENT_FEATURE_HISTORY/);});
test('feature-specific masks and F3 reuses F1 representation',()=>{const fs=clone(features);fs[0].values.xG=null;const one=featureState('F1',t,fs),two=featureState('F2',t,fs),three=featureState('F3',t,fs);assert.equal(one.audit[0].eligibleIds.length,39);assert.equal(two.audit[0].eligibleIds.length,40);assert.deepEqual(three.home,[...one.home,...two.home]);});
test('F2 does not inspect invalid xG',()=>{const fs=clone(features);fs[0].values.xG=[NaN,1];assert(featureState('F2',t,fs));assert.throws(()=>featureState('F1',t,fs),/INVALID_RAW_FEATURE_VALUE/);});
test('missing feature excludes only layer; base history intact',()=>{const fs=clone(features);fs[0].target.fixtureId=1223728;fs[0].values={xG:null,shots:null,sot:null};const base=rows.map((r,i)=>i? r:{...r,fixtureId:1223728});const h=causalHistory(t,base.map(targetOf),x=>base.find(r=>r.fixtureId===x.fixtureId)!);assert.equal(h.length,40);assert(h.some(r=>r.fixtureId===1223728));assert.equal(featureState('F3',t,fs).audit[0].eligibleIds.length,39);});
test('zero observations valid; zero mean yields PASS',()=>{const fs=clone(features);for(const r of fs)r.values.xG=[0,0];assert.throws(()=>featureState('F1',t,fs),/PASS_NONPOSITIVE_FEATURE_MEAN/);});
test('nonfinite input is INVALID, no epsilon',()=>{const fs=clone(features);fs[0].values.xG=[Infinity,1];assert.throws(()=>featureState('F1',t,fs),/INVALID_RAW_FEATURE_VALUE/);});
test('empty provider statistics unavailable',()=>assert.equal(parseFeature({errors:[],response:[]},t,'xG'),null));
test('raw explicit null remains unavailable',()=>assert.equal(parseFeature({response:[{team:{id:1},statistics:[{type:'expected_goals',value:null}]}]},t,'xG'),null));
test('invalid raw empty-string rejected',()=>assert.throws(()=>parseFeature({response:[{team:{id:1},statistics:[{type:'expected_goals',value:''}]}]},t,'xG'),/INVALID_RAW_FEATURE_VALUE/));
test('wrong provider identity rejected',()=>assert.throws(()=>parseFeature({response:[{team:{id:8},statistics:[]}]},t,'xG'),/INVALID_TEAM_BLOCKS/));
for(const [candidate,d] of [['F1',2],['F2',4],['F3',6]] as const)test(candidate+' dimension and beta-zero H2 equivalence',()=>{assert.equal(REQUIRED[candidate].length*2,d);const p=predict(candidate,t,features,offset,initialize(d));assert.equal(p.status,'PREDICTED');p.rates!.forEach((r,i)=>assert(Math.abs(r-offset.rates![i])<=1e-12));p.p!.forEach((r,i)=>assert(Math.abs(r-offset.p![i])<=1e-10));});
test('H2 PASS preserved',()=>{const p={...offset,status:'PASS' as const,reasons:['PASS_TEST'],p:null,rates:null};assert.deepEqual(prepare('F1',t,features,p).prediction,p);});
test('fresh causal H2 matches frozen estimator exactly',()=>{const h=causalHistory(t,rows.map(targetOf),x=>rows.find(r=>r.fixtureId===x.fixtureId)!);const direct=fitRates(h);assert.equal(direct.status,'FITTED');if(direct.status!=='FITTED')return;const p=causalOffset(t,h);assert.deepEqual(p.rates,predictRates(direct.parameters,t,h));assert.deepEqual(p.p,joint(...p.rates!).p);assert.equal(p.details.parameterHash,digest(direct.parameters));assert.equal(baseline(t,h).status,'PREDICTED');});
const examples:Example[]=rows.map((r,i)=>({target:targetOf(r),home:[Math.sin(i),0.1*(i%3)],away:[0.2*(i%5),Math.cos(i)],offset:[1.5,1.1],goals:[2,1]}));
test('ridge and zero initialization frozen',()=>{assert.equal(KAPPA,0.01);assert.deepEqual(initialize(4),[0,0,0,0]);});
test('analytic gradient agrees with finite differences',()=>{const b=[0.1,-0.2],s=objective(examples,b),eps=1e-5;for(let j=0;j<2;j++){const l=[...b],r=[...b];l[j]-=eps;r[j]+=eps;assert(Math.abs(s.g[j]-(objective(examples,r).value-objective(examples,l).value)/(2*eps))<1e-7);}});
test('analytic Hessian agrees with gradient differences',()=>{const b=[0.1,-0.2],s=objective(examples,b),eps=1e-5;for(let j=0;j<2;j++){const l=[...b],r=[...b];l[j]-=eps;r[j]+=eps;for(let k=0;k<2;k++)assert(Math.abs(s.h[k][j]-(objective(examples,r).g[k]-objective(examples,l).g[k])/(2*eps))<1e-7);}});
test('Cholesky solves Newton equation',()=>assert.deepEqual(choleskyDirection([[2,0],[0,4]],[2,4]).map(x=>Math.round(x)),[-1,-1]));
test('Cholesky no jitter fallback',()=>assert.throws(()=>choleskyDirection([[0]],[1]),/FAIL_NUMERICAL/));
test('deterministic fit and convergence',()=>{const a=fitBeta(examples,2),b=fitBeta(examples,2);assert.equal(a.status,'FITTED');assert.deepEqual(a,b);assert(Number(a.diagnostics.gradientInfinity)<=1e-7);});
test('fit count below 30 is PASS',()=>assert.equal(fitBeta(examples.slice(0,29),2).status,'PASS'));
test('2024 beta fitting rejected',()=>{const xs=clone(examples);xs[0].target.season=2024;assert.equal(fitBeta(xs,2).status,'INVALID');});
test('2025 beta fitting rejected',()=>{const xs=clone(examples);xs[0].target.season=2025;assert.equal(fitBeta(xs,2).status,'INVALID');});
test('cross league beta fitting rejected',()=>{const xs=clone(examples);xs[0].target.leagueId=140;assert.equal(fitBeta(xs,2).status,'INVALID');});
test('fixed intersection and no survivor metrics',()=>{const pre=rows.slice(0,2).map(r=>({target:targetOf(r),v1:offset,h2:offset}));assert.equal(population(pre).ids.length,2);const p={...offset,status:'PASS' as const,p:null,rates:null,reasons:['PASS_TEST']};const cmp=compare(pre,[offset,p],rows.slice(0,2));assert.equal(cmp.pairedCount,2);assert.equal(cmp.candidate,null);assert.equal(cmp.full.targets,2);});
test('metric rejects 2025 identity before scoring',()=>assert.throws(()=>population([{target:{...t,season:2025},v1:offset,h2:offset}]),/SEASON_FIREWALL/));
test('runtime source has no holdout raw path or network',()=>{const s=readFileSync(join(root,'scripts/football-v3-feature-research-v1/evidence-v1.ts'),'utf8');assert(!s.includes('football-v3-2025-holdout-seal-v1/2026-09-12T09'));assert(!/\bfetch\s*\(/.test(s));});
test('data loader permits metadata only until exposed enabled',()=>{const data=loadData();const target=data.targets.find(t=>t.season===2024)!;assert.throws(()=>data.score(target),/EXPOSED_LABELS_NOT_ENABLED/);assert.throws(()=>data.feature({...target,season:2025},'F1'),/SEASON_FIREWALL/);});
test('initial fit boundary requires labels to have passed 48h',()=>{const times=['2023-12-29T23:59:59.999Z','2023-12-30T00:00:00.000Z','2023-12-31T00:00:00.000Z','2024-01-01T00:00:00.000Z'];const r=times.map((kickoffUtc,i)=>({target:{...t,fixtureId:i+1,kickoffUtc},v1:offset,h2:offset}));const s=splitDevelopment(r);assert.deepEqual(s.initial.map(x=>x.target.fixtureId),[1]);assert.deepEqual(s.checks.map(x=>x.target.fixtureId),[4]);});
test('feature integrity remains required on H2 PASS',()=>{const p={...offset,status:'PASS' as const,reasons:['PASS_TEST'],p:null,rates:null};assert.throws(()=>prepare('F1',t,[{...features[0],target:t}],p),/TARGET_FUTURE_OR_FOREIGN_FEATURE/);});
