import {readFileSync,readdirSync,realpathSync} from 'node:fs';
import {join,resolve,relative} from 'node:path';
import {fileURLToPath} from 'node:url';
import {sha,digest,hashEqual,requireRule,V31_SCHEMA} from './contracts-v1';
import {read,readSeal,writeSeal,git,censusMetadata} from '../football-v3-feature-research-v1/evidence-v1';
export {read,readSeal,writeSeal,git,censusMetadata};
export const root=fileURLToPath(new URL('../../',import.meta.url)),code=join(root,'scripts/football-v31-incremental-feature-research-v1'),output=resolve(root,'../YANG-EDGE-INBOX/football-v31-development-v1'),sourceSealPath=join(root,'data/audits/football-v31-source-freeze-v1.json');
export const parents=[['docs/FOOTBALL_V31_INCREMENTAL_FEATURE_RESEARCH_PROTOCOL_V1.json','04d7a0029d70c031fcc3fcb443dca56c6a08f7d1c64c5051570af4dd4117ebfb'],['docs/FOOTBALL_V31_ALGORITHM_DESIGN_FREEZE_V1.json','8ed600a7a97ed7276dbadf1fc9eaff518e03101090b9d952563877116f3ff264'],['data/audits/football-v3-2025-independent-holdout-cohort-seal-v1.json','7924420956e419af1a7f14b8b2eb520cc55d37b46534736d35b0fbdcf51c2581']] as const;
const auditDoc='docs/FOOTBALL_V31_OMISSION_AUDIT_V1.md';
const baselineCommit='2763ce8aee4594c4ae48776b46254bf348cab32c';
export function verifyParents(){for(const [p,h]of parents)hashEqual(readSeal<unknown>(join(root,p)).sha256,h);requireRule(readFileSync(join(root,auditDoc),'utf8').replaceAll('\r\n','\n')===git('show',baselineCommit+':'+auditDoc).replaceAll('\r\n','\n')+'\n','OMISSION_AUDIT_CHANGED');}
function under(dir:string):string[]{return readdirSync(dir,{withFileTypes:true}).flatMap(x=>x.isDirectory()?under(join(dir,x.name)):x.name.endsWith('.ts')?[join(dir,x.name)]:[]);}
export function sourceFiles(){return Object.fromEntries(under(code).sort().map(p=>[relative(root,p).replaceAll('\\','/'),sha(readFileSync(p,'utf8').replaceAll('\r\n','\n'))]));}
export function dependencies(){const phase1=readSeal<{dependencies:Record<string,string>}>(join(root,'data/audits/football-v3-feature-source-freeze-v1.json')).payload;return {...phase1.dependencies,...Object.fromEntries(under(join(root,'scripts/football-v3-feature-research-v1')).sort().map(p=>[relative(root,p).replaceAll('\\','/'),sha(readFileSync(p))]))};}
export function preservation(){const old=readSeal<{preserved:Record<string,string>;files:Record<string,string>;dependencies:Record<string,string>}>(join(root,'data/audits/football-v3-feature-source-freeze-v1.json')).payload;
  for(const [p,h]of Object.entries(old.files))hashEqual(sha(readFileSync(join(root,p),'utf8').replaceAll('\r\n','\n')),h);for(const g of [old.preserved,old.dependencies])for(const [p,h]of Object.entries(g))hashEqual(sha(readFileSync(join(root,p))),h);
  const extras=[...Object.keys(old.files),...parents.map(x=>x[0]),auditDoc,'docs/FOOTBALL_V31_ALGORITHM_DESIGN_FREEZE_V1.md','data/audits/football-v3-feature-source-freeze-v1.json','data/audits/football-v3-feature-development-v1.json','data/audits/football-v3-feature-2024-exposed-check-v1.json','data/audits/football-v3-phase1-diagnostic-review-v1.json','docs/FOOTBALL_V3_FEATURE_DEVELOPMENT_V1.md','docs/FOOTBALL_V3_FEATURE_2024_EXPOSED_CHECK_V1.md','docs/FOOTBALL_V3_PHASE1_DIAGNOSTIC_REVIEW_V1.md'];
  return {...old.preserved,...old.dependencies,...Object.fromEntries(extras.map(p=>[p,sha(readFileSync(join(root,p)))]))};
}
export function sealSource(){verifyParents();requireRule(git('status','--porcelain').split('\n').every(l=>!l||l==='?? docs/FOOTBALL_CURRENT_SEASON_DATA_ACCESS_GATE_V1.md'),'SOURCE_COMMIT_DIRTY');const c=censusMetadata();return writeSeal(sourceSealPath,{schemaVersion:'FOOTBALL_V31_SOURCE_FREEZE_V1',createdAt:new Date().toISOString(),sourceCommit:git('rev-parse','HEAD'),runtime:{node:process.version,platform:process.platform,arch:process.arch},parents,omissionAuditByteHash:sha(readFileSync(join(root,auditDoc))),files:sourceFiles(),testHashes:Object.fromEntries(Object.entries(sourceFiles()).filter(([p])=>p.includes('test'))),dependencies:dependencies(),inputSchema:V31_SCHEMA,inputSchemaHash:digest(V31_SCHEMA),censusHash:c.sha256,inputHashes:c.payload.records.map(r=>({fixtureId:r.fixtureId,season:r.season,sha256:r.sourceHash})),preserved:preservation(),tests:read<unknown>(join(output,'pre-result-tests.json')),fittingExecuted:false,candidateResultsViewed:false});}
export function verifySource(){verifyParents();const s=readSeal<{files:Record<string,string>;dependencies:Record<string,string>;preserved:Record<string,string>;inputSchemaHash:string;runtime:{node:string}}>(sourceSealPath);hashEqual(digest(s.payload.files),digest(sourceFiles()));hashEqual(digest(s.payload.dependencies),digest(dependencies()));hashEqual(digest(s.payload.preserved),digest(preservation()));hashEqual(s.payload.inputSchemaHash,digest(V31_SCHEMA));requireRule(s.payload.runtime.node===process.version,'RUNTIME_CHANGED');requireRule(git('rev-parse','HEAD')===git('rev-parse','origin/agent/astra/football-historical-source-gate-v1'),'SOURCE_NOT_PUSHED');requireRule(digest(JSON.parse(git('show','HEAD:data/audits/football-v31-source-freeze-v1.json')))===digest(s),'SOURCE_SEAL_NOT_COMMITTED');return s;}
export function exactRawFile(rootDir:string,file:string){requireRule(realpathSync(file)===join(realpathSync(rootDir),file.split(/[\\/]/).pop()!),'RAW_PATH_FIREWALL');}
