import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {DAY,BOUNDARY,validateTarget,selectTargets,targetOf,digest,beforeInputRead,hashEqual,type Target,type Match} from './contracts-v1';
import {buildAnchor,project,condition,assertAnchor,type Condition,type Pair} from './causal-state-v1';
import {fitPrefix,prefixPool,fitStageMap,transform,normalEquations,solveMaps,residual,type Parameters} from './residual-map-v1';
import {predict,fitCandidate} from './candidate-v1';
import {featureState,parseFeature,type FeatureRecord} from '../football-v3-feature-research-v1/feature-state-v1';
import {objective,choleskyDirection,type Example} from '../football-v3-feature-research-v1/ridge-offset-poisson-v1';
import {fitRates,predictRates} from '../football-poisson-v2-draw-research/evaluation-v1/h2-ridge-rates-v1';
import {compare,population} from '../football-v3-feature-research-v1/metrics-v1';
import {loadData,indexArchive} from './data-v1';
import {root,verifyParents} from './evidence-v1';
import {split} from './run-development-v1';
import {pearson,ranks,distribution} from './diagnostics-v1';
const t:Target={fixtureId:90000,leagueId:39,season:2023,kickoffUtc:'2023-12-20T12:00:00.000Z',homeTeamId:1,awayTeamId:2};
const base:Match[]=Array.from({length:40},(_,i)=>({...t,fixtureId:i+1,kickoffUtc:new Date(Date.parse('2023-07-01T00:00:00.000Z')+i*DAY).toISOString(),homeTeamId:i%2?2:1,awayTeamId:i%2?1:2,homeGoals:2,awayGoals:1}));
const features:FeatureRecord[]=base.map(r=>({target:targetOf(r),values:{xG:[2,1],shots:[12,6],sot:[6,3]},sourceHash:'a'.repeat(64),providerFetchedAt:'2026-09-12T00:00:00.000Z'}));
const clone=<T>(x:T):T=>JSON.parse(JSON.stringify(x));
const state=buildAnchor(t,base,features),anchors=Array.from({length:12},(_,i)=>buildAnchor({...t,fixtureId:100+i,kickoffUtc:new Date(Date.parse('2023-10-01T00:00:00.000Z')+i*3*DAY).toISOString()},base,features).anchor);
const prefix=fitPrefix(t,prefixPool(t,anchors)),initial=fitStageMap('INITIAL',39,anchors,anchors.map(a=>a.target),Date.parse('2026-01-01T00:00:00.000Z')),final=fitStageMap('FINAL',39,anchors,anchors.map(a=>a.target),Date.parse('2026-01-01T00:00:00.000Z'));
test('parents protocol/design/holdout metadata hashes and omission doc unchanged',()=>verifyParents());
test('hand projection exact ordered sums and divide',()=>assert.deepEqual(project([1,2,4,5,7,8]),[4,5]));
test('projection rejects invalid dimension and nonfinite',()=>{assert.throws(()=>project([1,2]));assert.throws(()=>project([1,2,3,4,5,NaN]));});
const manual=[[-1,0],[1,0],[0,-1],[0,1],[0,0]].map(([x,y])=>({h:[1,x,y] as Condition,q:[2+3*x-y,-1+.5*x+2*y] as Pair}));
test('hand-calculated R1 normal equation A and b',()=>{const n=normalEquations(manual);assert.deepEqual(n.A,[[1,0,0],[0,.41000000000000003,0],[0,0,.41000000000000003]]);assert.deepEqual(n.b,[[2,1.2,-.4],[-1,.2,.8]]);});
test('hand-calculated map coefficients and intercept unpenalized',()=>{const n=normalEquations(manual),a=solveMaps(n.A,n.b),expected=[[2,1.2/.41,-.4/.41],[-1,.2/.41,.8/.41]];a.flat().forEach((v,i)=>assert(Math.abs(v-expected.flat()[i])<1e-12));});
test('residual q minus ordered h dot a identity',()=>{const a:Parameters=[[1,2,3],[4,5,6]];assert.deepEqual(residual([10,30],[1,2,3],a),[-4,-2]);});
test('R1 normal solver rejects nonpositive pivot no jitter',()=>assert.throws(()=>solveMaps([[0,0,0],[0,1,0],[0,0,1]],[[1,1,1],[1,1,1]]),/FAIL_MAP_CHOLESKY/));
test('nonfinite map response rejected',()=>assert.throws(()=>normalEquations([{h:[1,0,0],q:[NaN,2]}]),/INVALID_MAP_ROW/));
test('representation count four PASS, five FITTED',()=>{assert.equal(fitPrefix(t,anchors.slice(0,4)).fit.status,'PASS');assert.equal(fitPrefix(t,anchors.slice(0,5)).fit.status,'FITTED');});
test('R1 prefix seal records exact IDs/input/map parameter hashes',()=>{assert.equal(prefix.count,12);assert.equal(prefix.fixtureIdsHash,digest(anchors.map(a=>a.target.fixtureId)));assert.equal(prefix.inputHash,digest(anchors));assert.equal(prefix.parameterHash,digest(prefix.fit.parameters));});
test('prefix rejects own anchor, no self response',()=>assert.equal(fitPrefix(t,[...anchors,state.anchor]).fit.status,'INVALID'));
test('prefix rejects future anchor',()=>{const future=buildAnchor({...t,fixtureId:80001,kickoffUtc:'2023-12-25T00:00:00.000Z'},base,features).anchor;assert.equal(fitPrefix(t,[...anchors,future]).fit.status,'INVALID');});
test('same kickoff prefix anchor excluded and direct pool rejected',()=>{const same=buildAnchor({...t,fixtureId:80002},base,features).anchor;assert.equal(prefixPool(t,[...anchors,same]).length,12);assert.equal(fitPrefix(t,[...anchors,same]).fit.status,'INVALID');});
test('prefix target 2024 rejected before fitting',()=>assert.throws(()=>fitPrefix({...t,season:2024},anchors),/MAP_FIT_SEASON/));
test('future source season rejected even before temporal selection',()=>assert.throws(()=>prefixPool(t,[{...state.anchor,target:{...t,season:2025}}]),/SEASON_FIREWALL/));
test('final map never used to transform beta training target',()=>assert.throws(()=>transform(state.anchor,final,'TRAIN'),/FINAL_MAP_BACKFILL/));
test('initial map never used to transform beta training target',()=>assert.throws(()=>transform(state.anchor,initial,'TRAIN'),/FINAL_MAP_BACKFILL/));
test('prefix target identity enforced',()=>assert.throws(()=>transform(anchors[11],prefix,'TRAIN'),/FINAL_MAP_BACKFILL/));
test('nested causality rejects history after anchor m even if before outer T',()=>{const m=anchors[0].target;const bad=clone(features);bad[0].target.kickoffUtc='2023-10-10T00:00:00.000Z';assert.throws(()=>buildAnchor(m,base,bad),/TARGET_FUTURE_OR_FOREIGN_FEATURE/);});
test('nested base-result history after m rejected',()=>{const bad=clone(base);bad[0].kickoffUtc='2023-10-10T00:00:00.000Z';assert.throws(()=>buildAnchor(anchors[0].target,bad,features),/TEMPORAL_OR_LEAGUE_LEAKAGE/);});
test('mutation of later eligible-to-T feature does not change m causal selection',()=>{const later={...t,fixtureId:80003,kickoffUtc:'2023-10-15T00:00:00.000Z'};assert.deepEqual(selectTargets(anchors[0].target,[...base.map(targetOf),later]),base.map(targetOf));});
test('unattested or tampered q anchor rejected',()=>{assert.throws(()=>assertAnchor(clone(state.anchor)),/UNTRUSTED/);const b=buildAnchor(t,base,features).anchor;b.q![0][0]+=1;assert.throws(()=>assertAnchor(b),/UNTRUSTED/);});
test('48h equality excluded and 1ms older included',()=>{const c=Date.parse(t.kickoffUtc)-1,r={...t,fixtureId:80004,kickoffUtc:new Date(c-2*DAY).toISOString()};assert.equal(selectTargets(t,[r]).length,0);r.kickoffUtc=new Date(c-2*DAY-1).toISOString();assert.equal(selectTargets(t,[r]).length,1);});
test('365d equality included and older by1ms excluded',()=>{const c=Date.parse(t.kickoffUtc)-1,r={...t,fixtureId:80005,kickoffUtc:new Date(c-365*DAY).toISOString()};assert.equal(selectTargets(t,[r]).length,1);r.kickoffUtc=new Date(c-365*DAY-1).toISOString();assert.equal(selectTargets(t,[r]).length,0);});
for(const field of ['homeGoals','actualScore','odds','ownerShadow','providerPrediction','xG'])test('target forbids '+field,()=>assert.throws(()=>validateTarget({...t,[field]:1}),/FORBIDDEN/));
for(const kind of ['own','future','league']as const)test('feature history rejects '+kind,()=>{const f=clone(features);f[0].target=kind==='own'?t:kind==='future'?{...t,fixtureId:80006,kickoffUtc:'2023-12-25T00:00:00.000Z'}:{...f[0].target,leagueId:140};assert.throws(()=>buildAnchor(t,base,f));});
test('base and feature team identities must match',()=>{const f=clone(features);[f[0].target.homeTeamId,f[0].target.awayTeamId]=[f[0].target.awayTeamId,f[0].target.homeTeamId];assert.throws(()=>buildAnchor(t,base,f),/BASE_FEATURE_IDENTITY/);});
test('For Against reversal with fixed projection',()=>{const f=features.slice(0,5).map(x=>({...x,target:{...x.target,homeTeamId:1,awayTeamId:2}}));const s=featureState('F3',t,f);const h=(((Math.log(2)-Math.log(1.5))+(Math.log(12)-Math.log(9)))+(Math.log(6)-Math.log(4.5)))/3,a=(((Math.log(1)-Math.log(1.5))+(Math.log(6)-Math.log(9)))+(Math.log(3)-Math.log(4.5)))/3;assert.deepEqual(project(s.home),[h,h]);assert.deepEqual(project(s.away),[a,a]);assert.deepEqual(condition([2,1])[0],condition([1,2])[1]);});
test('feature min history5 and4 PASS',()=>{assert(featureState('F3',t,features.slice(0,5)));assert.throws(()=>featureState('F3',t,features.slice(0,4)),/PASS_INSUFFICIENT_FEATURE_HISTORY/);});
test('feature specific masks not joint mask',()=>{const f=clone(features);f[0].values.xG=null;const s=featureState('F3',t,f);assert.deepEqual(s.audit.map(a=>a.eligibleIds.length),[39,40,40]);assert.equal(base.length,40);});
test('missing/null/zero/invalid distinct',()=>{assert.equal(parseFeature({response:[]},t,'xG'),null);assert.equal(parseFeature({response:[{team:{id:1},statistics:[]}]},t,'xG'),null);const raw=(v:unknown)=>({response:[1,2].map(id=>({team:{id},statistics:[{type:'expected_goals',value:v}]}))});assert.equal(parseFeature(raw(null),t,'xG'),null);assert.deepEqual(parseFeature(raw(0),t,'xG'),[0,0]);assert.throws(()=>parseFeature(raw(''),t,'xG'));assert.throws(()=>parseFeature(raw(-1),t,'xG'));});
test('zero required mean PASS no epsilon',()=>{const f=clone(features);f.forEach(x=>x.values.xG=[0,0]);assert.throws(()=>featureState('F3',t,f),/PASS_NONPOSITIVE_FEATURE_MEAN/);});
test('duplicate provider identities rejected',()=>assert.throws(()=>parseFeature({response:[{team:{id:1},statistics:[]},{team:{id:1},statistics:[]}]},t,'xG')));
test('fresh H2 causal equivalence to frozen estimator',()=>{const f=fitRates(base);assert.equal(f.status,'FITTED');if(f.status==='FITTED'){assert.deepEqual(state.h2.rates,predictRates(f.parameters,t,base));assert.equal(state.h2.details.parameterHash,digest(f.parameters));}});
test('R1/R3 each two beta parameters, zero beta H2 equivalence',()=>{const check=buildAnchor({...t,season:2024,kickoffUtc:'2024-02-01T00:00:00.000Z'},base,features);for(const c of ['V31-R1','V31-R3']as const){const p=predict(c,check.anchor,c==='V31-R1'?final:null,[0,0]);assert.equal(p.status,'PREDICTED');p.p!.forEach((v,i)=>assert(Math.abs(v-check.h2.p![i])<1e-10));assert.throws(()=>predict(c,check.anchor,c==='V31-R1'?final:null,[0,0,0]),/INVALID_BETA_DIMENSION/);}});
test('initial map immutable through multiple internal checks',()=>{const hash=digest(initial);for(const day of [1,3]){const a=buildAnchor({...t,kickoffUtc:`2024-01-0${day}T00:00:00.000Z`},base,features).anchor;assert.equal(predict('V31-R1',a,initial,[.1,.1]).status,'PREDICTED');}assert.equal(digest(initial),hash);});
test('final map immutable through2024 and initial map rejected',()=>{const hash=digest(final),a=buildAnchor({...t,season:2024,kickoffUtc:'2024-02-01T00:00:00.000Z'},base,features).anchor;assert.equal(predict('V31-R1',a,final,[.1,.1]).status,'PREDICTED');assert.equal(predict('V31-R1',a,initial,[.1,.1]).status,'INVALID');assert.equal(digest(final),hash);});
test('2024 anchor rejected from map fit population',()=>{const a=buildAnchor({...t,season:2024,kickoffUtc:'2024-02-01T00:00:00.000Z'},base,features).anchor;assert.equal(fitStageMap('FINAL',39,[...anchors,a],anchors.map(a=>a.target),Date.now()).fit.status,'INVALID');});
test('map mutation detected even with valid dimensions',()=>{const m=fitPrefix(t,anchors);m.parameterHash='0'.repeat(64);assert.throws(()=>transform(state.anchor,m,'TRAIN'),/UNTRUSTED_OR_MUTATED_MAP/);});
test('deterministic repeated map/transform equality',()=>{assert.deepEqual(fitPrefix(t,anchors),fitPrefix(t,[...anchors].reverse()));assert.deepEqual(transform(state.anchor,prefix,'TRAIN'),transform(state.anchor,prefix,'TRAIN'));});
const examples:Example[]=base.map((r,i)=>({target:targetOf(r),home:[Math.sin(i),.1*(i%3)],away:[.2*(i%5),Math.cos(i)],offset:[1.5,1.1],goals:[2,1]}));
test('deterministic two-beta fitting and frozen convergence',()=>{const a=fitCandidate(examples),b=fitCandidate(examples);assert.equal(a.status,'FITTED');assert.deepEqual(a,b);assert.equal(a.parameters!.length,2);assert(Number(a.diagnostics.gradientInfinity)<=1e-7);assert.deepEqual(a.diagnostics.initialization,[0,0]);});
test('beta count29 PASS;2024fit INVALID',()=>{assert.equal(fitCandidate(examples.slice(0,29)).status,'PASS');const x=clone(examples);x[0].target.season=2024;assert.equal(fitCandidate(x).status,'INVALID');});
test('beta gradient and Hessian finite difference checks',()=>{const b=[.1,-.2],v=objective(examples,b),e=1e-5;for(let j=0;j<2;j++){const l=[...b],r=[...b];l[j]-=e;r[j]+=e;assert(Math.abs(v.g[j]-(objective(examples,r).value-objective(examples,l).value)/(2*e))<1e-7);for(let k=0;k<2;k++)assert(Math.abs(v.h[k][j]-(objective(examples,r).g[k]-objective(examples,l).g[k])/(2*e))<1e-7);}});
test('beta optimizer rejects singular Cholesky no repair',()=>assert.throws(()=>choleskyDirection([[0]],[1]),/FAIL_NUMERICAL/));
test('source hash mismatch rejected',()=>assert.throws(()=>hashEqual('a','b'),/HASH_MISMATCH/));
test('2025 rejected BEFORE injected file read',()=>{let reads=0;assert.throws(()=>beforeInputRead({...t,season:2025},()=>{reads++;return 0;}),/SEASON_FIREWALL/);assert.equal(reads,0);});
test('actual loader rejects2025 and disabled2024 before scores/features',()=>{const data=loadData();const t24=data.targets.find(x=>x.season===2024)!;assert.throws(()=>data.score({...t24,season:2025}),/SEASON_FIREWALL/);assert.throws(()=>data.feature({...t24,season:2025}),/SEASON_FIREWALL/);assert.throws(()=>data.score(t24),/EXPOSED_NOT_ENABLED/);});
test('archive index preserves raw string without parsing scores',()=>{const s='{"matches":[{"providerFixtureId":1,"note":"} escaped \\\""},{"providerFixtureId":2,"score":"not decoded"}]}';const ix=indexArchive(s);assert.equal(ix.size,2);assert(ix.get(2)!.includes('not decoded'));});
test('fixed comparator U and missing candidate nulls primary',()=>{const pre=[{target:t,v1:state.v1,h2:state.h2}],pass={status:'PASS' as const,reasons:['PASS_TEST'],p:null,rates:null,details:{}};assert.equal(population(pre).ids.length,1);const c=compare(pre,[pass],[{...t,homeGoals:1,awayGoals:1}]);assert.equal(c.pairedCount,1);assert.equal(c.candidate,null);assert.equal(c.full.pass,1);});
test('split honors boundary plus48h and same kickoff',()=>{const rows=['2023-12-29T23:59:59.999Z','2023-12-30T00:00:00.000Z','2024-01-01T00:00:00.000Z'].map((kickoffUtc,i)=>({target:{...t,kickoffUtc,fixtureId:i+1}}));assert.equal(BOUNDARY,Date.parse(rows[2].target.kickoffUtc));assert.deepEqual(split(rows).initial.map(r=>r.target.fixtureId),[1]);assert.deepEqual(split(rows).checks.map(r=>r.target.fixtureId),[3]);});
test('diagnostic quantiles and tied ranks',()=>{assert.equal(distribution([1,2,3,4])!.p25,1.75);assert.deepEqual(ranks([3,1,1,2]),[4,1.5,1.5,3]);assert.equal(pearson([1,2,3],[3,2,1]),-1);assert.equal(pearson([1,1],[2,3]),null);});
test('no runtime network or holdout raw directory',()=>{const s=readFileSync(join(root,'scripts/football-v31-incremental-feature-research-v1/data-v1.ts'),'utf8');assert(!/\bfetch\s*\(/.test(s));assert(!s.includes('football-v3-2025-holdout-seal-v1/'));});
